package com.quiz.config.seeds;

public final class DatabaseSeeder {
    private static final String C = "Database";
    private DatabaseSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("In the database world, what does the acronym SQL stand for?", C, "Easy", "Structured Query Language", "Simple Query Language", "Sequential Query List", "Strong Query Language");
        a.add("Which SQL keyword is used to retrieve rows from a table?", C, "Easy", "SELECT", "FETCH", "GET", "READ");
        a.add("Which SQL clause is used to filter rows based on a condition?", C, "Easy", "WHERE", "FILTER", "HAVING", "IF");
        a.add("Which SQL clause sorts the result set by one or more columns?", C, "Easy", "ORDER BY", "SORT BY", "ARRANGE BY", "RANK BY");
        a.add("Which SQL clause groups rows that have the same values in specified columns?", C, "Easy", "GROUP BY", "AGGREGATE", "PARTITION", "SET");
        a.add("Which SQL clause limits the number of rows returned in many dialects (MySQL/PostgreSQL)?", C, "Easy", "LIMIT", "TOP only", "FIRST only", "FETCH FIRST only");
        a.add("Which SQL keyword inserts new rows into a table?", C, "Easy", "INSERT", "ADD", "CREATE", "PUT");
        a.add("Which SQL keyword modifies existing rows in a table?", C, "Easy", "UPDATE", "MODIFY", "EDIT", "ALTER");
        a.add("Which SQL keyword removes rows from a table?", C, "Easy", "DELETE", "REMOVE", "DROP ROW", "ERASE");
        a.add("Which SQL statement creates a new table?", C, "Easy", "CREATE TABLE", "MAKE TABLE", "NEW TABLE", "BUILD TABLE");
        a.add("Which SQL statement permanently deletes a table and its data?", C, "Easy", "DROP TABLE", "DELETE TABLE", "REMOVE TABLE", "TRUNCATE TABLE");
        a.add("Which SQL statement modifies the structure of an existing table?", C, "Easy", "ALTER TABLE", "EDIT TABLE", "MODIFY TABLE", "CHANGE TABLE");
        a.add("Which standard SQL wildcard matches any sequence of characters in a LIKE pattern?", C, "Easy", "%", "_", "*", "?");
        a.add("Which standard SQL wildcard matches exactly one character in a LIKE pattern?", C, "Easy", "_", "%", "?", ".");
        a.add("Which SQL predicate tests if a column's value is NULL?", C, "Easy", "IS NULL", "= NULL", "EQUALS NULL", "ISNULL ()");
        a.add("Which SQL predicate tests that a column's value is not NULL?", C, "Easy", "IS NOT NULL", "<> NULL", "NOT NULL", "EXISTS NULL");
        a.add("Which SQL keyword removes duplicate rows from a result set?", C, "Easy", "DISTINCT", "UNIQUE", "DEDUPE", "GROUP");
        a.add("Which SQL set operator combines results from multiple SELECT statements (removing duplicates)?", C, "Easy", "UNION", "JOIN", "INTERSECT only", "MERGE");
        a.add("Which SQL aggregate function returns the number of rows?", C, "Easy", "COUNT", "TOTAL", "NUMBER", "COUNT_ROWS");
        a.add("Which SQL aggregate function returns the smallest value in a column?", C, "Easy", "MIN", "LOW", "SMALLEST", "FLOOR");
        a.add("Which SQL aggregate function returns the largest value in a column?", C, "Easy", "MAX", "HIGH", "LARGEST", "CEILING");
        a.add("Which SQL aggregate function returns the arithmetic mean of a column's values?", C, "Easy", "AVG", "MEAN", "AVERAGE", "MED");
        a.add("Which SQL aggregate function returns the total of numeric values?", C, "Easy", "SUM", "TOTAL", "ADD", "PLUS");
        a.add("Which SQL data type is most commonly used for whole numbers?", C, "Easy", "INTEGER (INT)", "VARCHAR", "BOOLEAN", "FLOAT");
        a.add("Which SQL data type is most commonly used for variable-length text?", C, "Easy", "VARCHAR", "INT", "DATE", "BLOB");
        a.add("Which SQL data type is most commonly used for calendar dates (no time)?", C, "Easy", "DATE", "TIMESTAMP only", "INTERVAL", "STRING");
        a.add("Which SQL data type is most commonly used for date and time together?", C, "Easy", "TIMESTAMP (or DATETIME)", "DATE only", "TIME only", "INTERVAL");
        a.add("Which SQL data type represents true/false values?", C, "Easy", "BOOLEAN (or BIT)", "INT", "VARCHAR", "ENUM");
        a.add("Which SQL data type stores fixed-length character strings?", C, "Easy", "CHAR", "VARCHAR", "TEXT", "BLOB");
        a.add("What does a primary key uniquely identify in a relational table?", C, "Easy", "Each row in the table", "Each column", "Each transaction", "Each connection");
        a.add("A foreign key in a table typically references which constraint of another table?", C, "Easy", "The primary key (or a UNIQUE constraint)", "An index", "A view", "A sequence");
        a.add("Which constraint ensures that a column cannot have duplicate values?", C, "Easy", "UNIQUE", "PRIMARY KEY only", "INDEX only", "CHECK");
        a.add("Which constraint ensures that a column must always have a value?", C, "Easy", "NOT NULL", "UNIQUE", "DEFAULT", "REQUIRED");
        a.add("Which clause specifies a default value for a column when no value is provided?", C, "Easy", "DEFAULT", "SET DEFAULT", "INIT", "PRESET");
        a.add("Which constraint validates a column's value against a boolean expression at insert/update?", C, "Easy", "CHECK", "VALIDATE", "WHERE", "ASSERT");
        a.add("Which characters introduce a single-line comment in standard SQL?", C, "Easy", "--", "//", "#", "/*");
        a.add("Which characters delimit a multi-line comment in SQL?", C, "Easy", "/* ... */", "<!-- ... -->", "// ... //", "## ... ##");
        a.add("What does the abbreviation DBMS stand for?", C, "Easy", "Database Management System", "Distributed Backup Maintenance Service", "Data-Bound Monitoring System", "Database Memory Service");
        a.add("What does the abbreviation RDBMS stand for?", C, "Easy", "Relational Database Management System", "Reliable Database Management System", "Resilient Distributed Backup Memory System", "Recursive Data Block Management System");
        a.add("Which is a popular open-source RDBMS used widely in web stacks?", C, "Easy", "MySQL", "Microsoft Access", "DB2", "MS SQL Server (commercial)");
        a.add("Which open-source RDBMS is famous for advanced SQL features and standards compliance?", C, "Easy", "PostgreSQL", "Microsoft Access", "DB2 (commercial)", "Sybase ASE (commercial)");
        a.add("Which two RDBMSs are well-known commercial offerings?", C, "Easy", "Oracle Database and Microsoft SQL Server", "MySQL and PostgreSQL", "SQLite and MariaDB", "MongoDB and Cassandra");
        a.add("In database terminology, what does NoSQL most often expand to?", C, "Easy", "Not Only SQL", "Never SQL", "Non SQL", "Negated SQL");
        a.add("Which is a popular open-source document database?", C, "Easy", "MongoDB", "MySQL", "PostgreSQL", "Redis");
        a.add("Which is a widely used in-memory key-value store database?", C, "Easy", "Redis", "Cassandra", "MongoDB", "PostgreSQL");
        a.add("Which is a widely used graph database?", C, "Easy", "Neo4j", "MongoDB", "Redis", "Couchbase");
        a.add("Which is a widely used wide-column NoSQL store originally from Facebook (open-sourced)?", C, "Easy", "Apache Cassandra", "MongoDB", "Redis", "DynamoDB only");
        a.add("Which acronym represents the four classical transaction guarantees in RDBMSs?", C, "Easy", "ACID", "BASE", "CAP", "CRUD");
        a.add("In ACID, what does the 'A' stand for?", C, "Easy", "Atomicity", "Availability", "Asynchrony", "Authentication");
        a.add("Which is a small, file-based RDBMS commonly used in mobile and embedded apps?", C, "Easy", "SQLite", "PostgreSQL", "Oracle", "MySQL");

        // ===== Medium (50) =====
        a.add("Which SQL JOIN returns only rows that match in both joined tables?", C, "Medium", "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN");
        a.add("Which SQL JOIN returns all rows from the left table and matches from the right (NULLs otherwise)?", C, "Medium", "LEFT JOIN (LEFT OUTER JOIN)", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN");
        a.add("Which SQL JOIN returns all rows from the right table and matches from the left (NULLs otherwise)?", C, "Medium", "RIGHT JOIN (RIGHT OUTER JOIN)", "LEFT JOIN", "INNER JOIN", "FULL OUTER JOIN");
        a.add("Which SQL JOIN returns all rows from both tables, matching where possible?", C, "Medium", "FULL OUTER JOIN", "INNER JOIN", "LEFT JOIN", "CROSS JOIN");
        a.add("Which SQL JOIN returns the Cartesian product of two tables?", C, "Medium", "CROSS JOIN", "INNER JOIN", "FULL OUTER JOIN", "NATURAL JOIN");
        a.add("Which JOIN type joins a table to itself, often using table aliases?", C, "Medium", "SELF JOIN (a regular JOIN with aliases)", "REFLECT JOIN", "CIRCULAR JOIN", "CYCLIC JOIN");
        a.add("Which SQL keyword is used to assign an alias to a column or table?", C, "Medium", "AS", "ALIAS", "RENAME", "USING");
        a.add("Which SQL statement begins an explicit transaction in standard SQL?", C, "Medium", "START TRANSACTION (or BEGIN)", "OPEN TX", "TRANSACT", "TXN BEGIN");
        a.add("Which SQL statement permanently saves all changes made during a transaction?", C, "Medium", "COMMIT", "SAVE", "FLUSH", "PERSIST");
        a.add("Which SQL statement undoes all changes made during the current transaction?", C, "Medium", "ROLLBACK", "UNDO", "REVERT", "CANCEL");
        a.add("Which SQL statement creates a virtual table whose rows come from a stored query?", C, "Medium", "CREATE VIEW", "CREATE TABLE AS", "CREATE QUERY", "CREATE VIRTUAL");
        a.add("Which SQL statement creates a stored procedure?", C, "Medium", "CREATE PROCEDURE", "CREATE FUNCTION only", "DEFINE PROCEDURE", "MAKE PROCEDURE");
        a.add("Which SQL statement creates a user-defined function?", C, "Medium", "CREATE FUNCTION", "MAKE FUNCTION", "DEFINE FUNCTION", "CREATE METHOD");
        a.add("Which SQL statement creates a database trigger?", C, "Medium", "CREATE TRIGGER", "MAKE TRIGGER", "DEFINE TRIGGER", "CREATE EVENT");
        a.add("Which SQL statement creates an index on one or more columns?", C, "Medium", "CREATE INDEX", "MAKE INDEX", "DEFINE INDEX", "BUILD INDEX");
        a.add("Which kind of index physically orders the table's rows by its key columns?", C, "Medium", "Clustered index", "Non-clustered index", "Hash index", "Bitmap index");
        a.add("Which is the most common data structure used for general-purpose database indexes?", C, "Medium", "B-Tree (and B+Tree)", "Linked list", "Hash table only", "Array of pointers");
        a.add("What is the primary purpose of database normalization?", C, "Medium", "Reduce data redundancy and improve data integrity", "Speed up read queries always", "Increase storage usage", "Eliminate the need for indexes");
        a.add("First Normal Form (1NF) requires which property of column values?", C, "Medium", "Atomic (indivisible) values", "Globally unique values", "Numeric values only", "Foreign key values only");
        a.add("Third Normal Form (3NF) eliminates which kind of dependency beyond 2NF?", C, "Medium", "Transitive dependencies on the primary key", "Functional dependencies", "Subqueries", "Self-references");
        a.add("Boyce-Codd Normal Form (BCNF) is a stricter form requiring what about every nontrivial determinant?", C, "Medium", "It must be a candidate key", "It must include all foreign keys", "It must be the primary key only", "It must be sortable");
        a.add("Why might a database design intentionally include some denormalization?", C, "Medium", "To improve read performance at the cost of redundancy", "To violate ACID", "To make migrations harder", "To reduce backup size");
        a.add("What does JPA stand for?", C, "Medium", "Java Persistence API", "Java Persistent Application", "Java Programming Annotation", "Java Property Access");
        a.add("Which open-source library is the most widely used implementation of JPA?", C, "Medium", "Hibernate", "EclipseLink only", "OpenJPA only", "MyBatis");
        a.add("Which JPA EntityManager method makes a new entity persistent?", C, "Medium", "persist(entity)", "save(entity)", "store(entity)", "register(entity)");
        a.add("Which JPA EntityManager method merges a detached entity's state into a managed copy?", C, "Medium", "merge(entity)", "attach(entity)", "reattach(entity)", "rejoin(entity)");
        a.add("Which JPA EntityManager method removes a managed entity from the persistence context (and DB on flush)?", C, "Medium", "remove(entity)", "delete(entity)", "discard(entity)", "purge(entity)");
        a.add("Which JPA EntityManager method retrieves an entity by primary key?", C, "Medium", "find(EntityClass.class, id)", "fetch(...)", "get(...)", "load(...)");
        a.add("What does JPQL stand for?", C, "Medium", "Java Persistence Query Language", "Java Persistent Query Layer", "Java Programming Query Language", "Java Property Query Language");
        a.add("Which JPA cascade type cascades all operations from parent to child?", C, "Medium", "CascadeType.ALL", "CascadeType.PERSIST only", "CascadeType.MERGE only", "CascadeType.REFRESH only");
        a.add("In a JPA @OneToMany, which option, when true, deletes children that are removed from the parent collection?", C, "Medium", "orphanRemoval = true", "cascade = REMOVE only", "fetch = LAZY", "optional = false");
        a.add("In JPA, which fetch type defers loading until the association is accessed?", C, "Medium", "LAZY", "EAGER", "ON_DEMAND only", "ASYNC");
        a.add("In JPA, which fetch type loads the association immediately with the parent?", C, "Medium", "EAGER", "LAZY", "ALWAYS only", "SYNC");
        a.add("Which kind of cache, when enabled in Hibernate, is shared across multiple EntityManagers/sessions?", C, "Medium", "Second-level cache", "First-level cache only", "Query cache only (legacy)", "Third-level cache");
        a.add("Which Spring Data JPA repository interface adds paging and sorting beyond CrudRepository?", C, "Medium", "PagingAndSortingRepository (or JpaRepository)", "PageRepository only", "QueryRepository", "BasicRepository");
        a.add("In Spring Data JPA, how does a method like 'List<User> findByLastNameAndFirstName(...)' work?", C, "Medium", "It is a derived query whose method name maps to a SQL/JPQL query", "It calls a JNI native method", "It generates a stored procedure", "It does nothing without manual @Query");
        a.add("Which SQL keyword shows the execution plan for a query in many RDBMSs?", C, "Medium", "EXPLAIN (or EXPLAIN PLAN)", "PLAN", "TRACE", "EXEC PLAN");
        a.add("Which standard SQL transaction isolation level is the strictest?", C, "Medium", "SERIALIZABLE", "REPEATABLE READ", "READ COMMITTED", "READ UNCOMMITTED");
        a.add("Which SQL transaction isolation level allows reading uncommitted (dirty) writes?", C, "Medium", "READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE");
        a.add("What is the default transaction isolation level for PostgreSQL?", C, "Medium", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE", "READ UNCOMMITTED");
        a.add("What is the default transaction isolation level for MySQL InnoDB?", C, "Medium", "REPEATABLE READ", "READ COMMITTED", "SERIALIZABLE", "READ UNCOMMITTED");
        a.add("A 'dirty read' anomaly happens when a transaction reads what?", C, "Medium", "Data written by another, uncommitted transaction", "Its own writes", "Stale committed data", "Phantom rows from another query");
        a.add("A 'phantom read' anomaly is best described as which behavior?", C, "Medium", "A repeated query returns rows that newly match because of another transaction's inserts/deletes", "A row's value changes between two reads in the same transaction", "Reading uncommitted data", "Reading data that has been rolled back");
        a.add("A 'non-repeatable read' anomaly happens when which condition occurs?", C, "Medium", "The same row returns different values across two reads in the same transaction", "A new row appears between two queries", "Reading uncommitted data", "Reading rolled-back data");
        a.add("Which SQL isolation level prevents all standard read anomalies (including phantoms)?", C, "Medium", "SERIALIZABLE", "REPEATABLE READ", "READ COMMITTED", "READ UNCOMMITTED");
        a.add("Optimistic concurrency control is typically implemented in JPA using what mechanism?", C, "Medium", "A @Version column", "A SELECT FOR UPDATE", "An exclusive table lock", "A trigger");
        a.add("Pessimistic concurrency control is typically implemented in DB engines using what?", C, "Medium", "Row-level (or table) locks acquired during the transaction", "A version column only", "Compare-and-swap on a counter", "Optimistic retries only");
        a.add("Which SQL statement permanently removes all rows from a table much faster than a DELETE?", C, "Medium", "TRUNCATE TABLE", "DROP ROWS", "EMPTY TABLE", "CLEAR TABLE");
        a.add("Which SQL keyword introduces a Common Table Expression (CTE)?", C, "Medium", "WITH", "USING", "SET", "CTE");
        a.add("Which SQL clause filters groups produced by GROUP BY (using aggregate functions)?", C, "Medium", "HAVING (filters after grouping)", "WHERE (filters before grouping)", "FILTER", "QUALIFY");

        // ===== Hard (50) =====
        a.add("How does a B+ Tree index differ from a classical B-Tree?", C, "Hard", "Data is stored only in the leaves and the leaves are linked for efficient range scans", "B+ Tree has no internal nodes", "B+ Tree is unbalanced", "B+ Tree allows duplicates only");
        a.add("Which kind of index is most efficient for exact-match equality lookups, not range scans?", C, "Hard", "Hash index", "B-Tree index", "Bitmap index", "GiST index");
        a.add("Which kind of index is well-suited for low-cardinality columns, often used in OLAP workloads?", C, "Hard", "Bitmap index", "Hash index", "B-Tree index", "GIN index");
        a.add("What is a 'covering index' in database performance tuning?", C, "Hard", "An index that contains all columns needed by a query, avoiding table lookup", "An index built across multiple tables", "A primary key with foreign keys included", "An index that automatically rebuilds on idle");
        a.add("In a multi-column (composite) B-Tree index, which property explains why column order matters?", C, "Hard", "Leftmost-prefix matching: queries using the leftmost columns benefit most", "Right-most-prefix matching", "Random matching across columns", "Order does not matter");
        a.add("PostgreSQL's MVCC feature stands for what?", C, "Hard", "Multi-Version Concurrency Control", "Multi-Volume Cluster Control", "Master-Version Commit Cache", "Multi-Version Cache Coherence");
        a.add("Which port is the default TCP port for PostgreSQL?", C, "Hard", "5432", "3306", "1521", "1433");
        a.add("Which port is the default TCP port for MySQL?", C, "Hard", "3306", "5432", "1521", "1433");
        a.add("Which port is the default TCP port for Oracle Database listener?", C, "Hard", "1521", "1433", "3306", "5432");
        a.add("Which port is the default TCP port for Microsoft SQL Server?", C, "Hard", "1433", "1521", "3306", "5432");
        a.add("Which group of SQL statements is collectively called DML?", C, "Hard", "INSERT, UPDATE, DELETE (and SELECT)", "CREATE, ALTER, DROP", "GRANT, REVOKE", "COMMIT, ROLLBACK");
        a.add("Which group of SQL statements is collectively called DDL?", C, "Hard", "CREATE, ALTER, DROP, TRUNCATE", "INSERT, UPDATE, DELETE", "GRANT, REVOKE", "COMMIT, ROLLBACK");
        a.add("Which group of SQL statements is collectively called DCL?", C, "Hard", "GRANT, REVOKE", "COMMIT, ROLLBACK", "INSERT, UPDATE", "CREATE, DROP");
        a.add("Which group of SQL statements is collectively called TCL?", C, "Hard", "COMMIT, ROLLBACK, SAVEPOINT", "GRANT, REVOKE", "CREATE, DROP", "INSERT, UPDATE");
        a.add("Which kind of SQL feature lets you compute things like ROW_NUMBER, RANK, or moving averages over a partition?", C, "Hard", "Window functions (OVER (...) clause)", "Aggregate functions only", "Derived tables only", "Recursive CTEs only");
        a.add("Which SQL feature uses 'WITH RECURSIVE' to walk hierarchical data like trees?", C, "Hard", "Recursive Common Table Expressions (CTEs)", "Stored procedures only", "Cursors only", "Lateral joins only");
        a.add("Which kind of view physically stores its result set on disk and refreshes on demand?", C, "Hard", "Materialized view", "Virtual view (regular view)", "Inline view", "Indexed cursor");
        a.add("Which database design pattern horizontally partitions data across multiple servers by key?", C, "Hard", "Sharding", "Replication", "Indexing", "Partitioning by row size only");
        a.add("Which replication topology has one writer (leader) and many read-only replicas (followers)?", C, "Hard", "Primary-replica (leader-follower / master-slave)", "Multi-primary", "Peer-to-peer mesh", "Federated cluster");
        a.add("Which replication topology has multiple nodes that all accept writes?", C, "Hard", "Multi-primary (multi-master) replication", "Primary-replica only", "Read-only mesh", "Single-leader replication");
        a.add("What three properties does the CAP theorem name as a tradeoff in distributed data systems?", C, "Hard", "Consistency, Availability, Partition tolerance", "Consistency, Atomicity, Persistence", "Caching, Availability, Performance", "Concurrency, Availability, Persistence");
        a.add("Which acronym describes the eventual-consistency philosophy of many NoSQL stores?", C, "Hard", "BASE (Basically Available, Soft state, Eventually consistent)", "BACE", "BACS", "BASS");
        a.add("Which classical distributed transaction protocol uses a 'prepare' and 'commit' phase across resource managers?", C, "Hard", "Two-Phase Commit (2PC)", "Three-Phase Commit (3PC) only", "Saga only", "Eventual Consensus");
        a.add("Which pattern handles long-running distributed transactions via a sequence of compensating actions?", C, "Hard", "Saga pattern", "2PC", "Outbox pattern only", "Choreography only");
        a.add("Which pair of JDBC methods is used to perform efficient bulk inserts?", C, "Hard", "addBatch + executeBatch on PreparedStatement", "executeMany + commit only", "executeBulk + flush", "loop of execute(insert) only");
        a.add("Which is the default JDBC connection pool used by Spring Boot 2.x and later?", C, "Hard", "HikariCP", "Apache DBCP", "C3P0", "Tomcat JDBC Pool only");
        a.add("Which JDBC concept controls how many rows a result set fetches per network round trip?", C, "Hard", "Fetch size", "Batch size", "Pool size", "Cursor name");
        a.add("Which JDBC API protects against SQL injection by parameterizing queries?", C, "Hard", "PreparedStatement", "Statement", "ResultSet", "DatabaseMetaData");
        a.add("Which JDBC API is specifically designed for invoking stored procedures?", C, "Hard", "CallableStatement", "PreparedStatement", "Statement", "RowSet");
        a.add("Which JPA annotation specifies the foreign key column for an association?", C, "Hard", "@JoinColumn", "@JoinTable", "@PrimaryKeyJoinColumn only", "@ForeignKey only");
        a.add("Which JPA annotation defines a join table for a many-to-many relationship?", C, "Hard", "@JoinTable", "@JoinColumn", "@ManyToMany only", "@OneToMany only");
        a.add("Which JPA annotation lets a child entity share the same primary key as its parent in a one-to-one mapping?", C, "Hard", "@MapsId", "@SharedId", "@CopyId", "@PrimaryKeyJoinColumn only");
        a.add("Which JPA annotations let you embed a value object's columns into the owning entity's table?", C, "Hard", "@Embeddable on the value type and @Embedded on the field", "@Inline and @Inlinable", "@Compose and @Composer", "@Component and @Componentized");
        a.add("Which JPA inheritance strategy stores all concrete subclasses in a single table with a discriminator column?", C, "Hard", "SINGLE_TABLE", "JOINED", "TABLE_PER_CLASS", "MAPPED_SUPERCLASS only");
        a.add("Which JPA inheritance strategy stores each subclass's data in its own joined table?", C, "Hard", "JOINED", "SINGLE_TABLE", "TABLE_PER_CLASS", "EMBEDDED");
        a.add("Which JPA inheritance strategy puts each concrete subclass in its own complete table (no joins)?", C, "Hard", "TABLE_PER_CLASS", "JOINED", "SINGLE_TABLE", "COMPOSITE");
        a.add("Which infamous ORM performance issue causes 1 query for the parent and N queries for its children?", C, "Hard", "The N+1 query problem", "The K-way merge problem", "The transitive closure problem", "The Cartesian explosion problem");
        a.add("Which is a common solution for the N+1 query problem in JPA?", C, "Hard", "Use JOIN FETCH (or @EntityGraph) in the JPQL query", "Disable lazy loading globally", "Add more indexes", "Switch to optimistic locking");
        a.add("Which JPA exception is thrown when a lazy association is accessed outside an open persistence context?", C, "Hard", "LazyInitializationException", "EntityNotFoundException", "PersistenceException", "TransactionRequiredException");
        a.add("How do most relational engines resolve a deadlock between two transactions waiting on each other?", C, "Hard", "Detect the cycle and abort one of the transactions", "Halt the database server", "Block both transactions forever", "Silently merge the transactions");
        a.add("Which durable database feature ensures committed transactions can be recovered after a crash?", C, "Hard", "Write-Ahead Logging (WAL) / transaction log", "In-memory cache", "Cold backup only", "Read replicas");
        a.add("In Write-Ahead Logging (WAL), what is written first?", C, "Hard", "The log record describing the change, before applying the change to the data files", "The data page only", "The COMMIT marker only", "The checkpoint only");
        a.add("Which JPA query API lets you build queries programmatically using a typed object model?", C, "Hard", "Criteria API", "JPQL only", "QueryDSL (third-party)", "Native SQL only");
        a.add("Which Spring Data JPA annotation lets you write a JPQL query directly on a repository method?", C, "Hard", "@Query", "@Native", "@Sql", "@JpqlMethod");
        a.add("Which Spring Data feature lets you control eager fetching graphs declaratively per query?", C, "Hard", "@EntityGraph", "@FetchPlan", "@LoadGraph only", "@FetchAll only");
        a.add("Which standard SQL function returns the current date and time?", C, "Hard", "CURRENT_TIMESTAMP (or NOW())", "TODAY()", "DATETIME()", "STAMP()");
        a.add("Which SQL clause returns rows from one query that also appear in another (intersection)?", C, "Hard", "INTERSECT", "UNION", "EXCEPT", "MINUS only");
        a.add("Which SQL clause returns rows from the first query that do not appear in the second?", C, "Hard", "EXCEPT (or MINUS in Oracle)", "INTERSECT", "UNION ALL", "SUBTRACT");
        a.add("In PostgreSQL, which command lists all tables in the current schema (psql shortcut)?", C, "Hard", "\\dt", "SHOW TABLES;", "DESC TABLES;", "LIST TABLES;");
        a.add("Which database term describes a system optimized for analytical workloads (read-heavy, complex queries)?", C, "Hard", "OLAP (Online Analytical Processing)", "OLTP (Online Transaction Processing)", "ETL", "CRUD");
    }
}
