package com.quiz.config.seeds;

public final class FullstackIntegrationSeeder {
    private static final String C = "Fullstack Integration";
    private FullstackIntegrationSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("What does the acronym AJAX stand for?", C, "Easy", "Asynchronous JavaScript and XML", "Active Java And XML", "Async Javascript And eXchange", "Asynchronous Java Application eXchange");
        a.add("Which modern browser API for HTTP requests returns a Promise?", C, "Easy", "fetch", "XMLHttpRequest only", "axios only", "jQuery.ajax only");
        a.add("Until when does data stored in 'localStorage' typically persist?", C, "Easy", "Until explicitly cleared (no expiration by default)", "Until the tab is closed", "Until the browser is closed", "For 24 hours");
        a.add("Until when does data stored in 'sessionStorage' typically persist?", C, "Easy", "Until the tab/window is closed", "Forever, until cleared", "Until the browser restarts", "For 30 days");
        a.add("Which entity automatically attaches matching cookies to outgoing HTTP requests?", C, "Easy", "The browser", "The web server", "The DNS resolver", "The OS firewall");
        a.add("Which web security policy restricts scripts on one origin from accessing data on another?", C, "Easy", "The same-origin policy", "Same-port policy", "Cross-domain whitelist", "Universal access policy");
        a.add("What is the primary purpose of CORS?", C, "Easy", "To allow controlled cross-origin requests in browsers", "To prevent all cross-origin requests", "To enforce HTTPS", "To enable single sign-on");
        a.add("Calling fetch() returns which kind of object?", C, "Easy", "A Promise that resolves to a Response", "A string of HTML", "A JSON object directly", "A callback handle");
        a.add("Which two browser APIs are most commonly used to make HTTP requests from JavaScript?", C, "Easy", "fetch and XMLHttpRequest", "WebSocket and SSE", "navigator.send and XMLHttp", "Window.open and XHR");
        a.add("Which Content-Type is most commonly used for HTML form submissions (no files)?", C, "Easy", "application/x-www-form-urlencoded", "multipart/form-data", "application/json", "text/plain");
        a.add("Which Content-Type is most commonly used for JSON REST APIs?", C, "Easy", "application/json", "application/x-www-form-urlencoded", "text/plain", "application/xml");
        a.add("Which browser developer tools tab is used to inspect HTTP requests and responses?", C, "Easy", "Network", "Console", "Elements", "Sources");
        a.add("Which browser developer tools tab is used to view JavaScript source files?", C, "Easy", "Sources", "Network", "Elements", "Performance");
        a.add("Which browser developer tools tab is used to inspect the live DOM tree?", C, "Easy", "Elements", "Sources", "Network", "Memory");
        a.add("By default, which port does the Create React App development server start on?", C, "Easy", "3000", "8080", "5000", "4200");
        a.add("By default, which port does the Spring Boot embedded server start on?", C, "Easy", "8080", "3000", "5000", "9000");
        a.add("Which protocol provides bidirectional, full-duplex communication between client and server?", C, "Easy", "WebSocket", "HTTP/1.1 only", "FTP", "SSE only");
        a.add("From which protocol does a WebSocket connection start before being upgraded?", C, "Easy", "HTTP", "TCP raw", "QUIC", "FTP");
        a.add("Which URL scheme indicates a secure WebSocket connection?", C, "Easy", "wss://", "ws://", "https-ws://", "swss://");
        a.add("Server-Sent Events (SSE) provide which kind of communication?", C, "Easy", "One-way server-to-client streaming over HTTP", "Bidirectional", "Client-to-server only", "Peer-to-peer");
        a.add("Which Content-Type is used for Server-Sent Events?", C, "Easy", "text/event-stream", "application/event", "application/sse", "text/stream");
        a.add("In a Single-Page Application (SPA), how many HTML pages does the browser typically load initially?", C, "Easy", "One", "One per route", "Two (login and main)", "Many small pages");
        a.add("In a SPA, navigation between views is generally handled by what?", C, "Easy", "A JavaScript client-side router", "Server-side template engine", "Browser history full reload", "DNS-based routing");
        a.add("Which CSS selector targets all elements with the class 'btn'?", C, "Easy", ".btn", "#btn", "*btn", "btn");
        a.add("Which CSS selector targets the single element with id 'header'?", C, "Easy", "#header", ".header", "header", "*header");
        a.add("Which JavaScript method retrieves an element by its id attribute?", C, "Easy", "document.getElementById", "document.querySelectorAll", "document.findById", "document.getById");
        a.add("Which DOM API attaches an event listener to a node?", C, "Easy", "addEventListener", "attachEvent only", "onEvent", "bindEvent");
        a.add("Which JS method serializes a JavaScript value to a JSON string?", C, "Easy", "JSON.stringify", "JSON.parse", "JSON.serialize", "JSON.toString");
        a.add("Which JS method parses a JSON string into a JavaScript value?", C, "Easy", "JSON.parse", "JSON.stringify", "JSON.deserialize", "JSON.fromString");
        a.add("Which Content-Type is used for SVG images?", C, "Easy", "image/svg+xml", "image/svg", "application/svg", "image/xml-svg");
        a.add("Which Content-Type is most commonly used for CSS files served to the browser?", C, "Easy", "text/css", "application/css", "text/style", "css/text");
        a.add("Which Content-Type is most commonly used for JavaScript files in modern web?", C, "Easy", "text/javascript (or application/javascript)", "application/x-script", "text/script", "code/javascript");
        a.add("CDN stands for which?", C, "Easy", "Content Delivery Network", "Content Distribution Node", "Cached Domain Network", "Common Data Network");
        a.add("Which JavaScript Promise method runs once the Promise resolves successfully?", C, "Easy", ".then(...)", ".finally(...)", ".catch(...)", ".resolve(...)");
        a.add("Which JavaScript syntax pauses an async function until a Promise resolves?", C, "Easy", "await", "yield", "wait", "sync");
        a.add("Which JS function call performs a deep clone of structured data in modern browsers?", C, "Easy", "structuredClone", "Object.deepClone", "JSON.deepClone", "Reflect.deepClone");
        a.add("In a typical SPA + REST architecture, the frontend and backend communicate primarily via what?", C, "Easy", "HTTP requests with JSON bodies", "Direct database connections", "Filesystem sharing", "Native sockets only");
        a.add("Which JavaScript bundler is widely used by Create React App?", C, "Easy", "Webpack", "Vite", "Rollup", "Parcel");
        a.add("Which CSS preprocessor is most commonly associated with the .scss file extension?", C, "Easy", "Sass", "Less", "Stylus", "PostCSS");
        a.add("Which abbreviation refers to the in-memory tree representation of an HTML document?", C, "Easy", "DOM", "BOM", "VOM", "TOM");
        a.add("Which JavaScript object models the browser tab's window, including history and location?", C, "Easy", "window", "browser", "session", "tab");
        a.add("Which DOM API queries elements by a CSS selector and returns the first match?", C, "Easy", "document.querySelector", "document.queryFirst", "document.getBySelector", "document.findOne");
        a.add("Which DOM API queries all elements matching a CSS selector?", C, "Easy", "document.querySelectorAll", "document.queryAll", "document.getAllBySelector", "document.findAll");
        a.add("Which JavaScript event fires when the DOM is fully constructed?", C, "Easy", "DOMContentLoaded", "load", "ready", "init");
        a.add("Which JavaScript event fires when the page (and all assets) finishes loading?", C, "Easy", "load", "DOMContentLoaded", "complete", "ready");
        a.add("Which API in browsers schedules a function to run after a delay in milliseconds?", C, "Easy", "setTimeout", "setInterval", "delay", "later");
        a.add("Which API in browsers schedules a function to run repeatedly at an interval?", C, "Easy", "setInterval", "setTimeout", "every", "schedule");
        a.add("Which response header instructs browsers to download the body as a file?", C, "Easy", "Content-Disposition: attachment", "Download: true", "Disposition: file", "Save-As: file");
        a.add("Which standard browser API enables push notifications?", C, "Easy", "Push API (with Service Workers)", "alert API", "fetch API", "Storage API");
        a.add("Which standard browser API enables location access (with user consent)?", C, "Easy", "Geolocation API", "Map API", "Position API", "GPS API");

        // ===== Medium (50) =====
        a.add("Which HTTP method is sent by browsers as a CORS preflight?", C, "Medium", "OPTIONS", "GET", "HEAD", "POST");
        a.add("What conditions cause a CORS preflight to be sent (rather than a 'simple' request)?", C, "Medium", "Custom headers, non-simple methods, or non-standard content types", "Any GET request", "All POST requests", "Only requests larger than 1MB");
        a.add("Which three components define an 'origin' under the same-origin policy?", C, "Medium", "Scheme, host, and port", "Scheme, host only", "Host, port only", "Domain and TLD only");
        a.add("How many segments does a typical JWT (JWS Compact) consist of?", C, "Medium", "3 (header, payload, signature)", "2 (header, payload)", "4 (header, payload, signature, footer)", "1 (the signature)");
        a.add("Which character separates the segments of a JWT?", C, "Medium", "A dot (.)", "A slash (/)", "A pipe (|)", "A comma (,)");
        a.add("Which signing algorithm does the typical default JWT use (HMAC SHA-256)?", C, "Medium", "HS256", "RS256", "ES256", "PS256");
        a.add("Which JWT registered claim represents the token's expiration time?", C, "Medium", "exp", "iat", "nbf", "ttl");
        a.add("Which JWT registered claim represents the token's issuer?", C, "Medium", "iss", "sub", "aud", "jti");
        a.add("Which JWT registered claim represents the token's intended audience?", C, "Medium", "aud", "iss", "sub", "azp");
        a.add("How is an OAuth 2.0 access token most commonly carried in HTTP requests?", C, "Medium", "Authorization: Bearer <token>", "X-Access-Token: <token>", "Cookie: oauth=<token>", "Token: Bearer <token>");
        a.add("Which identity protocol is built on top of OAuth 2.0?", C, "Medium", "OpenID Connect", "SAML", "Kerberos", "LDAP");
        a.add("What does the abbreviation SAML stand for?", C, "Medium", "Security Assertion Markup Language", "Single Authentication Markup Language", "Secure Application Messaging Layer", "Standard Auth Markup Language");
        a.add("What does the abbreviation CSRF stand for in web security?", C, "Medium", "Cross-Site Request Forgery", "Common Server Request Filter", "Centralized Service Resource Federation", "Cross-Site Reference Forwarding");
        a.add("Which technique is most commonly used to defend against CSRF attacks?", C, "Medium", "Synchronizer (CSRF) tokens, often paired with SameSite cookies", "Disabling JavaScript", "Hashing passwords", "Whitelisting IP addresses only");
        a.add("What does the abbreviation XSS stand for?", C, "Medium", "Cross-Site Scripting", "Extensible Server Scripting", "X-Site Subscription", "Cross-Service Sockets");
        a.add("What is the most reliable defense against SQL injection attacks?", C, "Medium", "Use parameterized queries / prepared statements", "Disable user input", "Filter requests by IP", "Use HTTPS");
        a.add("Which header is used to declare a Content Security Policy?", C, "Medium", "Content-Security-Policy", "X-CSP", "Security-Policy", "CSP-Header");
        a.add("Which standard mechanism ensures the integrity of fetched resources via cryptographic hashes?", C, "Medium", "Subresource Integrity (SRI)", "Strict Transport Security (HSTS)", "Cross-Origin Resource Sharing (CORS)", "Site Isolation");
        a.add("Which protocol underlies HTTPS and provides the secure channel?", C, "Medium", "TLS", "DTLS only", "SSH", "IPSec");
        a.add("Which entity issues digital certificates trusted by browsers?", C, "Medium", "Certificate Authorities (CAs)", "Internet Service Providers", "Operating Systems only", "ICANN");
        a.add("Why does a self-signed certificate trigger browser warnings?", C, "Medium", "It is not signed by a trusted Certificate Authority", "It uses old encryption only", "It cannot be parsed", "It always lacks a private key");
        a.add("Which acronym describes mutual TLS authentication, where both client and server present certificates?", C, "Medium", "mTLS", "TLS-A", "TLS-X", "DTLS");
        a.add("In modern Chromium browsers, what is the typical default value for the SameSite cookie attribute?", C, "Medium", "Lax", "Strict", "None", "Cross-site");
        a.add("With SameSite=Strict, when is the cookie sent?", C, "Medium", "Only when the request originates from the same site", "On every request including cross-site", "Never", "Only on form submissions");
        a.add("If you set SameSite=None on a cookie, what other attribute is required by browsers?", C, "Medium", "Secure", "HttpOnly", "Domain", "Max-Age");
        a.add("To prevent JavaScript from reading a session cookie, which cookie attribute should be set?", C, "Medium", "HttpOnly", "Secure", "Strict", "NoScript");
        a.add("To ensure a cookie is only sent over HTTPS, which attribute should be set?", C, "Medium", "Secure", "HttpOnly", "TLS-Only", "Encrypted");
        a.add("In a typical OAuth 2.0 flow, refresh tokens compared to access tokens are usually...", C, "Medium", "Longer-lived and used to obtain new access tokens", "Shorter-lived than access tokens", "Identical to access tokens", "Stored only on the resource server");
        a.add("Which non-profit organization publishes the famous 'Top 10 Web Application Security Risks'?", C, "Medium", "OWASP", "ISO", "W3C", "IETF");
        a.add("Which two web servers are very widely used in production deployments?", C, "Medium", "Nginx and Apache HTTPD", "IIS only", "Tomcat and Caddy only", "Lighttpd and h2o only");
        a.add("What is the primary role of a reverse proxy in a typical web stack?", C, "Medium", "Terminate TLS, route requests, and load balance to backends", "Open outbound internet for clients", "Resolve DNS records for the LAN", "Cache database queries");
        a.add("Which strategy keeps subsequent requests from a client routed to the same backend in a load-balanced cluster?", C, "Medium", "Sticky sessions (session affinity)", "Round-robin only", "Weighted random only", "Connection draining");
        a.add("Why is database connection pooling used in backends?", C, "Medium", "To reuse expensive connections and improve throughput/latency", "To encrypt the connection", "To partition large tables", "To replicate data");
        a.add("Which two in-memory data stores are often used as caching layers in modern web stacks?", C, "Medium", "Redis and Memcached", "MongoDB and PostgreSQL", "MySQL and SQLite", "Hadoop and Spark");
        a.add("Which compression algorithm is widely used in HTTP responses today and is generally newer/more efficient than gzip?", C, "Medium", "Brotli", "Zopfli only", "Snappy", "Bzip2");
        a.add("Which browser feature allows web apps to work offline and to control caching of network requests?", C, "Medium", "Service Workers", "Web Workers", "Shared Workers", "Push Workers");
        a.add("What is the term for a web application that behaves like a native installable app, often using Service Workers?", C, "Medium", "Progressive Web App (PWA)", "Hybrid App", "Single Page App (SPA)", "Web Component App");
        a.add("Which browser API enables peer-to-peer real-time audio/video/data communication?", C, "Medium", "WebRTC", "WebSocket", "Web Audio", "Web Push");
        a.add("Which Java Spring annotation typically marks a method as handling WebSocket messages over STOMP?", C, "Medium", "@MessageMapping", "@WebSocketHandler", "@StompMapping", "@SocketEvent");
        a.add("Which approach lets web apps make cross-origin AJAX requests with cookies attached?", C, "Medium", "Set credentials: 'include' on fetch and Access-Control-Allow-Credentials: true on the server", "Set Origin: * on the server", "Disable HTTPS", "Use only same-origin endpoints");
        a.add("Which JavaScript syntax fetches JSON, awaiting both the response and the body parsing?", C, "Medium", "const r = await fetch(url); const data = await r.json();", "const data = fetch(url).body;", "const data = JSON.fetch(url);", "fetch(url, json => data);");
        a.add("Which CORS request header lists the headers a non-simple request will use?", C, "Medium", "Access-Control-Request-Headers", "Origin-Headers", "Cors-Headers", "Allow-Headers");
        a.add("Which CORS response header lists which response headers the browser may expose to scripts?", C, "Medium", "Access-Control-Expose-Headers", "Allow-Read-Headers", "Cors-Expose-Headers", "X-Expose-Headers");
        a.add("In a typical browser/storage decision, where should you NOT store sensitive tokens that must be unreadable to JS?", C, "Medium", "localStorage / sessionStorage", "An HttpOnly Secure cookie", "A backend-controlled session", "An OS keychain accessed via native bridge");
        a.add("Which HTTP header instructs intermediaries (and the browser) on caching directives like max-age?", C, "Medium", "Cache-Control", "ETag", "Vary", "Pragma");
        a.add("In SSL/TLS, what does PKI stand for?", C, "Medium", "Public Key Infrastructure", "Private Key Initiator", "Protected Key Interface", "Public Key Interceptor");
        a.add("Which attribute on a cookie restricts its visibility to a specific URL prefix?", C, "Medium", "Path", "Domain", "Scope", "Realm");
        a.add("Which attribute on a cookie restricts its visibility to a specific host (and optionally subdomains)?", C, "Medium", "Domain", "Path", "Host-Only", "Origin");
        a.add("Which standard format do many backends use for time fields in JSON responses?", C, "Medium", "ISO 8601 (e.g., 2024-09-12T13:45:00Z)", "Unix epoch with milliseconds only", "RFC 822 only", "Localized strings only");
        a.add("Which JavaScript API is the most modern way to abort a fetch in flight?", C, "Medium", "AbortController", "Promise.cancel", "fetch.cancel", "XMLHttpRequest.abort only");

        // ===== Hard (50) =====
        a.add("In a JWS (JSON Web Signature) compact JWT, what exactly is signed?", C, "Hard", "base64url(header) + '.' + base64url(payload), using the chosen algorithm", "Just the payload, signed in plain text", "Just the header", "The entire concatenated cookie");
        a.add("In the JOSE family of standards, what does JWS stand for?", C, "Hard", "JSON Web Signature", "JSON Web Service", "JSON Web Schema", "JSON Web Session");
        a.add("In the JOSE family of standards, what does JWE stand for?", C, "Hard", "JSON Web Encryption", "JSON Web Endpoint", "JSON Web Exchange", "JSON Web Envelope");
        a.add("In the JOSE family of standards, what does JWK stand for?", C, "Hard", "JSON Web Key", "JSON Web Kerberos", "JSON Web Kit", "JSON Web Keystore");
        a.add("Why is the JWT 'alg: none' header value considered insecure?", C, "Hard", "It indicates an unsigned token; servers must reject this in production", "It enables stronger encryption only", "It restricts token to admins", "It is reserved for refresh tokens only");
        a.add("Which encoding does JWT use for its segments to be URL-safe?", C, "Hard", "Base64URL", "Base64 (standard)", "Hex", "Punycode");
        a.add("Which OAuth 2.0 endpoint is used by clients to exchange grants/refresh tokens for access tokens?", C, "Hard", "/token (the token endpoint)", "/authorize (the authorization endpoint)", "/userinfo", "/revoke");
        a.add("Which OAuth 2.0 endpoint redirects the user-agent and (when applicable) prompts for consent?", C, "Hard", "/authorize (the authorization endpoint)", "/token", "/introspect", "/jwks");
        a.add("Which RFC defines OAuth 2.0 token introspection (RFC 7662)?", C, "Hard", "RFC 7662", "RFC 6749", "RFC 8252", "RFC 7519");
        a.add("Which OAuth 2.0 grant is intended for input-constrained devices like smart TVs and IoT?", C, "Hard", "Device Authorization Grant", "Implicit Grant", "Client Credentials", "Resource Owner Password");
        a.add("Why should refresh tokens be rotated and revocable?", C, "Hard", "To minimize the impact of leaked refresh tokens", "To reduce database storage", "To make CSRF easier", "To force HTTPS");
        a.add("In OpenID Connect, the 'ID Token' is delivered in what format?", C, "Hard", "A signed JWT", "An encrypted SAML assertion", "An opaque session cookie", "A binary protobuf");
        a.add("Which OpenID Connect endpoint returns the authenticated user's claims?", C, "Hard", "/userinfo", "/openid", "/profile", "/identity");
        a.add("Which browser API allows two cross-origin frames to communicate by passing messages?", C, "Hard", "window.postMessage", "frame.send", "frame.notify", "BroadcastChannel only");
        a.add("Which Apple browser feature aggressively limits third-party tracking cookies?", C, "Hard", "Intelligent Tracking Prevention (ITP)", "Privacy Mode", "Cookie Sandbox", "Tracker Blocker");
        a.add("Which CSP directive lets you nominate a per-request 'nonce' for trusted inline scripts?", C, "Hard", "script-src 'nonce-...'", "trusted-inline 'allow'", "inline-script-policy", "default-src 'self-inline'");
        a.add("Which CSP directive endpoint receives violation reports?", C, "Hard", "report-uri (or report-to)", "csp-report", "violation-uri", "report-back");
        a.add("Which preload list, maintained by browser vendors, ships HTTPS-only enforcement for many domains?", C, "Hard", "The HSTS preload list", "The CSP preload list", "The CORS preload list", "The CDN preload list");
        a.add("With SameSite=Lax, what happens to top-level cross-site POST navigations?", C, "Hard", "The cookie is NOT sent (only safe top-level GETs send Lax cookies)", "The cookie is sent on all top-level navigations", "The cookie is sent only on iframes", "The cookie is sent only on XHR");
        a.add("Which cryptographic hash algorithms are commonly used for Subresource Integrity (SRI)?", C, "Hard", "SHA-256, SHA-384, and SHA-512", "MD5 only", "SHA-1 only", "BLAKE2 and SHA-3 only");
        a.add("Which header lets a site control browser features per-origin (e.g., camera, geolocation)?", C, "Hard", "Permissions-Policy", "Feature-Allow", "X-Permissions", "Capability-Policy");
        a.add("Which header restricts what the browser includes in the Referer header on outgoing requests?", C, "Hard", "Referrer-Policy", "Referer-Control", "Origin-Policy", "Privacy-Policy");
        a.add("Which header lets a resource declare which origins may include it as a sub-resource?", C, "Hard", "Cross-Origin-Resource-Policy (CORP)", "Resource-Origin-Policy", "Allow-Resource-Origin", "Cors-Resource-Policy");
        a.add("Which two headers must be set for cross-origin isolation to enable SharedArrayBuffer?", C, "Hard", "Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy", "X-Frame-Options and X-Content-Type-Options", "CSP and HSTS", "CORS and CORP only");
        a.add("Which CSP directive replaces X-Frame-Options for controlling who can frame the page?", C, "Hard", "frame-ancestors", "frame-policy", "embedder-policy", "frame-options");
        a.add("Which form 'enctype' is required to upload files via an HTML form?", C, "Hard", "multipart/form-data", "application/x-www-form-urlencoded", "application/json", "text/plain");
        a.add("Which Fetch API option must you set to send cookies on cross-origin requests?", C, "Hard", "credentials: 'include'", "credentials: 'same-origin' (default)", "withCredentials: true", "cookies: 'all'");
        a.add("By default, a Service Worker registered at /sw.js controls which scope?", C, "Hard", "The directory containing the SW file (and below)", "The whole origin always", "Only its own URL", "Only sub-paths of /service/");
        a.add("Which JSON-based file describes a Progressive Web App's metadata (icons, name, etc.)?", C, "Hard", "Web App Manifest (manifest.json or .webmanifest)", "package.json", "robots.txt", "sitemap.xml");
        a.add("Compared to TLS 1.2, TLS 1.3 typically requires how many round trips for the handshake?", C, "Hard", "1-RTT (and 0-RTT for resumption)", "2-RTT (always)", "3-RTT", "0-RTT only (always)");
        a.add("Which HTTP method is used by browsers to ask a proxy to tunnel HTTPS traffic?", C, "Hard", "CONNECT", "TRACE", "OPTIONS", "TUNNEL");
        a.add("During the TLS handshake, which extension lets the client select a higher-layer protocol like HTTP/2?", C, "Hard", "ALPN (Application-Layer Protocol Negotiation)", "SNI", "ECH", "OCSP");
        a.add("In TLS, which extension carries the server hostname so a single IP can host many certificates?", C, "Hard", "SNI (Server Name Indication)", "ALPN", "ECH", "OCSP");
        a.add("Which proposed TLS extension encrypts the SNI hostname in the ClientHello?", C, "Hard", "ECH (Encrypted Client Hello)", "ESNI v1 only (deprecated)", "OCSP Stapling", "PSK Resumption");
        a.add("In a typical mutual-TLS deployment, when does the client send its certificate?", C, "Hard", "During the TLS handshake (after the server's CertificateRequest)", "In a separate HTTP header after the connection", "Out of band over a different protocol", "Only during HTTP/2 stream creation");
        a.add("What is a 'webhook' in the context of integrations?", C, "Hard", "An HTTP callback delivered from one service to another when an event occurs", "A bidirectional WebSocket message", "A polling endpoint that the client must call", "A scheduled cron task");
        a.add("Which technique is the standard way to verify a webhook's authenticity at the receiver?", C, "Hard", "Verify a signature header (e.g., HMAC) computed with a shared secret", "Check the source IP only", "Trust the sender's claim of identity", "Whitelist by user-agent only");
        a.add("Which endpoint convention is most common for a GraphQL HTTP API?", C, "Hard", "A single endpoint such as /graphql for all queries and mutations", "One endpoint per type", "One endpoint per operation", "One endpoint per HTTP method");
        a.add("Which technique is used to issue short-lived signed URLs for accessing private cloud-storage objects?", C, "Hard", "Pre-signed URLs (e.g., S3 pre-signed URLs)", "JWT in the path", "Basic auth via URL", "TLS client certificates");
        a.add("To safely propagate distributed traces across services, which standard headers are commonly used today?", C, "Hard", "W3C traceparent and tracestate", "X-Request-ID only", "X-B3-TraceId only (legacy)", "X-Correlation-Id only");
        a.add("Which observability discipline focuses on three main signals: metrics, logs, and traces?", C, "Hard", "Observability", "Monitoring only", "Profiling only", "Auditing only");
        a.add("In an event-driven backend, which broker is widely used for high-throughput, distributed log streams?", C, "Hard", "Apache Kafka", "Apache Tomcat", "Nginx", "Apache Maven");
        a.add("Which API style serves HTTP requests by streaming partial JSON via Server-Sent Events for chatbots?", C, "Hard", "SSE-based streaming over HTTP", "WebSocket only", "gRPC server streaming only", "FTP streaming");
        a.add("Which header pattern lets browsers split-rejoin a large GET response across multiple chunks?", C, "Hard", "Transfer-Encoding: chunked", "Content-Length: 0", "Connection: keep-alive only", "Content-Range: bytes only");
        a.add("Which mechanism allows a server to push small notifications to a Service Worker, even when the page is closed?", C, "Hard", "Web Push (with VAPID keys)", "Server-Sent Events", "WebSocket only", "Long polling only");
        a.add("Which security header restricts how the browser may infer the request's intended audience (Sec-Fetch-Dest)?", C, "Hard", "Sec-Fetch-Dest", "Origin", "Sec-Fetch-User", "Sec-Dest");
        a.add("Which header tells fetchers whether the destination is 'cors', 'no-cors', or 'same-origin'?", C, "Hard", "Sec-Fetch-Mode", "Sec-Fetch-Type", "Origin-Mode", "Cors-Mode");
        a.add("Which 'Permissions-Policy' directive controls browser geolocation access?", C, "Hard", "geolocation=()", "location=()", "geo-pos=()", "position=()");
        a.add("In modern browser cookie partitioning (CHIPS), which attribute opts a cookie into per-top-level-site partitioning?", C, "Hard", "Partitioned", "Partition", "PartitionKey", "TopSite");
        a.add("Which Content Security Policy 'sandbox' directive lets you restrict a page's capabilities?", C, "Hard", "sandbox", "isolate", "restrict", "embed-sandbox");
    }
}
