package com.quiz.config.seeds;

public final class GeneralKnowledgeSeeder {
    private static final String C = "General Knowledge";
    private GeneralKnowledgeSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("What is the capital of England?", C, "Easy", "London", "Manchester", "Liverpool", "Birmingham");
        a.add("How many days are there in a week?", C, "Easy", "7", "5", "6", "8");
        a.add("What color is the sky on a clear day?", C, "Easy", "Blue", "Green", "Red", "Yellow");
        a.add("How many sides does a triangle have?", C, "Easy", "3", "4", "2", "5");
        a.add("How many wheels does a typical car have?", C, "Easy", "4", "2", "3", "6");
        a.add("Which animal is known as the king of the jungle?", C, "Easy", "Lion", "Tiger", "Elephant", "Bear");
        a.add("What is the largest mammal on Earth?", C, "Easy", "Blue Whale", "Elephant", "Giraffe", "Hippopotamus");
        a.add("On which continent is Egypt located?", C, "Easy", "Africa", "Asia", "Europe", "South America");
        a.add("What is the official currency of the United States?", C, "Easy", "US Dollar", "Pound", "Euro", "Yen");
        a.add("What is the official currency of Japan?", C, "Easy", "Yen", "Won", "Yuan", "Ringgit");
        a.add("What is the official currency of the United Kingdom?", C, "Easy", "Pound Sterling", "Euro", "US Dollar", "Krone");
        a.add("How many colors are commonly recognized in a rainbow?", C, "Easy", "7", "5", "6", "8");
        a.add("Which language is most commonly spoken in Brazil?", C, "Easy", "Portuguese", "Spanish", "English", "French");
        a.add("Who is the famous author of the Harry Potter book series?", C, "Easy", "J.K. Rowling", "Roald Dahl", "Stephen King", "C.S. Lewis");
        a.add("What two-dimensional shape is perfectly round?", C, "Easy", "Circle", "Square", "Triangle", "Rectangle");
        a.add("At what temperature does pure water freeze in Celsius?", C, "Easy", "0", "32", "10", "-10");
        a.add("At what temperature does pure water boil in Celsius at sea level?", C, "Easy", "100", "90", "120", "80");
        a.add("How many months are there in a year?", C, "Easy", "12", "10", "11", "13");
        a.add("Which travels faster: light or sound?", C, "Easy", "Light", "Sound", "They travel the same", "Neither has speed");
        a.add("What sound does a cow typically make?", C, "Easy", "Moo", "Bark", "Meow", "Quack");
        a.add("How many seconds are in a minute?", C, "Easy", "60", "30", "100", "120");
        a.add("How many minutes are in an hour?", C, "Easy", "60", "30", "100", "120");
        a.add("What is the natural color of grass?", C, "Easy", "Green", "Brown", "Blue", "Yellow");
        a.add("Which bird is famously unable to fly and lives in cold climates?", C, "Easy", "Penguin", "Eagle", "Sparrow", "Parrot");
        a.add("Which country has the largest area in the world?", C, "Easy", "Russia", "Canada", "China", "United States");
        a.add("What is the official currency of India?", C, "Easy", "Rupee", "Taka", "Dirham", "Riyal");
        a.add("What is the capital of Italy?", C, "Easy", "Rome", "Milan", "Naples", "Turin");
        a.add("What is the capital of Germany?", C, "Easy", "Berlin", "Munich", "Hamburg", "Frankfurt");
        a.add("What is the capital of Spain?", C, "Easy", "Madrid", "Barcelona", "Seville", "Valencia");
        a.add("What is the capital of Russia?", C, "Easy", "Moscow", "Saint Petersburg", "Kiev", "Minsk");
        a.add("What is the capital of China?", C, "Easy", "Beijing", "Shanghai", "Hong Kong", "Guangzhou");
        a.add("What is the capital of Japan?", C, "Easy", "Tokyo", "Kyoto", "Osaka", "Sapporo");
        a.add("What is the capital of Canada?", C, "Easy", "Ottawa", "Toronto", "Vancouver", "Montreal");
        a.add("What is the capital city of the United States?", C, "Easy", "Washington, D.C.", "New York", "Los Angeles", "Boston");
        a.add("What is the capital of Egypt?", C, "Easy", "Cairo", "Alexandria", "Giza", "Luxor");
        a.add("Which planet is closest to the Sun?", C, "Easy", "Mercury", "Venus", "Earth", "Mars");
        a.add("How many legs does a typical spider have?", C, "Easy", "8", "6", "10", "4");
        a.add("How many legs does a typical insect have?", C, "Easy", "6", "8", "4", "10");
        a.add("Which long curved yellow fruit is a popular breakfast food?", C, "Easy", "Banana", "Apple", "Pear", "Mango");
        a.add("Which ocean lies on the east coast of the United States?", C, "Easy", "Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean");
        a.add("Which animal has a long trunk?", C, "Easy", "Elephant", "Giraffe", "Hippopotamus", "Rhinoceros");
        a.add("Which is the tallest land animal on Earth?", C, "Easy", "Giraffe", "Elephant", "Camel", "Horse");
        a.add("Which is the fastest land animal?", C, "Easy", "Cheetah", "Lion", "Horse", "Greyhound");
        a.add("Which is the largest living bird?", C, "Easy", "Ostrich", "Eagle", "Albatross", "Emu");
        a.add("Which is the largest land animal alive today?", C, "Easy", "African Elephant", "White Rhinoceros", "Hippopotamus", "Giraffe");
        a.add("Which big fruit is mostly water and has a green rind with red flesh?", C, "Easy", "Watermelon", "Pumpkin", "Honeydew", "Cantaloupe");
        a.add("Which planet is famously known as the Red Planet?", C, "Easy", "Mars", "Venus", "Saturn", "Mercury");
        a.add("Which animal is the symbol of the World Wildlife Fund (WWF)?", C, "Easy", "Giant Panda", "Tiger", "Polar Bear", "Elephant");
        a.add("How many letters are there in the English alphabet?", C, "Easy", "26", "24", "25", "27");
        a.add("Which sense organ do humans use to see?", C, "Easy", "Eyes", "Ears", "Nose", "Skin");

        // ===== Medium (50) =====
        a.add("Who is widely credited with inventing the telephone?", C, "Medium", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi");
        a.add("Who wrote the political allegory 'Animal Farm'?", C, "Medium", "George Orwell", "Aldous Huxley", "Ray Bradbury", "John Steinbeck");
        a.add("Which element has atomic number 1?", C, "Medium", "Hydrogen", "Helium", "Lithium", "Oxygen");
        a.add("In which year did humans first land on the Moon?", C, "Medium", "1969", "1965", "1972", "1959");
        a.add("Who was the first person to walk on the Moon?", C, "Medium", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins");
        a.add("What is the official currency of Switzerland?", C, "Medium", "Swiss Franc", "Euro", "Krone", "Pound");
        a.add("Which flower is the unofficial national flower of Japan?", C, "Medium", "Cherry Blossom", "Lotus", "Tulip", "Orchid");
        a.add("Who painted 'The Starry Night'?", C, "Medium", "Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Salvador Dali");
        a.add("What is the highest mountain on Earth above sea level?", C, "Medium", "Mount Everest", "K2", "Kangchenjunga", "Lhotse");
        a.add("Who is famously credited with inventing the practical incandescent light bulb?", C, "Medium", "Thomas Edison", "Nikola Tesla", "James Watt", "Benjamin Franklin");
        a.add("What is the official currency of South Africa?", C, "Medium", "Rand", "Dollar", "Shilling", "Naira");
        a.add("Which country is shaped like a boot in Europe?", C, "Medium", "Italy", "Spain", "Greece", "Portugal");
        a.add("What is the capital of Norway?", C, "Medium", "Oslo", "Bergen", "Stavanger", "Trondheim");
        a.add("What is the capital of Sweden?", C, "Medium", "Stockholm", "Gothenburg", "Malmo", "Uppsala");
        a.add("What is the capital of Finland?", C, "Medium", "Helsinki", "Tampere", "Turku", "Espoo");
        a.add("What is the capital of Denmark?", C, "Medium", "Copenhagen", "Aarhus", "Odense", "Aalborg");
        a.add("What is the capital of Poland?", C, "Medium", "Warsaw", "Krakow", "Gdansk", "Lodz");
        a.add("What is the capital of Greece?", C, "Medium", "Athens", "Thessaloniki", "Sparta", "Patras");
        a.add("What is the capital of Portugal?", C, "Medium", "Lisbon", "Porto", "Coimbra", "Faro");
        a.add("What is the capital of Belgium?", C, "Medium", "Brussels", "Antwerp", "Bruges", "Ghent");
        a.add("What is the capital of the Netherlands?", C, "Medium", "Amsterdam", "Rotterdam", "The Hague", "Utrecht");
        a.add("What is the capital of Austria?", C, "Medium", "Vienna", "Salzburg", "Graz", "Linz");
        a.add("What is the capital of Switzerland?", C, "Medium", "Bern", "Zurich", "Geneva", "Basel");
        a.add("What is the capital of Ireland?", C, "Medium", "Dublin", "Cork", "Galway", "Limerick");
        a.add("What is the capital of Iceland?", C, "Medium", "Reykjavik", "Akureyri", "Hafnarfjordur", "Kopavogur");
        a.add("What is the capital of the Czech Republic?", C, "Medium", "Prague", "Brno", "Ostrava", "Plzen");
        a.add("What is the capital of Hungary?", C, "Medium", "Budapest", "Debrecen", "Szeged", "Pecs");
        a.add("Who wrote the novel 'The Great Gatsby'?", C, "Medium", "F. Scott Fitzgerald", "Ernest Hemingway", "John Steinbeck", "William Faulkner");
        a.add("Which country's flag features a single red maple leaf?", C, "Medium", "Canada", "Lebanon", "Switzerland", "Denmark");
        a.add("Which two brothers are credited with inventing the first powered airplane?", C, "Medium", "Wright Brothers", "Lumiere Brothers", "Mayo Brothers", "Marx Brothers");
        a.add("What is the official currency of Mexico?", C, "Medium", "Peso", "Real", "Bolivar", "Sol");
        a.add("What is the national anthem of the United States called?", C, "Medium", "The Star-Spangled Banner", "America the Beautiful", "God Bless America", "My Country, Tis of Thee");
        a.add("How many of the Great Lakes are there in North America?", C, "Medium", "5", "4", "6", "3");
        a.add("In which year did the First World War begin?", C, "Medium", "1914", "1916", "1918", "1912");
        a.add("In which year did the First World War end?", C, "Medium", "1918", "1919", "1917", "1920");
        a.add("Who is regarded as the founder of Buddhism?", C, "Medium", "Siddhartha Gautama", "Confucius", "Lao Tzu", "Mahavira");
        a.add("Which is the largest internal organ of the human body?", C, "Medium", "Liver", "Lung", "Kidney", "Stomach");
        a.add("Which natural substance is the hardest known on Earth?", C, "Medium", "Diamond", "Granite", "Quartz", "Steel");
        a.add("Which is the largest country in South America by area?", C, "Medium", "Brazil", "Argentina", "Peru", "Colombia");
        a.add("What is the capital of Turkey?", C, "Medium", "Ankara", "Istanbul", "Izmir", "Bursa");
        a.add("What is the capital of Brazil?", C, "Medium", "Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador");
        a.add("Who painted 'The Last Supper'?", C, "Medium", "Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello");
        a.add("The Statue of Liberty was a gift to the United States from which country?", C, "Medium", "France", "England", "Italy", "Spain");
        a.add("Which mountain range contains Mount Everest?", C, "Medium", "Himalayas", "Andes", "Rockies", "Alps");
        a.add("Which fruit is traditionally associated with the city of Newton, Massachusetts and gravity discovery?", C, "Medium", "Apple", "Pear", "Plum", "Quince");
        a.add("In Greek mythology, who is the king of the gods?", C, "Medium", "Zeus", "Poseidon", "Apollo", "Hades");
        a.add("Which planet has the most moons in our solar system (per recent counts)?", C, "Medium", "Saturn", "Jupiter", "Uranus", "Neptune");
        a.add("Which country gifted bonsai cultivation to the wider world?", C, "Medium", "Japan", "China", "Korea", "Vietnam");
        a.add("Which sport is associated with Wimbledon?", C, "Medium", "Tennis", "Cricket", "Rugby", "Golf");
        a.add("What is measured using a Richter scale?", C, "Medium", "Earthquake magnitude", "Wind speed", "Sound intensity", "Air pressure");

        // ===== Hard (50) =====
        a.add("What is the official currency of Bhutan?", C, "Hard", "Ngultrum", "Rupee", "Kyat", "Riel");
        a.add("What is the world's tallest uninterrupted waterfall?", C, "Hard", "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguazu Falls");
        a.add("What is the smallest bone in the human body?", C, "Hard", "Stapes", "Femur", "Mandible", "Ulna");
        a.add("Who was the first woman to win a Nobel Prize?", C, "Hard", "Marie Curie", "Mother Teresa", "Rosalind Franklin", "Ada Lovelace");
        a.add("What is the official currency of Thailand?", C, "Hard", "Baht", "Ringgit", "Dong", "Kip");
        a.add("Which modern country was historically known as Persia?", C, "Hard", "Iran", "Iraq", "Turkey", "Syria");
        a.add("Who wrote the novel 'Brave New World'?", C, "Hard", "Aldous Huxley", "George Orwell", "H.G. Wells", "Anthony Burgess");
        a.add("What is the official currency of Indonesia?", C, "Hard", "Rupiah", "Peso", "Ringgit", "Baht");
        a.add("What is the capital of Mongolia?", C, "Hard", "Ulaanbaatar", "Bishkek", "Astana", "Tashkent");
        a.add("What is the official currency of Israel?", C, "Hard", "Shekel", "Lira", "Dinar", "Riyal");
        a.add("Which country is reported to hold the largest proven oil reserves in the world?", C, "Hard", "Venezuela", "Saudi Arabia", "Iran", "Iraq");
        a.add("Which is the smallest planet in our solar system?", C, "Hard", "Mercury", "Mars", "Pluto", "Venus");
        a.add("Who is widely credited with inventing dynamite?", C, "Hard", "Alfred Nobel", "Thomas Edison", "Nikola Tesla", "James Watt");
        a.add("Which African country has more pyramids than Egypt?", C, "Hard", "Sudan", "Ethiopia", "Libya", "Algeria");
        a.add("What is the official currency of Vietnam?", C, "Hard", "Dong", "Kip", "Baht", "Riel");
        a.add("In which year was the Eiffel Tower completed?", C, "Hard", "1889", "1879", "1900", "1869");
        a.add("Who wrote the novel 'Don Quixote'?", C, "Hard", "Miguel de Cervantes", "Lope de Vega", "Federico Garcia Lorca", "Gabriel Garcia Marquez");
        a.add("Which is the most populous landlocked country in the world?", C, "Hard", "Ethiopia", "Uganda", "Kazakhstan", "Afghanistan");
        a.add("Which country spans the largest number of time zones (including overseas territories)?", C, "Hard", "France", "Russia", "United States", "United Kingdom");
        a.add("What is the capital of Bhutan?", C, "Hard", "Thimphu", "Kathmandu", "Paro", "Dhaka");
        a.add("What is the official currency of South Korea?", C, "Hard", "Won", "Yen", "Yuan", "Ringgit");
        a.add("What is the official currency of Brazil?", C, "Hard", "Real", "Peso", "Bolivar", "Cruzeiro");
        a.add("What is the largest island in the world (by land area)?", C, "Hard", "Greenland", "New Guinea", "Borneo", "Madagascar");
        a.add("Which river flows through the city of Paris?", C, "Hard", "Seine", "Rhone", "Loire", "Garonne");
        a.add("Who is traditionally credited with composing 'The Iliad'?", C, "Hard", "Homer", "Hesiod", "Sophocles", "Euripides");
        a.add("Which flower is widely considered the national flower of England?", C, "Hard", "Rose", "Daffodil", "Thistle", "Shamrock");
        a.add("Which flower is the national flower of India?", C, "Hard", "Lotus", "Marigold", "Jasmine", "Rose");
        a.add("What is the capital of Madagascar?", C, "Hard", "Antananarivo", "Maputo", "Nairobi", "Lusaka");
        a.add("What is the capital of Lebanon?", C, "Hard", "Beirut", "Damascus", "Amman", "Tripoli");
        a.add("What is the capital of Cuba?", C, "Hard", "Havana", "Santiago de Cuba", "Camaguey", "Holguin");
        a.add("What is the capital of Venezuela?", C, "Hard", "Caracas", "Maracaibo", "Valencia", "Bogota");
        a.add("What is the official currency of Russia?", C, "Hard", "Ruble", "Hryvnia", "Tenge", "Lari");
        a.add("What is the official currency of Saudi Arabia?", C, "Hard", "Riyal", "Dinar", "Dirham", "Pound");
        a.add("In which year was the Berlin Wall first erected?", C, "Hard", "1961", "1949", "1972", "1955");
        a.add("Around which year did Johannes Gutenberg invent the European printing press?", C, "Hard", "1440", "1500", "1620", "1390");
        a.add("Who invented the World Wide Web in 1989?", C, "Hard", "Tim Berners-Lee", "Vint Cerf", "Bob Kahn", "Linus Torvalds");
        a.add("In which year did the French Revolution begin?", C, "Hard", "1789", "1776", "1804", "1815");
        a.add("In which year was the Magna Carta sealed by King John of England?", C, "Hard", "1215", "1066", "1314", "1485");
        a.add("In which year did the Battle of Hastings take place?", C, "Hard", "1066", "1215", "1485", "1314");
        a.add("Which Roman emperor ordered the building of a famous wall in northern Britain?", C, "Hard", "Hadrian", "Augustus", "Nero", "Trajan");
        a.add("Who became the first emperor to unify ancient China?", C, "Hard", "Qin Shi Huang", "Han Wudi", "Tang Taizong", "Kublai Khan");
        a.add("Who wrote the play 'Faust'?", C, "Hard", "Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Thomas Mann");
        a.add("Which country reportedly holds the world's largest official gold reserves?", C, "Hard", "United States", "Germany", "Italy", "France");
        a.add("Who wrote the novel 'Les Miserables'?", C, "Hard", "Victor Hugo", "Alexandre Dumas", "Emile Zola", "Honore de Balzac");
        a.add("Who painted the famous anti-war mural 'Guernica'?", C, "Hard", "Pablo Picasso", "Salvador Dali", "Joan Miro", "Diego Rivera");
        a.add("Which Renaissance artist sculpted the marble statue 'David'?", C, "Hard", "Michelangelo", "Donatello", "Bernini", "Cellini");
        a.add("Which country produces the most coffee in the world?", C, "Hard", "Brazil", "Vietnam", "Colombia", "Ethiopia");
        a.add("What is the official currency of Iran?", C, "Hard", "Rial", "Lira", "Dinar", "Manat");
        a.add("What is the official currency of Argentina?", C, "Hard", "Peso", "Real", "Bolivar", "Sol");
        a.add("Which scientist proposed the heliocentric model of the solar system in his 1543 book?", C, "Hard", "Nicolaus Copernicus", "Galileo Galilei", "Johannes Kepler", "Tycho Brahe");
    }
}
