package com.quiz.config.seeds;

public final class GeographySeeder {
    private static final String C = "Geography";
    private GeographySeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("On which continent is Brazil located?", C, "Easy", "South America", "North America", "Africa", "Europe");
        a.add("In which country is Mount Fuji located?", C, "Easy", "Japan", "China", "South Korea", "Vietnam");
        a.add("The Great Barrier Reef lies off the coast of which country?", C, "Easy", "Australia", "Indonesia", "Philippines", "New Zealand");
        a.add("On which continent is Kenya located?", C, "Easy", "Africa", "Asia", "Europe", "South America");
        a.add("On which continent is Mongolia located?", C, "Easy", "Asia", "Europe", "Africa", "Oceania");
        a.add("The Amazon rainforest is mostly located in which country?", C, "Easy", "Brazil", "Peru", "Colombia", "Venezuela");
        a.add("Which continent has the most countries?", C, "Easy", "Africa", "Asia", "Europe", "South America");
        a.add("On which continent is the Sahara desert located?", C, "Easy", "Africa", "Asia", "South America", "Australia");
        a.add("Which large North American country has both Atlantic and Pacific coastlines?", C, "Easy", "United States", "Mexico only", "Cuba", "Honduras");
        a.add("In which country is the Eiffel Tower located?", C, "Easy", "France", "Italy", "Belgium", "Spain");
        a.add("The Acropolis is a famous ancient citadel in which country?", C, "Easy", "Greece", "Italy", "Turkey", "Egypt");
        a.add("Stonehenge is a prehistoric monument located in which country?", C, "Easy", "England", "Scotland", "Ireland", "Wales");
        a.add("In which country is the famous archaeological site of Petra located?", C, "Easy", "Jordan", "Egypt", "Iraq", "Syria");
        a.add("Pizza is a dish that originated in which country?", C, "Easy", "Italy", "France", "Greece", "Spain");
        a.add("Sushi is a dish that originated in which country?", C, "Easy", "Japan", "China", "South Korea", "Thailand");
        a.add("The tango dance is most associated with which country?", C, "Easy", "Argentina", "Brazil", "Spain", "Cuba");
        a.add("In which country are kangaroos native and a national symbol?", C, "Easy", "Australia", "New Zealand", "Indonesia", "South Africa");
        a.add("The giant panda is native to which country?", C, "Easy", "China", "Japan", "Vietnam", "Indonesia");
        a.add("Buckingham Palace is located in which country?", C, "Easy", "United Kingdom", "France", "Belgium", "Netherlands");
        a.add("The Vatican is an enclave within which country?", C, "Easy", "Italy", "France", "Switzerland", "Spain");
        a.add("Which Southeast Asian country is widely known as the 'Land of Smiles'?", C, "Easy", "Thailand", "Vietnam", "Indonesia", "Philippines");
        a.add("The Netherlands is famous for cultivating which spring flower?", C, "Easy", "Tulips", "Roses", "Sunflowers", "Lilies");
        a.add("On which continent is the island nation of Madagascar located?", C, "Easy", "Africa", "Asia", "Oceania", "South America");
        a.add("Bangkok is the capital city of which country?", C, "Easy", "Thailand", "Vietnam", "Cambodia", "Myanmar");
        a.add("The Andes mountain range runs along the western edge of which continent?", C, "Easy", "South America", "North America", "Africa", "Asia");
        a.add("Which is the largest country in Africa by area?", C, "Easy", "Algeria", "Egypt", "Sudan", "Libya");
        a.add("On which continent is Argentina located?", C, "Easy", "South America", "North America", "Africa", "Europe");
        a.add("Which Scandinavian country is often called the 'Land of the Midnight Sun'?", C, "Easy", "Norway", "Sweden", "Finland", "Iceland");
        a.add("On which continent is Australia geographically located?", C, "Easy", "Oceania", "Asia", "Antarctica", "Africa");
        a.add("Which country is reported to have the world's largest population (recent)?", C, "Easy", "India", "China", "United States", "Indonesia");
        a.add("Which river flows through London?", C, "Easy", "Thames", "Severn", "Clyde", "Mersey");
        a.add("Which river flows through New York City and forms part of its harbor?", C, "Easy", "Hudson", "Delaware", "Potomac", "Susquehanna");
        a.add("The Atlantic Ocean lies between Europe and which continent to the west?", C, "Easy", "North America", "South America", "Africa", "Asia");
        a.add("Which is the largest country in Europe by area?", C, "Easy", "Russia", "Ukraine", "France", "Germany");
        a.add("In which country is Niagara Falls' largest waterfall, the Horseshoe Falls, primarily located?", C, "Easy", "Canada", "United States", "Mexico", "Iceland");
        a.add("Which African country is the most populous?", C, "Easy", "Nigeria", "Egypt", "Ethiopia", "South Africa");
        a.add("Which country is widely reported to have the most lakes in the world?", C, "Easy", "Canada", "Russia", "Finland", "Sweden");
        a.add("Antarctica is located on which continent?", C, "Easy", "Antarctica", "South America", "Oceania", "Africa");
        a.add("Which country has the largest number of native Mandarin Chinese speakers?", C, "Easy", "China", "Taiwan", "Singapore", "Malaysia");
        a.add("Which country has the largest number of native Hindi speakers?", C, "Easy", "India", "Pakistan", "Nepal", "Bangladesh");
        a.add("Which country has the largest population of native Spanish speakers?", C, "Easy", "Mexico", "Spain", "Argentina", "Colombia");
        a.add("Which country has the largest population of native English speakers?", C, "Easy", "United States", "United Kingdom", "Canada", "Australia");
        a.add("Mount Kilimanjaro is located in which country?", C, "Easy", "Tanzania", "Kenya", "Uganda", "Ethiopia");
        a.add("Which country is famous for the Statue of Liberty?", C, "Easy", "United States", "France", "United Kingdom", "Canada");
        a.add("Which country is the home of the original Olympic Games?", C, "Easy", "Greece", "Italy", "France", "Egypt");
        a.add("In which country is Mount Everest's southern climbing base located?", C, "Easy", "Nepal", "China", "Bhutan", "India");
        a.add("In which country is the Taj Mahal located?", C, "Easy", "India", "Pakistan", "Bangladesh", "Iran");
        a.add("Which country has Helsinki as its capital?", C, "Easy", "Finland", "Estonia", "Latvia", "Sweden");
        a.add("Which country has Athens as its capital?", C, "Easy", "Greece", "Albania", "Cyprus", "Bulgaria");
        a.add("Which country has Berlin as its capital?", C, "Easy", "Germany", "Austria", "Poland", "Switzerland");

        // ===== Medium (50) =====
        a.add("What is the capital of South Korea?", C, "Medium", "Seoul", "Busan", "Incheon", "Daegu");
        a.add("What is the capital of New Zealand?", C, "Medium", "Wellington", "Auckland", "Christchurch", "Dunedin");
        a.add("What is the capital of Argentina?", C, "Medium", "Buenos Aires", "Cordoba", "Rosario", "La Plata");
        a.add("What is the capital of Chile?", C, "Medium", "Santiago", "Valparaiso", "Concepcion", "Antofagasta");
        a.add("What is the capital of Peru?", C, "Medium", "Lima", "Cusco", "Arequipa", "Trujillo");
        a.add("What is the capital of Colombia?", C, "Medium", "Bogota", "Medellin", "Cali", "Cartagena");
        a.add("What is the capital of Ecuador?", C, "Medium", "Quito", "Guayaquil", "Cuenca", "Ambato");
        a.add("What is the capital of Mexico?", C, "Medium", "Mexico City", "Guadalajara", "Monterrey", "Puebla");
        a.add("What is the capital of Saudi Arabia?", C, "Medium", "Riyadh", "Jeddah", "Mecca", "Medina");
        a.add("What is the capital of the United Arab Emirates?", C, "Medium", "Abu Dhabi", "Dubai", "Sharjah", "Ajman");
        a.add("What is the capital of Iran?", C, "Medium", "Tehran", "Isfahan", "Mashhad", "Tabriz");
        a.add("What is the capital of Iraq?", C, "Medium", "Baghdad", "Mosul", "Basra", "Erbil");
        a.add("What is the capital of Pakistan?", C, "Medium", "Islamabad", "Karachi", "Lahore", "Faisalabad");
        a.add("What is the capital of Bangladesh?", C, "Medium", "Dhaka", "Chittagong", "Khulna", "Sylhet");
        a.add("What is the capital of Indonesia?", C, "Medium", "Jakarta", "Surabaya", "Bandung", "Bali");
        a.add("What is the capital of Malaysia?", C, "Medium", "Kuala Lumpur", "Penang", "Johor Bahru", "Putrajaya");
        a.add("What is the capital of the Philippines?", C, "Medium", "Manila", "Quezon City", "Cebu", "Davao");
        a.add("What is the capital of Vietnam?", C, "Medium", "Hanoi", "Ho Chi Minh City", "Da Nang", "Hue");
        a.add("Cape Town is one of the three capitals of South Africa, serving which branch of government?", C, "Medium", "Legislative", "Judicial", "Executive", "Defense");
        a.add("What is the capital of Nigeria?", C, "Medium", "Abuja", "Lagos", "Kano", "Ibadan");
        a.add("What is the capital of Kenya?", C, "Medium", "Nairobi", "Mombasa", "Kisumu", "Nakuru");
        a.add("What is the capital of Morocco?", C, "Medium", "Rabat", "Casablanca", "Marrakech", "Fez");
        a.add("What is the capital of Ethiopia?", C, "Medium", "Addis Ababa", "Dire Dawa", "Mekelle", "Adama");
        a.add("What is the capital of Algeria?", C, "Medium", "Algiers", "Oran", "Constantine", "Annaba");
        a.add("What is the capital of Romania?", C, "Medium", "Bucharest", "Cluj-Napoca", "Iasi", "Timisoara");
        a.add("What is the capital of Bulgaria?", C, "Medium", "Sofia", "Plovdiv", "Varna", "Burgas");
        a.add("What is the capital of Croatia?", C, "Medium", "Zagreb", "Split", "Rijeka", "Osijek");
        a.add("What is the capital of Slovenia?", C, "Medium", "Ljubljana", "Maribor", "Celje", "Kranj");
        a.add("What is the capital of Slovakia?", C, "Medium", "Bratislava", "Kosice", "Presov", "Zilina");
        a.add("Which is the largest desert in the world (including cold deserts)?", C, "Medium", "Antarctic Polar Desert", "Sahara", "Arabian", "Gobi");
        a.add("Which lake has the largest surface area in the world?", C, "Medium", "Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal");
        a.add("Which is the largest freshwater lake in the world by surface area?", C, "Medium", "Lake Superior", "Lake Victoria", "Lake Baikal", "Lake Michigan");
        a.add("Which is the deepest lake in the world?", C, "Medium", "Lake Baikal", "Lake Tanganyika", "Caspian Sea", "Lake Superior");
        a.add("What is the highest mountain in Africa?", C, "Medium", "Mount Kilimanjaro", "Mount Kenya", "Mount Stanley", "Atlas Range peak");
        a.add("What is the highest mountain in North America?", C, "Medium", "Denali (Mount McKinley)", "Mount Logan", "Mount Whitney", "Pico de Orizaba");
        a.add("What is the highest mountain in South America?", C, "Medium", "Aconcagua", "Ojos del Salado", "Huascaran", "Chimborazo");
        a.add("What is the highest mountain in Europe?", C, "Medium", "Mount Elbrus", "Mont Blanc", "Matterhorn", "Mount Olympus");
        a.add("What is the highest mountain in Antarctica?", C, "Medium", "Vinson Massif", "Mount Erebus", "Mount Sidley", "Mount Kirkpatrick");
        a.add("Which sea is the largest by area in the world?", C, "Medium", "Philippine Sea", "Mediterranean Sea", "South China Sea", "Caribbean Sea");
        a.add("Which country is widely considered to have the most volcanoes?", C, "Medium", "Indonesia", "Japan", "Russia", "United States");
        a.add("Which country is geographically located on both the European and Asian continents?", C, "Medium", "Russia", "Greece", "Iran", "Egypt");
        a.add("The Strait of Gibraltar separates Europe from which continent?", C, "Medium", "Africa", "Asia", "South America", "Australia");
        a.add("Which strait connects the Persian Gulf to the Gulf of Oman?", C, "Medium", "Strait of Hormuz", "Strait of Malacca", "Bosphorus", "Strait of Dover");
        a.add("Which body of water lies between England and France?", C, "Medium", "English Channel", "Irish Sea", "North Sea", "Bay of Biscay");
        a.add("Which U.S. state is geographically separated from the rest of the country by Canada?", C, "Medium", "Alaska", "Hawaii", "Maine", "Washington");
        a.add("Which sea lies between Italy and the Balkan Peninsula?", C, "Medium", "Adriatic Sea", "Ionian Sea", "Tyrrhenian Sea", "Aegean Sea");
        a.add("Which sea lies between Sweden and Estonia/Latvia/Finland?", C, "Medium", "Baltic Sea", "North Sea", "White Sea", "Barents Sea");
        a.add("The Bering Strait separates Russia from which other country?", C, "Medium", "United States", "Canada", "Japan", "Mongolia");
        a.add("Mount Vesuvius is a famous volcano located near which Italian city?", C, "Medium", "Naples", "Rome", "Florence", "Milan");
        a.add("Lake Titicaca is shared between Bolivia and which other country?", C, "Medium", "Peru", "Chile", "Argentina", "Ecuador");

        // ===== Hard (50) =====
        a.add("What is the current capital of Kazakhstan?", C, "Hard", "Astana", "Almaty", "Shymkent", "Karaganda");
        a.add("What is the capital of Uzbekistan?", C, "Hard", "Tashkent", "Samarkand", "Bukhara", "Nukus");
        a.add("What is the capital of Turkmenistan?", C, "Hard", "Ashgabat", "Mary", "Turkmenabat", "Dashoguz");
        a.add("What is the capital of Tajikistan?", C, "Hard", "Dushanbe", "Khujand", "Kulob", "Qurghonteppa");
        a.add("What is the capital of Kyrgyzstan?", C, "Hard", "Bishkek", "Osh", "Jalal-Abad", "Karakol");
        a.add("What is the capital of Azerbaijan?", C, "Hard", "Baku", "Ganja", "Sumqayit", "Mingachevir");
        a.add("What is the capital of Armenia?", C, "Hard", "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat");
        a.add("What is the capital of the country of Georgia?", C, "Hard", "Tbilisi", "Batumi", "Kutaisi", "Rustavi");
        a.add("What is the capital of Belarus?", C, "Hard", "Minsk", "Gomel", "Brest", "Vitebsk");
        a.add("What is the capital of Ukraine?", C, "Hard", "Kyiv", "Lviv", "Kharkiv", "Odesa");
        a.add("What is the capital of Latvia?", C, "Hard", "Riga", "Daugavpils", "Liepaja", "Jelgava");
        a.add("What is the capital of Lithuania?", C, "Hard", "Vilnius", "Kaunas", "Klaipeda", "Siauliai");
        a.add("What is the capital of Estonia?", C, "Hard", "Tallinn", "Tartu", "Narva", "Parnu");
        a.add("What is the capital of Moldova?", C, "Hard", "Chisinau", "Tiraspol", "Balti", "Bender");
        a.add("What is the capital of Albania?", C, "Hard", "Tirana", "Durres", "Vlore", "Shkoder");
        a.add("What is the capital of Bosnia and Herzegovina?", C, "Hard", "Sarajevo", "Banja Luka", "Mostar", "Tuzla");
        a.add("What is the capital of North Macedonia?", C, "Hard", "Skopje", "Bitola", "Kumanovo", "Tetovo");
        a.add("What is the capital of Montenegro?", C, "Hard", "Podgorica", "Niksic", "Cetinje", "Budva");
        a.add("What is the capital of Serbia?", C, "Hard", "Belgrade", "Novi Sad", "Nis", "Kragujevac");
        a.add("What is the capital of Cyprus?", C, "Hard", "Nicosia", "Limassol", "Larnaca", "Paphos");
        a.add("What is the capital of Malta?", C, "Hard", "Valletta", "Birkirkara", "Mosta", "Sliema");
        a.add("What is the capital of Luxembourg?", C, "Hard", "Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange");
        a.add("What is the capital of Liechtenstein?", C, "Hard", "Vaduz", "Schaan", "Triesen", "Balzers");
        a.add("What is the capital of Andorra?", C, "Hard", "Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana");
        a.add("What is the capital of San Marino?", C, "Hard", "San Marino", "Borgo Maggiore", "Serravalle", "Domagnano");
        a.add("What is the capital of Monaco?", C, "Hard", "Monaco", "Monte Carlo", "La Condamine", "Fontvieille");
        a.add("What is the capital of the Comoros?", C, "Hard", "Moroni", "Mutsamudu", "Fomboni", "Domoni");
        a.add("What is the capital of Lesotho?", C, "Hard", "Maseru", "Teyateyaneng", "Mafeteng", "Hlotse");
        a.add("What is the executive capital of Eswatini (formerly Swaziland)?", C, "Hard", "Mbabane", "Lobamba", "Manzini", "Big Bend");
        a.add("What is the capital of Namibia?", C, "Hard", "Windhoek", "Walvis Bay", "Swakopmund", "Rundu");
        a.add("What is the capital of Botswana?", C, "Hard", "Gaborone", "Francistown", "Maun", "Kasane");
        a.add("What is the capital of Zimbabwe?", C, "Hard", "Harare", "Bulawayo", "Mutare", "Gweru");
        a.add("What is the capital of Zambia?", C, "Hard", "Lusaka", "Kitwe", "Ndola", "Livingstone");
        a.add("What is the capital of Mozambique?", C, "Hard", "Maputo", "Beira", "Nampula", "Pemba");
        a.add("What is the capital of Angola?", C, "Hard", "Luanda", "Huambo", "Benguela", "Lobito");
        a.add("What is the capital of Senegal?", C, "Hard", "Dakar", "Thies", "Kaolack", "Saint-Louis");
        a.add("What is the capital of Mali?", C, "Hard", "Bamako", "Sikasso", "Mopti", "Timbuktu");
        a.add("What is the capital of Niger?", C, "Hard", "Niamey", "Zinder", "Maradi", "Agadez");
        a.add("What is the capital of Chad?", C, "Hard", "N'Djamena", "Moundou", "Sarh", "Abeche");
        a.add("What is the capital of Sudan?", C, "Hard", "Khartoum", "Omdurman", "Port Sudan", "Kassala");
        a.add("What is the capital of South Sudan?", C, "Hard", "Juba", "Wau", "Malakal", "Bor");
        a.add("What is the capital of Sierra Leone?", C, "Hard", "Freetown", "Bo", "Kenema", "Makeni");
        a.add("What is the capital of Liberia?", C, "Hard", "Monrovia", "Gbarnga", "Buchanan", "Kakata");
        a.add("What is the capital of Ghana?", C, "Hard", "Accra", "Kumasi", "Tamale", "Sekondi-Takoradi");
        a.add("What is the capital of Cameroon?", C, "Hard", "Yaounde", "Douala", "Bafoussam", "Garoua");
        a.add("What is the capital of the Democratic Republic of the Congo?", C, "Hard", "Kinshasa", "Lubumbashi", "Goma", "Mbuji-Mayi");
        a.add("What is the capital of the Republic of the Congo?", C, "Hard", "Brazzaville", "Pointe-Noire", "Dolisie", "Owando");
        a.add("What is the capital of Rwanda?", C, "Hard", "Kigali", "Butare", "Gisenyi", "Ruhengeri");
        a.add("What is the political capital of Burundi (since 2019)?", C, "Hard", "Gitega", "Bujumbura", "Muyinga", "Ngozi");
        a.add("What is the capital of Djibouti?", C, "Hard", "Djibouti", "Ali Sabieh", "Tadjoura", "Obock");
    }
}
