package com.quiz.config.seeds;

public final class HistorySeeder {
    private static final String C = "History";
    private HistorySeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Who was the U.S. President assassinated in Dallas in 1963?", C, "Easy", "John F. Kennedy", "Abraham Lincoln", "Richard Nixon", "Ronald Reagan");
        a.add("In which country are the famous Pyramids of Giza located?", C, "Easy", "Egypt", "Mexico", "Sudan", "Iraq");
        a.add("In which country is the Great Wall famously found?", C, "Easy", "China", "Japan", "Mongolia", "Korea");
        a.add("On which ship did the Pilgrims sail to North America in 1620?", C, "Easy", "Mayflower", "Santa Maria", "Discovery", "Endeavour");
        a.add("Adolf Hitler was the leader of which country during World War II?", C, "Easy", "Germany", "Italy", "Austria", "Poland");
        a.add("In which country did the Bolshevik Revolution take place?", C, "Easy", "Russia", "Germany", "France", "Poland");
        a.add("During which war did the Holocaust take place?", C, "Easy", "World War II", "World War I", "Cold War", "Korean War");
        a.add("The Cold War was primarily a rivalry between the United States and which other country?", C, "Easy", "Soviet Union", "China", "Germany", "France");
        a.add("Joan of Arc was a national heroine of which country?", C, "Easy", "France", "England", "Spain", "Italy");
        a.add("Alexander the Great originated from which ancient kingdom?", C, "Easy", "Macedonia", "Persia", "Sparta", "Athens");
        a.add("The Roman Colosseum is located in which modern city?", C, "Easy", "Rome", "Athens", "Florence", "Naples");
        a.add("Mahatma Gandhi led the independence movement of which country?", C, "Easy", "India", "Pakistan", "Bangladesh", "Sri Lanka");
        a.add("Martin Luther King Jr. led civil rights protests in which country?", C, "Easy", "United States", "United Kingdom", "South Africa", "France");
        a.add("Nelson Mandela served as President of which country?", C, "Easy", "South Africa", "Kenya", "Nigeria", "Egypt");
        a.add("In which country did the Renaissance originate?", C, "Easy", "Italy", "France", "Germany", "England");
        a.add("Which country sold Alaska to the United States in 1867?", C, "Easy", "Russia", "Canada", "Britain", "Spain");
        a.add("Which side won the American Civil War?", C, "Easy", "The Union (North)", "The Confederacy (South)", "Britain", "France");
        a.add("Against which country did the American colonies fight the Revolutionary War?", C, "Easy", "Britain", "France", "Spain", "Netherlands");
        a.add("Which country dropped atomic bombs on Hiroshima and Nagasaki in 1945?", C, "Easy", "United States", "Soviet Union", "United Kingdom", "France");
        a.add("Which European naval force defeated the Spanish Armada in 1588?", C, "Easy", "England", "France", "Netherlands", "Portugal");
        a.add("Which ancient civilization built Machu Picchu high in the Andes?", C, "Easy", "Inca", "Aztec", "Maya", "Olmec");
        a.add("The Aztec civilization was centered in which present-day country?", C, "Easy", "Mexico", "Peru", "Bolivia", "Guatemala");
        a.add("The Maya civilization was located mainly in which region?", C, "Easy", "Central America", "South America", "North Africa", "Southeast Asia");
        a.add("Who is generally considered the first emperor of the Roman Empire?", C, "Easy", "Augustus", "Julius Caesar", "Nero", "Caligula");
        a.add("From which broad European region did the Vikings originate?", C, "Easy", "Scandinavia", "Iberia", "Balkans", "British Isles");
        a.add("The legend of the Trojan Horse comes from stories about which city?", C, "Easy", "Troy", "Sparta", "Carthage", "Athens");
        a.add("Which wife of King Henry VIII was famously beheaded in 1536?", C, "Easy", "Anne Boleyn", "Jane Seymour", "Anne of Cleves", "Catherine of Aragon");
        a.add("Who was the British Prime Minister during most of World War II?", C, "Easy", "Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden");
        a.add("Who succeeded George Washington as the second U.S. President?", C, "Easy", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe");
        a.add("Who was the 16th President of the United States?", C, "Easy", "Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant", "James Buchanan");
        a.add("How many original colonies are represented by stripes on the U.S. flag?", C, "Easy", "13", "12", "15", "10");
        a.add("In honor of which event was the Eiffel Tower originally built?", C, "Easy", "1889 World's Fair (Exposition Universelle)", "Coronation of Napoleon", "End of WWI", "Bicentennial of France");
        a.add("Cleopatra was the last active ruler of which ancient kingdom?", C, "Easy", "Egypt", "Greece", "Rome", "Persia");
        a.add("In which city did the Boston Tea Party take place?", C, "Easy", "Boston", "New York", "Philadelphia", "Charleston");
        a.add("Who was the Fascist dictator of Italy during World War II?", C, "Easy", "Benito Mussolini", "Adolf Hitler", "Francisco Franco", "Joseph Stalin");
        a.add("Which Renaissance artist painted the ceiling of the Sistine Chapel?", C, "Easy", "Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello");
        a.add("From which country did Christopher Columbus sail in 1492?", C, "Easy", "Spain", "Portugal", "Italy", "England");
        a.add("In which U.S. city does the Statue of Liberty stand?", C, "Easy", "New York", "Boston", "Washington, D.C.", "Philadelphia");
        a.add("Vasco da Gama was a famous explorer from which country?", C, "Easy", "Portugal", "Spain", "Italy", "Netherlands");
        a.add("Which Spanish conquistador led the conquest of the Aztec Empire?", C, "Easy", "Hernan Cortes", "Francisco Pizarro", "Hernando de Soto", "Vasco Nunez de Balboa");
        a.add("Which U.S. agency carried out the first crewed Moon landing in 1969?", C, "Easy", "NASA", "DARPA", "ESA", "Roscosmos");
        a.add("Who is widely regarded as the founder of modern nursing?", C, "Easy", "Florence Nightingale", "Clara Barton", "Mary Seacole", "Edith Cavell");
        a.add("Which U.S. President is associated with the popular toy 'teddy bear'?", C, "Easy", "Theodore Roosevelt", "Franklin Roosevelt", "Andrew Jackson", "Calvin Coolidge");
        a.add("In what approximate year did the Western Roman Empire fall?", C, "Easy", "476 AD", "1066 AD", "800 AD", "1453 AD");
        a.add("Who was the first president of the Republic of Turkey?", C, "Easy", "Mustafa Kemal Ataturk", "Ismet Inonu", "Adnan Menderes", "Suleyman Demirel");
        a.add("Who led the Cuban Revolution that took power in 1959?", C, "Easy", "Fidel Castro", "Che Guevara", "Raul Castro", "Camilo Cienfuegos");
        a.add("Which country's flag features a hammer and sickle on a red field (Soviet era)?", C, "Easy", "Soviet Union", "China", "Cuba", "Vietnam");
        a.add("Who was the wartime British prime minister succeeded by Clement Attlee in 1945?", C, "Easy", "Winston Churchill", "Neville Chamberlain", "Anthony Eden", "Harold Macmillan");
        a.add("Which Indian leader is famous for the Salt March in 1930?", C, "Easy", "Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel");
        a.add("Which 'wall' famously divided a German city from 1961 to 1989?", C, "Easy", "Berlin Wall", "Hadrian's Wall", "Great Wall", "Western Wall");

        // ===== Medium (50) =====
        a.add("Which 1919 treaty officially ended World War I and imposed terms on Germany?", C, "Medium", "Treaty of Versailles", "Treaty of Trianon", "Treaty of Brest-Litovsk", "Treaty of Saint-Germain");
        a.add("The Hundred Years' War was primarily fought between which two countries?", C, "Medium", "England and France", "France and Spain", "England and Scotland", "France and Holy Roman Empire");
        a.add("Which monk's 95 Theses in 1517 helped trigger the Protestant Reformation?", C, "Medium", "Martin Luther", "John Calvin", "Huldrych Zwingli", "Thomas Cranmer");
        a.add("In which century did the Black Death pandemic devastate Europe?", C, "Medium", "14th century", "12th century", "16th century", "10th century");
        a.add("Which Carthaginian general famously crossed the Alps with war elephants?", C, "Medium", "Hannibal", "Hasdrubal", "Mago", "Hamilcar");
        a.add("Which 1815 battle marked the final defeat of Napoleon Bonaparte?", C, "Medium", "Battle of Waterloo", "Battle of Austerlitz", "Battle of Borodino", "Battle of Leipzig");
        a.add("To which remote island was Napoleon ultimately exiled until his death?", C, "Medium", "Saint Helena", "Elba", "Corsica", "Sardinia");
        a.add("Catherine the Great ruled which European empire in the 18th century?", C, "Medium", "Russian Empire", "Austrian Empire", "Holy Roman Empire", "Prussia");
        a.add("In which year did the Boston Massacre take place?", C, "Medium", "1770", "1773", "1775", "1763");
        a.add("In 1215, the Magna Carta limited the power of which monarch?", C, "Medium", "King of England", "King of France", "King of Spain", "Holy Roman Emperor");
        a.add("During which war did the Siege of Leningrad occur?", C, "Medium", "World War II", "World War I", "Russian Civil War", "Crimean War");
        a.add("Which country is known as the 'Land of the Rising Sun'?", C, "Medium", "Japan", "China", "South Korea", "Vietnam");
        a.add("In which year did the Japanese attack on Pearl Harbor occur?", C, "Medium", "1941", "1939", "1945", "1942");
        a.add("In which French region did the Allied D-Day landings occur in 1944?", C, "Medium", "Normandy", "Brittany", "Provence", "Alsace");
        a.add("Who was assassinated by senators on the Ides of March in 44 BC?", C, "Medium", "Julius Caesar", "Augustus", "Pompey", "Cicero");
        a.add("Which Mongol leader led the invasion of Kievan Rus and parts of Europe in the 1240s?", C, "Medium", "Batu Khan", "Ogedei Khan", "Hulagu Khan", "Tamerlane");
        a.add("Which British king lost the American colonies during his reign?", C, "Medium", "King George III", "King George II", "King William III", "King James II");
        a.add("Who was famously known as the 'Sun King' of France?", C, "Medium", "Louis XIV", "Louis XVI", "Henry IV", "Francis I");
        a.add("In 1947 the British Raj was partitioned to create India and which other country?", C, "Medium", "Pakistan", "Bangladesh", "Sri Lanka", "Burma");
        a.add("The Suez Canal connects the Mediterranean Sea with which other body of water?", C, "Medium", "Red Sea", "Persian Gulf", "Arabian Sea", "Black Sea");
        a.add("Which political ideology was led by Benito Mussolini in interwar Italy?", C, "Medium", "Fascism", "Communism", "Anarchism", "Liberalism");
        a.add("Who delivered the famous 1946 'Iron Curtain' speech in Fulton, Missouri?", C, "Medium", "Winston Churchill", "Harry Truman", "Dwight Eisenhower", "Franklin Roosevelt");
        a.add("Which international organization was founded in 1945 to replace the League of Nations?", C, "Medium", "United Nations", "European Union", "NATO", "World Bank");
        a.add("The post-WWII Marshall Plan provided economic aid primarily to which region?", C, "Medium", "Western Europe", "Eastern Europe", "Southeast Asia", "Latin America");
        a.add("In which year did the Cuban Missile Crisis bring the world close to nuclear war?", C, "Medium", "1962", "1958", "1965", "1972");
        a.add("During the Cold War, the Vietnam War was fought between which two regions of Vietnam?", C, "Medium", "North and South Vietnam", "East and West Vietnam", "Hanoi and Cambodia", "Saigon and Laos");
        a.add("In which year did the Korean War begin?", C, "Medium", "1950", "1945", "1953", "1948");
        a.add("Which secret WWII project produced the first atomic bombs?", C, "Medium", "Manhattan Project", "Operation Overlord", "Project Mercury", "Operation Husky");
        a.add("In which year did the Wright Brothers achieve the first powered, controlled airplane flight?", C, "Medium", "1903", "1893", "1910", "1899");
        a.add("Marco Polo's famous late-13th-century travels took him primarily to which continent?", C, "Medium", "Asia", "Africa", "Americas", "Australia");
        a.add("The Mughal Empire ruled large parts of which modern country?", C, "Medium", "India", "Iran", "Turkey", "Indonesia");
        a.add("The Ottoman Empire was centered in territory that is now mostly which country?", C, "Medium", "Turkey", "Syria", "Greece", "Egypt");
        a.add("What was the capital of the Byzantine Empire?", C, "Medium", "Constantinople", "Rome", "Athens", "Antioch");
        a.add("The Code of Hammurabi originated in which ancient region?", C, "Medium", "Babylonia (Mesopotamia)", "Ancient Egypt", "Ancient Greece", "Indus Valley");
        a.add("The 1494 Treaty of Tordesillas divided new lands between which two nations?", C, "Medium", "Spain and Portugal", "England and France", "Spain and France", "Portugal and Netherlands");
        a.add("In which country did the Industrial Revolution famously begin in the 18th century?", C, "Medium", "Great Britain", "France", "Germany", "United States");
        a.add("Which famous English physicist died in 1727?", C, "Medium", "Isaac Newton", "Robert Hooke", "Edmund Halley", "Christopher Wren");
        a.add("During which revolution did the 'Reign of Terror' take place?", C, "Medium", "French Revolution", "American Revolution", "Russian Revolution", "Glorious Revolution");
        a.add("Ancient democracy is most commonly traced to which civilization?", C, "Medium", "Ancient Greece", "Ancient Rome", "Ancient Egypt", "Ancient Persia");
        a.add("Who co-authored 'The Communist Manifesto' with Karl Marx in 1848?", C, "Medium", "Friedrich Engels", "Vladimir Lenin", "Leon Trotsky", "Joseph Stalin");
        a.add("The 1884-1885 Berlin Conference divided which continent among European powers?", C, "Medium", "Africa", "Asia", "Australia", "South America");
        a.add("Which Serbian-American inventor was a famous rival of Thomas Edison in the 'War of Currents'?", C, "Medium", "Nikola Tesla", "Guglielmo Marconi", "George Westinghouse", "Alexander Graham Bell");
        a.add("The Treaty of Westphalia in 1648 ended which long European war?", C, "Medium", "Thirty Years' War", "Hundred Years' War", "Seven Years' War", "Eighty Years' War");
        a.add("Ivan the Terrible was the first ruler to formally take the title of Tsar in which country?", C, "Medium", "Russia", "Poland", "Bulgaria", "Serbia");
        a.add("The Mexican Revolution began in which year?", C, "Medium", "1910", "1898", "1925", "1934");
        a.add("Which empire was destroyed by Hernan Cortes and his expedition in the 1520s?", C, "Medium", "Aztec Empire", "Inca Empire", "Maya civilization", "Olmec civilization");
        a.add("Which empire was destroyed by Francisco Pizarro and his expedition in the 1530s?", C, "Medium", "Inca Empire", "Aztec Empire", "Maya civilization", "Tlaxcala");
        a.add("Which 1804 emperor crowned himself ruler of the French Empire?", C, "Medium", "Napoleon Bonaparte", "Louis Napoleon", "Charles X", "Louis Philippe");
        a.add("Which famous British naval commander died at the Battle of Trafalgar in 1805?", C, "Medium", "Horatio Nelson", "Francis Drake", "James Cook", "John Jervis");
        a.add("Catherine de' Medici was a powerful queen consort of which country?", C, "Medium", "France", "Italy", "Spain", "England");

        // ===== Hard (50) =====
        a.add("In what year was Charlemagne crowned Holy Roman Emperor?", C, "Hard", "800 AD", "962 AD", "476 AD", "1066 AD");
        a.add("At the Battle of Thermopylae, the legendary 300 warriors were primarily from which Greek city-state?", C, "Hard", "Sparta", "Athens", "Corinth", "Thebes");
        a.add("In which year did the Russo-Japanese War end with the Treaty of Portsmouth?", C, "Hard", "1905", "1899", "1910", "1914");
        a.add("In which years was the Spanish Civil War fought?", C, "Hard", "1936-1939", "1929-1932", "1914-1918", "1945-1948");
        a.add("In which country did the Boxer Rebellion of 1899-1901 take place?", C, "Hard", "China", "Japan", "Korea", "Vietnam");
        a.add("What Italian title did Benito Mussolini adopt for himself?", C, "Hard", "Il Duce", "Il Capo", "Il Padrone", "Il Re");
        a.add("What German title did Adolf Hitler adopt as leader of the Nazi state?", C, "Hard", "Der Fuhrer", "Der Kanzler", "Der Konig", "Der Kaiser");
        a.add("In which year was the Treaty of Brest-Litovsk signed by Soviet Russia?", C, "Hard", "1918", "1914", "1922", "1916");
        a.add("In which year was the Treaty of Versailles signed?", C, "Hard", "1919", "1918", "1920", "1924");
        a.add("Who was the first ruler (founder) of the Mughal Empire in India?", C, "Hard", "Babur", "Akbar", "Humayun", "Aurangzeb");
        a.add("Akbar the Great expanded which empire in the 16th century?", C, "Hard", "Mughal Empire", "Maratha Empire", "Vijayanagara Empire", "Sultanate of Delhi");
        a.add("What was the capital of the Inca Empire?", C, "Hard", "Cuzco", "Machu Picchu", "Lima", "Quito");
        a.add("Thomas Cromwell was a chief minister to which English monarch?", C, "Hard", "Henry VIII", "Henry VII", "Edward VI", "Mary I");
        a.add("Eleanor of Aquitaine was first married to which French king?", C, "Hard", "Louis VII", "Philip II", "Henry I", "Charles VII");
        a.add("The Hagia Sophia in Constantinople was originally constructed as what kind of building?", C, "Hard", "Christian (Byzantine) cathedral", "Mosque", "Roman temple", "Imperial palace");
        a.add("In which year did the Battle of Stalingrad effectively end with German surrender?", C, "Hard", "1943", "1941", "1944", "1945");
        a.add("In which year was the Battle of Midway fought?", C, "Hard", "1942", "1941", "1944", "1939");
        a.add("In which year was the Battle of Trafalgar fought?", C, "Hard", "1805", "1799", "1815", "1812");
        a.add("Which French king's reign of more than 70 years made him the longest-reigning monarch of France?", C, "Hard", "Louis XIV", "Louis XV", "Louis XIII", "Louis XVI");
        a.add("The 1618 Defenestration of Prague is widely considered the trigger for which long war?", C, "Hard", "Thirty Years' War", "Hundred Years' War", "Eighty Years' War", "Seven Years' War");
        a.add("What was Vladimir Lenin's birth surname?", C, "Hard", "Ulyanov", "Dzhugashvili", "Trotsky", "Bronstein");
        a.add("What was Joseph Stalin's birth surname (Georgian)?", C, "Hard", "Dzhugashvili", "Ulyanov", "Bronstein", "Molotov");
        a.add("In which year did Constantinople fall to the Ottoman Turks?", C, "Hard", "1453", "1492", "1066", "1517");
        a.add("On which Pacific archipelago was Captain James Cook killed in 1779?", C, "Hard", "Hawaii", "Tahiti", "Samoa", "New Zealand");
        a.add("In which years was the Crimean War (involving Britain, France, Russia) fought?", C, "Hard", "1853-1856", "1870-1871", "1898-1899", "1839-1842");
        a.add("In which year did Iceland gain full independence from Denmark?", C, "Hard", "1944", "1918", "1948", "1955");
        a.add("Who led the Communist 'Long March' in China in 1934-35?", C, "Hard", "Mao Zedong", "Zhou Enlai", "Chiang Kai-shek", "Sun Yat-sen");
        a.add("In which country did Mao Zedong launch the Cultural Revolution in 1966?", C, "Hard", "China", "Vietnam", "North Korea", "Soviet Union");
        a.add("In which year did the Suez Crisis occur?", C, "Hard", "1956", "1948", "1962", "1973");
        a.add("Which 1783 treaty formally recognized U.S. independence from Great Britain?", C, "Hard", "Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Utrecht");
        a.add("The 313 AD Edict of Milan, granting tolerance to Christians, was issued largely under which Roman emperor?", C, "Hard", "Constantine the Great", "Diocletian", "Theodosius", "Justinian");
        a.add("In Napoleonic history, the 'Hundred Days' refers to which event?", C, "Hard", "Napoleon's return from Elba and final defeat", "His coronation as emperor", "His Egyptian campaign", "His Russian campaign");
        a.add("Which 19th-century Prussian statesman is most associated with the unification of Germany?", C, "Hard", "Otto von Bismarck", "Wilhelm II", "Helmuth von Moltke", "Bethmann Hollweg");
        a.add("Which Italian general played a leading role in the unification of Italy in the 1860s?", C, "Hard", "Giuseppe Garibaldi", "Camillo Cavour", "Victor Emmanuel II", "Giuseppe Mazzini");
        a.add("The ancient Hittite Empire was based in which modern region?", C, "Hard", "Anatolia (modern Turkey)", "Mesopotamia", "Levant", "Egypt");
        a.add("The three Punic Wars were fought between Rome and which other ancient city-state?", C, "Hard", "Carthage", "Athens", "Sparta", "Persia");
        a.add("Athens' 'Golden Age' in the 5th century BC is most associated with which statesman?", C, "Hard", "Pericles", "Solon", "Cleisthenes", "Themistocles");
        a.add("Which Roman emperor convened the First Council of Nicaea in 325 AD?", C, "Hard", "Constantine the Great", "Theodosius I", "Justinian", "Diocletian");
        a.add("Who was Genghis Khan's grandson that founded the Yuan Dynasty in China?", C, "Hard", "Kublai Khan", "Ogedei Khan", "Hulagu Khan", "Mongke Khan");
        a.add("During which years did the Ming Dynasty rule China?", C, "Hard", "1368-1644", "618-907", "960-1279", "1644-1912");
        a.add("According to traditional Japanese mythology, who was the first emperor of Japan?", C, "Hard", "Emperor Jimmu", "Emperor Meiji", "Emperor Tenmu", "Emperor Kanmu");
        a.add("In which year did Japan's Meiji Restoration formally begin?", C, "Hard", "1868", "1853", "1905", "1912");
        a.add("Which Mughal emperor commissioned the construction of the Taj Mahal?", C, "Hard", "Shah Jahan", "Akbar", "Aurangzeb", "Humayun");
        a.add("On what date did Parisian crowds storm the Bastille at the start of the French Revolution?", C, "Hard", "14 July 1789", "4 July 1789", "26 August 1789", "20 June 1789");
        a.add("Which 1848 figure became the first president of the Second French Republic?", C, "Hard", "Louis-Napoleon Bonaparte", "Adolphe Thiers", "Lamartine", "Cavaignac");
        a.add("Which 1848 treaty ended the Mexican-American War?", C, "Hard", "Treaty of Guadalupe Hidalgo", "Gadsden Purchase", "Treaty of Cordoba", "Treaty of Velasco");
        a.add("Ramesses II was a famously long-reigning pharaoh of which kingdom?", C, "Hard", "Ancient Egypt", "Babylonia", "Assyria", "Persia");
        a.add("In which year did the Soviet Union officially dissolve?", C, "Hard", "1991", "1989", "1993", "1985");
        a.add("Who became the first General Secretary of the Communist Party of China?", C, "Hard", "Chen Duxiu", "Mao Zedong", "Zhou Enlai", "Sun Yat-sen");
        a.add("What was the formal name of Russia's secret police that became the Cheka in 1917?", C, "Hard", "All-Russian Extraordinary Commission", "NKVD", "KGB", "GRU");
    }
}
