package com.quiz.config.seeds;

public final class JavaBasicsSeeder {
    private static final String C = "Java Basics";
    private JavaBasicsSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which Java symbol is used for the addition operator?", C, "Easy", "+", "-", "*", "/");
        a.add("Which Java symbol is used for the subtraction operator?", C, "Easy", "-", "+", "*", "/");
        a.add("Which Java symbol is used for the multiplication operator?", C, "Easy", "*", "x", "+", "/");
        a.add("Which Java symbol is used for the division operator?", C, "Easy", "/", "\\", "%", "*");
        a.add("Which Java symbol is used for the modulo (remainder) operator?", C, "Easy", "%", "/", "mod", "rem");
        a.add("Which symbol is used for the logical AND operator in Java?", C, "Easy", "&&", "&", "and", "AND");
        a.add("Which symbol is used for the logical OR operator in Java?", C, "Easy", "||", "|", "or", "OR");
        a.add("Which symbol is used for the logical NOT operator in Java?", C, "Easy", "!", "~", "not", "NOT");
        a.add("Which Java symbol is used for the less-than comparison?", C, "Easy", "<", ">", "<=", "!");
        a.add("Which Java symbol is used for the greater-than comparison?", C, "Easy", ">", "<", ">=", "?");
        a.add("Which Java symbol is used for less-than-or-equal-to?", C, "Easy", "<=", "=<", "<<", "lt");
        a.add("Which Java symbol is used for greater-than-or-equal-to?", C, "Easy", ">=", "=>", ">>", "gt");
        a.add("Which Java operator increments a variable by 1?", C, "Easy", "++", "+1", "+=", "inc");
        a.add("Which Java operator decrements a variable by 1?", C, "Easy", "--", "-1", "-=", "dec");
        a.add("Which Java operator adds and assigns in one step?", C, "Easy", "+=", "=+", "++", "+!");
        a.add("Which Java operator performs bitwise AND on integer operands?", C, "Easy", "&", "&&", "and", "|");
        a.add("Which Java operator performs bitwise OR on integer operands?", C, "Easy", "|", "||", "or", "&");
        a.add("Which Java operator performs bitwise XOR (exclusive OR)?", C, "Easy", "^", "&", "|", "~");
        a.add("Which Java operator performs the left bit shift?", C, "Easy", "<<", ">>", "<<<", "<");
        a.add("Which Java operator performs the signed right bit shift?", C, "Easy", ">>", "<<", ">>>", ">");
        a.add("Which Java statement is used to choose between multiple discrete cases?", C, "Easy", "switch", "if", "select", "case");
        a.add("Which Java statement is used for two-way branching based on a boolean condition?", C, "Easy", "if/else", "switch", "case", "when");
        a.add("Which keyword introduces an individual case in a switch statement?", C, "Easy", "case", "when", "match", "if");
        a.add("Which keyword introduces the catch-all branch of a switch statement?", C, "Easy", "default", "else", "otherwise", "fallback");
        a.add("Which character ends a statement in Java?", C, "Easy", ";", ":", ".", ",");
        a.add("What is the file extension of a compiled Java class file?", C, "Easy", ".class", ".jar", ".java", ".bin");
        a.add("What is the file extension of a Java source file?", C, "Easy", ".java", ".class", ".jvm", ".src");
        a.add("What is the standard signature of the Java program entry point?", C, "Easy", "public static void main(String[] args)", "public void main(String args)", "static int main(String args)", "void main()");
        a.add("Which Java access modifier makes a member visible everywhere?", C, "Easy", "public", "private", "protected", "static");
        a.add("Which Java access modifier makes a member visible to subclasses and the same package?", C, "Easy", "protected", "public", "default", "private");
        a.add("Which method modifier indicates that a method cannot be overridden?", C, "Easy", "final", "static", "abstract", "private");
        a.add("Which method modifier indicates a method has no implementation in this class?", C, "Easy", "abstract", "static", "final", "default");
        a.add("Which class modifier prevents the class from being instantiated directly?", C, "Easy", "abstract", "final", "static", "private");
        a.add("Which character separates parts of a Java package name?", C, "Easy", ".", "/", "_", "::");
        a.add("A constructor in Java must share which name?", C, "Easy", "The class name", "The package name", "The interface name", "The file name");
        a.add("Which two literal values can a Java boolean hold?", C, "Easy", "true and false", "0 and 1", "yes and no", "on and off");
        a.add("In Java, which characters enclose a String literal?", C, "Easy", "Double quotes \"\"", "Single quotes ''", "Backticks ``", "Slashes //");
        a.add("In Java, which characters enclose a char literal?", C, "Easy", "Single quotes ''", "Double quotes \"\"", "Backticks ``", "Pipes ||");
        a.add("Which built-in class is the most common way to read input from the console in Java?", C, "Easy", "Scanner", "Reader", "InputReader", "Console");
        a.add("Which String method tests two strings for character-by-character equality?", C, "Easy", ".equals()", "==", ".compare()", ".same()");
        a.add("Which String method returns the position of the first occurrence of a substring?", C, "Easy", ".indexOf()", ".find()", ".search()", ".positionOf()");
        a.add("Which String method returns the character at a given index?", C, "Easy", ".charAt(i)", ".getChar(i)", ".at(i)", ".letter(i)");
        a.add("Which String method returns a lowercase copy of the string?", C, "Easy", ".toLowerCase()", ".lower()", ".small()", ".lcase()");
        a.add("Which String method returns an uppercase copy of the string?", C, "Easy", ".toUpperCase()", ".upper()", ".big()", ".ucase()");
        a.add("Which String method removes leading and trailing whitespace?", C, "Easy", ".trim()", ".strip() only", ".clean()", ".cut()");
        a.add("Which Java keyword declares a method in a class?", C, "Easy", "(no keyword - signature alone)", "method", "func", "def");
        a.add("Which Java type stores a single 16-bit Unicode character?", C, "Easy", "char", "string", "byte", "letter");
        a.add("Which Java keyword denotes that a method takes no parameters?", C, "Easy", "Empty parentheses ()", "void()", "none()", "null()");
        a.add("Which keyword is used to allocate a new object instance in Java?", C, "Easy", "new", "alloc", "create", "make");
        a.add("Which keyword denotes the absence of a value for a Java reference?", C, "Easy", "null", "nil", "none", "undefined");

        // ===== Medium (50) =====
        a.add("Which keyword marks a class member as belonging to the class itself rather than to instances?", C, "Medium", "static", "shared", "global", "common");
        a.add("Which Java keyword makes a variable's value unable to be reassigned after initialization?", C, "Medium", "final", "static", "const", "fixed");
        a.add("Which Java access level applies when no access modifier is specified?", C, "Medium", "Package-private (default)", "Public", "Private", "Protected");
        a.add("Inside an instance method, what does the 'this' keyword reference?", C, "Medium", "The current instance", "The class object", "The parent class", "The package");
        a.add("Inside an instance method, what does the 'super' keyword reference?", C, "Medium", "The parent class component of the current object", "The current instance", "The Class object", "A static parent");
        a.add("Java does not support multiple inheritance of state from which kind of type?", C, "Medium", "Concrete classes", "Interfaces", "Annotations", "Records");
        a.add("Which Java keyword establishes a class inheritance relationship?", C, "Medium", "extends", "implements", "inherits", "subclass");
        a.add("Which Java keyword is used to indicate that a class implements an interface?", C, "Medium", "implements", "extends", "uses", "satisfies");
        a.add("An abstract method may only appear in which kind of type?", C, "Medium", "An abstract class or an interface", "Any class", "A final class", "A record");
        a.add("If a class contains at least one abstract method, the class itself must be declared as what?", C, "Medium", "abstract", "final", "static", "interface");
        a.add("Variables that are declared inside a method body are referred to as what?", C, "Medium", "Local variables", "Instance variables", "Static variables", "Class variables");
        a.add("A constructor in Java can never have which of the following?", C, "Medium", "An explicit return type", "Parameters", "An access modifier", "An overload");
        a.add("Which syntax is used to call another constructor of the same class from within a constructor?", C, "Medium", "this(...)", "super(...)", "self(...)", "ctor(...)");
        a.add("Which syntax is used to call the parent class constructor from a subclass constructor?", C, "Medium", "super(...)", "this(...)", "parent(...)", "extends(...)");
        a.add("Which arithmetic operator has higher precedence in Java: * or +?", C, "Medium", "*", "+", "They are equal", "Depends on the operands");
        a.add("What is Java's bitwise complement (NOT) operator on integers?", C, "Medium", "~", "!", "^", "not");
        a.add("What is Java's conditional (ternary) operator?", C, "Medium", "?:", "??", ":?", "if-else");
        a.add("What does the Java 'instanceof' operator test?", C, "Medium", "Whether an object is an instance of a given type", "Whether two values are equal", "Whether a class exists", "Whether a method has been called");
        a.add("Which Java syntax casts an Object reference to a String?", C, "Medium", "(String) obj", "obj as String", "String(obj)", "obj.toString() (cast)");
        a.add("Casting an object to an unrelated type at runtime can throw which exception?", C, "Medium", "ClassCastException", "IllegalArgumentException", "InvalidCastException", "TypeException");
        a.add("In an expression like 'int + double', what is the resulting promoted type?", C, "Medium", "double", "int", "float", "long");
        a.add("What is the result of integer division 7 / 2 in Java?", C, "Medium", "3", "3.5", "4", "2.5");
        a.add("What is the result of 7.0 / 2 in Java?", C, "Medium", "3.5", "3", "4", "3.0");
        a.add("What is the result of 7 % 3 in Java?", C, "Medium", "1", "0", "2", "3");
        a.add("Which Java operator is overloaded to perform String concatenation?", C, "Medium", "+", "&", "||", ".");
        a.add("Which syntax declares and initializes a Java int array with three values?", C, "Medium", "int[] arr = {1, 2, 3};", "int arr[] = (1,2,3);", "int<3> arr = [1,2,3];", "array(int, 3) = 1,2,3;");
        a.add("How is a two-dimensional int array declared in Java?", C, "Medium", "int[][] matrix", "int<2> matrix", "int matrix[,]", "int.matrix(2)");
        a.add("Switch statements in modern Java can switch on which kinds of values?", C, "Medium", "int, String, enum, and others", "Only int and char", "Only String", "Only boolean");
        a.add("Without a 'break' between cases, what happens in a Java switch?", C, "Medium", "Execution falls through to the next case", "Compilation error always", "Switch returns immediately", "Default case is skipped");
        a.add("A variable declared in a 'for' loop's header is visible in which scope?", C, "Medium", "Only inside the loop body", "Throughout the enclosing method", "Throughout the entire class", "It must be declared 'public' to be visible");
        a.add("How many primitive data types does Java define?", C, "Medium", "8", "6", "10", "12");
        a.add("Java source code is compiled into what intermediate form?", C, "Medium", "Bytecode", "Native machine code", "Assembly language", "Microcode");
        a.add("Java bytecode is interpreted and executed by which component?", C, "Medium", "The JVM", "The OS kernel", "The JDK linker", "The web browser");
        a.add("Java is best described as which kind of typed language?", C, "Medium", "Statically typed", "Dynamically typed", "Untyped", "Weakly typed");
        a.add("Java identifiers may begin with which characters?", C, "Medium", "A letter, underscore, or dollar sign", "Only a letter", "Any character", "Only an underscore");
        a.add("Java identifiers cannot begin with which kind of character?", C, "Medium", "A digit", "An underscore", "A letter", "A dollar sign");
        a.add("By convention, Java constants are written in which style?", C, "Medium", "UPPER_SNAKE_CASE", "camelCase", "PascalCase", "kebab-case");
        a.add("By convention, Java class names are written in which style?", C, "Medium", "PascalCase", "camelCase", "snake_case", "UPPER_SNAKE_CASE");
        a.add("By convention, Java method and variable names are written in which style?", C, "Medium", "camelCase", "PascalCase", "snake_case", "UPPER_SNAKE_CASE");
        a.add("By convention, Java package names are written in which style?", C, "Medium", "all lowercase, dot-separated", "PascalCase, dot-separated", "camelCase", "UPPER_SNAKE_CASE");
        a.add("Method overloading is distinguished from another method by what?", C, "Medium", "Its parameter list (number/types)", "Its return type only", "Its access modifier", "Its name only");
        a.add("Method overriding requires the subclass method to have what relative to the parent method?", C, "Medium", "The same name and compatible signature", "A different name", "A different return type only", "A more restrictive access modifier");
        a.add("Which Java arithmetic exception is thrown by integer division by zero?", C, "Medium", "ArithmeticException", "DivisionException", "NumberFormatException", "IllegalStateException");
        a.add("Which exception subclass hierarchy is unchecked at compile time?", C, "Medium", "RuntimeException and its subclasses", "All Throwable subclasses", "Only Error subclasses", "Only Exception subclasses");
        a.add("Which Java keyword causes a method to declare that it may throw a checked exception?", C, "Medium", "throws", "throw", "raises", "exception");
        a.add("Which Java keyword raises an exception explicitly?", C, "Medium", "throw", "throws", "raise", "fail");
        a.add("Which numeric literal suffix is used for a long literal in Java?", C, "Medium", "L", "Z", "X", "I");
        a.add("Which numeric literal suffix is used for a float literal in Java?", C, "Medium", "f", "d", "F32", "fl");
        a.add("Which numeric literal suffix is used for a double literal in Java?", C, "Medium", "d", "D64", "f", "dl");
        a.add("Which Java construct lets you handle several exception types in a single catch block?", C, "Medium", "Multi-catch using the | (pipe) operator", "Multi-catch using the , (comma) operator", "An additional throws clause", "A separate finally block");

        // ===== Hard (50) =====
        a.add("What does Java do on integer overflow during arithmetic?", C, "Hard", "Silently wraps around (no exception)", "Throws ArithmeticException", "Promotes to long", "Returns Integer.MAX_VALUE");
        a.add("In which Java release was the Object.finalize() method officially deprecated?", C, "Hard", "Java 9", "Java 8", "Java 11", "Java 17");
        a.add("Can a static method directly access non-static instance fields of the enclosing class?", C, "Hard", "No, only via an instance reference", "Yes, always", "Yes, only if the field is final", "No, never under any circumstance");
        a.add("Can a non-static instance method directly access static members of its class?", C, "Hard", "Yes", "No", "Only if the static member is private", "Only if the method is final");
        a.add("Inside a static method, the 'this' keyword is what?", C, "Hard", "Not allowed (compile error)", "Refers to the Class object", "Always null", "Refers to the most recent instance created");
        a.add("Inside a static method, the 'super' keyword is what?", C, "Hard", "Not allowed (compile error)", "Refers to a global parent", "Always null", "Refers to java.lang.Object");
        a.add("In Java, throwing a new exception loses the original cause unless it is...", C, "Hard", "Chained via the constructor's cause argument or initCause()", "Logged before throwing", "Re-thrown using throws", "Caught in a finally block");
        a.add("Which Java exception types must be either caught or declared in a throws clause?", C, "Hard", "Checked exceptions (subclasses of Exception, excluding RuntimeException)", "All Throwable subclasses", "Only Errors", "Only RuntimeException subclasses");
        a.add("Which two are common examples of java.lang.Error subclasses?", C, "Hard", "OutOfMemoryError and StackOverflowError", "NullPointerException and ClassCastException", "IOException and SQLException", "FileNotFoundException and EOFException");
        a.add("Calling an instance method on a null reference throws which exception?", C, "Hard", "NullPointerException", "IllegalStateException", "NoSuchMethodException", "MissingMethodException");
        a.add("Calling a static method via a null-valued reference variable typically does what?", C, "Hard", "Works (resolved at compile time, not via the object)", "Throws NullPointerException", "Throws NoSuchMethodError", "Calls Object.getClass() instead");
        a.add("What does 'compile-time constant' mean in Java?", C, "Hard", "An expression whose value is fully known and final at compile time", "A value computed once at JVM startup", "Any final variable", "A value that never changes at runtime");
        a.add("Which method on an enum class returns an array of all enum constants?", C, "Hard", "values()", "constants()", "all()", "list()");
        a.add("Which static method on an enum class converts a String name to the matching enum constant?", C, "Hard", "valueOf(String)", "fromString(String)", "parse(String)", "constantOf(String)");
        a.add("A non-static class declared inside another class is generally called what?", C, "Hard", "Inner class", "Local class", "Anonymous class", "Static nested class");
        a.add("A class declared inside the body of a method is called what?", C, "Hard", "Local class", "Inner class", "Static nested class", "Anonymous class");
        a.add("A nameless class defined and instantiated in a single expression is called what?", C, "Hard", "Anonymous class", "Inner class", "Local class", "Lambda");
        a.add("A Java lambda expression is essentially syntactic sugar for what?", C, "Hard", "An anonymous instance of a functional interface", "A static nested class", "A free function with no class", "A multi-method anonymous class");
        a.add("What does Java's 'type erasure' mean for generics?", C, "Hard", "Generic type info is removed at compile time", "Generics are checked only at runtime", "Generics are translated to reflection at runtime", "All generic types become Object at compile time only");
        a.add("Since Java 7, which operator allows the compiler to infer generic type arguments?", C, "Hard", "The diamond operator <>", "The angle operator <>", "The auto operator @", "The infer operator !");
        a.add("In a generic method signature, what does '<? extends Number>' mean?", C, "Hard", "An upper bounded wildcard: Number or any subtype", "A lower bounded wildcard: Number or any supertype", "Any type at all", "Exactly Number");
        a.add("In a generic method signature, what does '<? super Integer>' mean?", C, "Hard", "A lower bounded wildcard: Integer or any supertype", "An upper bounded wildcard: Integer or any subtype", "Exactly Integer", "Any type at all");
        a.add("What does the PECS principle stand for in Java generics?", C, "Hard", "Producer Extends, Consumer Super", "Parent Extends, Child Super", "Public Extends, Composite Super", "Polymorphic Extends, Concrete Super");
        a.add("Java reflection allows you to do what at runtime?", C, "Hard", "Inspect and modify class metadata", "Recompile classes", "Replace the JVM", "Mutate primitive types");
        a.add("How many bits does the Java 'float' primitive use?", C, "Hard", "32", "16", "64", "128");
        a.add("How many bits does the Java 'double' primitive use?", C, "Hard", "64", "32", "128", "16");
        a.add("How many bits does the Java 'char' primitive use?", C, "Hard", "16", "8", "32", "1");
        a.add("Which Unicode encoding form does Java use to store char values?", C, "Hard", "UTF-16", "UTF-8", "UTF-32", "ASCII");
        a.add("What is the value of Integer.MAX_VALUE in Java?", C, "Hard", "2,147,483,647", "1,073,741,823", "65,535", "9,223,372,036,854,775,807");
        a.add("What is the value of Integer.MIN_VALUE in Java?", C, "Hard", "-2,147,483,648", "-1,073,741,824", "-65,536", "-9,223,372,036,854,775,808");
        a.add("What is the Java string literal pool?", C, "Hard", "A shared cache of String literals interned by the JVM", "A separate heap for String objects only", "A pool of mutable Strings", "The garbage collector's String region");
        a.add("How does == compare String objects in Java?", C, "Hard", "It compares references (identity), not character contents", "It compares character contents", "It compares lexicographic order", "It calls equals() under the hood");
        a.add("Two distinct String literals containing the same characters typically refer to which object(s)?", C, "Hard", "The same pooled String instance", "Two distinct instances on the heap", "Two distinct instances in the pool", "Always two new instances");
        a.add("What does 'new String(\"abc\")' produce in Java?", C, "Hard", "A new String object on the heap, separate from the pool", "A pooled String reference", "A primitive char array", "A shared canonical instance");
        a.add("What does the .intern() method on a String return?", C, "Hard", "The canonical pooled instance with the same contents", "A copy of the String", "A primitive value", "A new String each call");
        a.add("When does an object become eligible for garbage collection in Java?", C, "Hard", "When it is no longer reachable from any GC root", "When .delete() is called on it", "When it leaves the current method", "When the JVM stops");
        a.add("What does the 'java' command-line tool do?", C, "Hard", "Launches the JVM and runs a class's main method", "Compiles .java files into bytecode", "Generates JavaDoc HTML", "Inspects a thread dump");
        a.add("What does the 'javac' command-line tool do?", C, "Hard", "Compiles .java source files into .class files", "Runs a Java class", "Generates JavaDoc", "Decompiles bytecode");
        a.add("What does the 'javadoc' command-line tool do?", C, "Hard", "Generates HTML documentation from Javadoc comments", "Compiles source files", "Profiles a running JVM", "Lints code style");
        a.add("Which API is the modern replacement for the older 'apt' annotation processor tool?", C, "Hard", "The Pluggable Annotation Processing API (JSR 269)", "Lombok", "Java Reflection API", "javac alone");
        a.add("Which guarantee does the 'volatile' keyword NOT provide on its own?", C, "Hard", "Atomicity of compound operations", "Visibility of writes across threads", "Prevention of certain reorderings", "A happens-before edge between writes and reads");
        a.add("On a static synchronized method, the intrinsic lock acquired is on which monitor?", C, "Hard", "The Class object of the declaring class", "Each instance separately", "A global monitor for all classes", "The current Thread");
        a.add("On a non-static synchronized instance method, the intrinsic lock is on which monitor?", C, "Hard", "The 'this' instance", "The Class object", "A global lock", "The Thread object");
        a.add("Which best describes Java's argument-passing semantics?", C, "Hard", "Pass-by-value for primitives and for object references (reference values)", "Pass-by-reference for objects always", "Pass-by-name", "Pass-by-pointer");
        a.add("What does try-with-resources require of the resource type?", C, "Hard", "It must implement AutoCloseable", "It must implement Serializable", "It must extend Object", "It must be marked transient");
        a.add("Which Java 7+ feature lets you literally use underscore separators in numeric literals?", C, "Hard", "Underscores in numeric literals (e.g., 1_000_000)", "Underscored identifiers", "Hex numeric prefix", "Numeric overflow markers");
        a.add("What does the @SafeVarargs annotation do?", C, "Hard", "Suppresses unchecked-warnings for safe varargs methods with generics", "Makes varargs thread-safe", "Forces fixed-arity calls", "Marks varargs as deprecated");
        a.add("In Java's classloading model, what does the 'parent-first' (delegation) rule mean?", C, "Hard", "A class loader first asks its parent to load a class before trying itself", "A class loader loads parent classes first within a JAR", "A class loader loads its first declared parent only", "A class loader prefers child classes over parents");
        a.add("Which Java 8+ method on Map computes a value if the key is absent and stores it?", C, "Hard", "computeIfAbsent", "putIfAbsent only", "getOrDefault", "merge always");
        a.add("Which Java 8+ Stream terminal operation collects results into a structure (e.g., List)?", C, "Hard", "collect(...)", "forEach(...)", "reduce(...) only", "iterator()");
    }
}
