package com.quiz.config.seeds;

public final class JavaSeeder {
    private static final String C = "Java";
    private JavaSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which Java primitive type is a 32-bit signed integer?", C, "Easy", "int", "long", "short", "byte");
        a.add("Which Java primitive type is a 64-bit signed integer?", C, "Easy", "long", "int", "short", "double");
        a.add("Which Java primitive type is a 32-bit floating-point number?", C, "Easy", "float", "double", "int", "long");
        a.add("Which Java primitive type is a 64-bit floating-point number?", C, "Easy", "double", "float", "long", "decimal");
        a.add("Which Java primitive type is a 16-bit signed integer?", C, "Easy", "short", "int", "byte", "long");
        a.add("Which Java primitive type is an 8-bit signed integer?", C, "Easy", "byte", "short", "int", "char");
        a.add("Which Java primitive type stores a single Unicode character?", C, "Easy", "char", "byte", "String", "Character");
        a.add("Which Java primitive type stores 'true' or 'false'?", C, "Easy", "boolean", "bool", "byte", "int");
        a.add("How many bits does a Java 'long' occupy?", C, "Easy", "64", "32", "16", "8");
        a.add("How many bits does a Java 'short' occupy?", C, "Easy", "16", "32", "8", "64");
        a.add("How many bits does a Java 'byte' occupy?", C, "Easy", "8", "16", "32", "1");
        a.add("What is the default value of a Java 'int' field?", C, "Easy", "0", "1", "null", "-1");
        a.add("What is the default value of a Java 'double' field?", C, "Easy", "0.0", "0", "1.0", "null");
        a.add("What is the default value of a Java reference field of type String?", C, "Easy", "null", "\"\"", "\" \"", "0");
        a.add("What is the default value of any reference field in Java?", C, "Easy", "null", "void", "0", "false");
        a.add("Which sequence starts a single-line comment in Java?", C, "Easy", "//", "/*", "#", "<!--");
        a.add("Which symbols enclose a Java multi-line comment?", C, "Easy", "/* */", "// //", "<!-- -->", "## ##");
        a.add("Which Java operator is used for assignment?", C, "Easy", "=", "==", ":=", "<-");
        a.add("Which Java operator tests value/reference equality?", C, "Easy", "==", "=", "===", "equals");
        a.add("Which Java operator tests inequality?", C, "Easy", "!=", "<>", "!==", "not");
        a.add("Which keyword declares a constant (immutable) variable in Java?", C, "Easy", "final", "const", "readonly", "let");
        a.add("Which keyword declares a class member shared across all instances?", C, "Easy", "static", "shared", "global", "common");
        a.add("Which keyword indicates a Java method returns no value?", C, "Easy", "void", "null", "none", "empty");
        a.add("Which Java loop checks the condition before each iteration?", C, "Easy", "while", "do-while", "for-each only", "switch");
        a.add("Which Java loop is guaranteed to execute its body at least once?", C, "Easy", "do-while", "while", "for", "if");
        a.add("Which Java loop is best when you know the number of iterations in advance?", C, "Easy", "for", "while", "do-while", "switch");
        a.add("Which keyword exits a Java loop immediately?", C, "Easy", "break", "continue", "return", "exit");
        a.add("Which keyword skips to the next iteration of a Java loop?", C, "Easy", "continue", "break", "skip", "next");
        a.add("Which keyword exits a Java method, optionally with a value?", C, "Easy", "return", "break", "exit", "yield");
        a.add("Which keyword starts a Java class declaration?", C, "Easy", "class", "struct", "object", "type");
        a.add("Which keyword declares a Java package?", C, "Easy", "package", "module", "namespace", "lib");
        a.add("Which keyword brings a class from another package into scope?", C, "Easy", "import", "include", "use", "require");
        a.add("Which Java wrapper class corresponds to int?", C, "Easy", "Integer", "Int", "IntegerObject", "Numeric");
        a.add("Which Java wrapper class corresponds to long?", C, "Easy", "Long", "LongObject", "Int64", "BigLong");
        a.add("Which Java wrapper class corresponds to double?", C, "Easy", "Double", "Float64", "DoublePrecision", "Decimal");
        a.add("Which Java wrapper class corresponds to boolean?", C, "Easy", "Boolean", "Bool", "BooleanObject", "TrueFalse");
        a.add("Which Java wrapper class corresponds to char?", C, "Easy", "Character", "Char", "CharObject", "Letter");
        a.add("Which standard method prints a line to the console in Java?", C, "Easy", "System.out.println", "Console.WriteLine", "System.print", "Print.line");
        a.add("Which standard method prints text to the console without a trailing newline?", C, "Easy", "System.out.print", "System.out.write", "System.echo", "Out.print");
        a.add("Which built-in Java class represents a sequence of characters?", C, "Easy", "String", "Text", "CharArray", "Sequence");
        a.add("Which built-in Java class is a mutable sequence of characters and is NOT thread-safe?", C, "Easy", "StringBuilder", "StringBuffer", "MutableString", "CharBuilder");
        a.add("Which built-in Java class is a thread-safe mutable sequence of characters?", C, "Easy", "StringBuffer", "StringBuilder", "ThreadString", "AtomicString");
        a.add("Which String method returns the number of characters in the string?", C, "Easy", "length()", "size()", "count()", "len()");
        a.add("Which property returns the number of elements in a Java array?", C, "Easy", "length", "size()", "count", "len()");
        a.add("If you create 'int[] a = new int[5];', what is a.length?", C, "Easy", "5", "0", "4", "10");
        a.add("In a standard Java array, what is the index of the first element?", C, "Easy", "0", "1", "-1", "Depends on the array");
        a.add("Which method converts an int to its String representation?", C, "Easy", "Integer.toString(i)", "i.toString()", "String.fromInt(i)", "Convert.toString(i)");
        a.add("Which method parses a String into an int?", C, "Easy", "Integer.parseInt(s)", "Integer.toInt(s)", "String.toInt(s)", "Convert.parseInt(s)");
        a.add("Which method parses a String into a double?", C, "Easy", "Double.parseDouble(s)", "Double.toDouble(s)", "Number.parseDouble(s)", "String.toDouble(s)");
        a.add("Which keyword declares an enumerated type in Java?", C, "Easy", "enum", "enumeration", "etype", "switch");

        // ===== Medium (50) =====
        a.add("Which Java collection type guarantees no duplicate elements?", C, "Medium", "Set", "List", "Queue", "Map");
        a.add("Which Java Set implementation maintains insertion order of elements?", C, "Medium", "LinkedHashSet", "HashSet", "TreeSet", "EnumSet");
        a.add("Which Java Set implementation orders elements according to their natural ordering?", C, "Medium", "TreeSet", "HashSet", "LinkedHashSet", "ArraySet");
        a.add("Which Java Map implementation preserves insertion order of keys?", C, "Medium", "LinkedHashMap", "HashMap", "TreeMap", "Hashtable");
        a.add("Which Java Map implementation orders keys by natural ordering?", C, "Medium", "TreeMap", "LinkedHashMap", "HashMap", "Hashtable");
        a.add("Which Java Map implementation typically offers the best average-case performance, with no ordering?", C, "Medium", "HashMap", "TreeMap", "LinkedHashMap", "Hashtable");
        a.add("Which interface is implemented by ArrayList?", C, "Medium", "List", "Set", "Map", "Queue");
        a.add("Which interface is implemented by HashMap?", C, "Medium", "Map", "Set", "List", "Collection");
        a.add("Which interface is implemented by HashSet?", C, "Medium", "Set", "List", "Map", "Queue");
        a.add("Which collection interface does LinkedList implement (besides List)?", C, "Medium", "Deque", "Set", "Map", "Iterator");
        a.add("Which Java interface allows traversal of a collection's elements?", C, "Medium", "Iterator", "Comparable", "Iterable", "Streamable");
        a.add("Which interface should a class implement to define a natural ordering of its instances?", C, "Medium", "Comparable", "Comparator", "Iterable", "Cloneable");
        a.add("Which method must a class implement when it implements Comparable<T>?", C, "Medium", "compareTo", "compare", "equals", "hashCode");
        a.add("Which method must a class implement when it implements Comparator<T>?", C, "Medium", "compare", "compareTo", "equals", "sort");
        a.add("Which Java exception class is the root of all errors and exceptions?", C, "Medium", "Throwable", "Exception", "Error", "RuntimeException");
        a.add("Which exception is thrown when accessing a method or field via a null reference?", C, "Medium", "NullPointerException", "ClassCastException", "NumberFormatException", "ArithmeticException");
        a.add("Which exception is thrown when an array index is out of bounds?", C, "Medium", "ArrayIndexOutOfBoundsException", "IndexOutOfBoundsException only", "OutOfRangeException", "ArrayException");
        a.add("Which exception is thrown when parsing an invalid numeric string?", C, "Medium", "NumberFormatException", "NumberParseException", "FormatException", "InvalidNumberException");
        a.add("Which exception is thrown by an invalid (illegal) cast between unrelated types?", C, "Medium", "ClassCastException", "IllegalArgumentException", "InvalidCastException", "TypeMismatchException");
        a.add("Which Java keyword introduces a block that always runs after a try (with or without exception)?", C, "Medium", "finally", "always", "after", "ensure");
        a.add("Which Java keyword is used to manually raise an exception?", C, "Medium", "throw", "throws", "raise", "fire");
        a.add("Which Java keyword in a method signature declares that the method may throw a checked exception?", C, "Medium", "throws", "throw", "raises", "exception");
        a.add("Which package contains core Java classes such as String, Integer, and Math?", C, "Medium", "java.lang", "java.util", "java.io", "java.core");
        a.add("Which package contains the Java collections framework classes?", C, "Medium", "java.util", "java.lang", "java.collections", "java.io");
        a.add("Which package contains classes for stream-based file I/O?", C, "Medium", "java.io", "java.nio", "java.file", "java.util");
        a.add("Which class is commonly used to read user input line by line from System.in?", C, "Medium", "Scanner", "Reader", "InputStream", "Console");
        a.add("Which class is commonly used to write text to a file?", C, "Medium", "FileWriter", "FileOutputStream", "BufferedReader", "PrintReader");
        a.add("Which class is commonly used to read characters from a file?", C, "Medium", "FileReader", "InputStream", "FileWriter", "PrintWriter");
        a.add("What does NIO commonly stand for in Java?", C, "Medium", "New I/O", "Network I/O", "Non-blocking IO only", "Native I/O");
        a.add("Which Java keyword provides intrinsic locking on a monitor?", C, "Medium", "synchronized", "locked", "atomic", "exclusive");
        a.add("Which keyword indicates that a variable's value can be modified by multiple threads and reads should bypass caches?", C, "Medium", "volatile", "synchronized", "atomic", "transient");
        a.add("Which class is the foundational class for creating an OS thread in Java?", C, "Medium", "Thread", "Runnable", "Process", "Worker");
        a.add("Which interface should you implement to define a task that can run in a thread?", C, "Medium", "Runnable", "Threadable", "Executable", "Callable");
        a.add("Which method actually starts a new thread once Thread.start() is called?", C, "Medium", "run() runs in the new thread", "init()", "begin()", "execute()");
        a.add("Which annotation indicates that a method overrides a method from its supertype?", C, "Medium", "@Override", "@OverrideMethod", "@Inherit", "@Super");
        a.add("Which annotation marks an element as deprecated and discouraged from use?", C, "Medium", "@Deprecated", "@Obsolete", "@OldApi", "@Legacy");
        a.add("Which annotation tells the compiler to suppress particular warnings?", C, "Medium", "@SuppressWarnings", "@IgnoreWarnings", "@NoWarnings", "@SilentWarnings");
        a.add("What is a constructor that takes no parameters often called?", C, "Medium", "No-argument (default) constructor", "Empty constructor only", "Static constructor", "Initializer constructor");
        a.add("What is the OO principle of bundling state and behavior together while restricting direct access?", C, "Medium", "Encapsulation", "Inheritance", "Polymorphism", "Abstraction");
        a.add("Which OO principle allows a single interface or method to operate on different concrete types?", C, "Medium", "Polymorphism", "Encapsulation", "Inheritance", "Modularity");
        a.add("Which OO principle hides implementation details and exposes only essential features?", C, "Medium", "Abstraction", "Encapsulation", "Polymorphism", "Composition");
        a.add("Which OO principle allows a subclass to acquire fields and methods of a superclass?", C, "Medium", "Inheritance", "Composition", "Encapsulation", "Aggregation");
        a.add("Which method does a HashMap rely on (combined with hashCode) to detect key equality?", C, "Medium", "equals", "compareTo", "==", "isEqual");
        a.add("In Java, two objects that are equal according to equals() must also have the same value of which method?", C, "Medium", "hashCode()", "toString()", "compareTo()", "getClass()");
        a.add("Which class hierarchy contains both checked and unchecked exceptions?", C, "Medium", "Throwable", "Exception only", "RuntimeException only", "Error only");
        a.add("Which Java construct allows multiple types to be parameterized at compile time?", C, "Medium", "Generics", "Reflection", "Annotations", "Lambdas");
        a.add("Which Java type allows defining a method whose body is provided by another type at runtime?", C, "Medium", "Abstract method", "Static method", "Final method", "Native method");
        a.add("In which Java collection are elements typically retrieved by an integer index in O(1)?", C, "Medium", "ArrayList", "LinkedList", "HashSet", "TreeSet");
        a.add("In which Java collection are insert/remove operations at the ends typically O(1)?", C, "Medium", "LinkedList", "ArrayList", "HashSet", "ArrayDeque only");
        a.add("Which collection class provides a thread-safe Map implementation since Java 5?", C, "Medium", "ConcurrentHashMap", "HashMap", "Hashtable only", "SyncMap");

        // ===== Hard (50) =====
        a.add("Which Java component is responsible for loading classes into the JVM at runtime?", C, "Hard", "ClassLoader", "JIT compiler", "Garbage collector", "Bytecode verifier");
        a.add("Which annotation marks an interface as intended to be used as a lambda target with exactly one abstract method?", C, "Hard", "@FunctionalInterface", "@Lambda", "@SAM", "@SingleMethod");
        a.add("Which Java 8 syntax is used to refer to a method as a lambda?", C, "Hard", "Method references using ::", "Method references using ->", "Method references using @", "Method references using :=");
        a.add("Which Java 8 syntax separates lambda parameters from the lambda body?", C, "Hard", "->", "=>", "::", ":");
        a.add("Which Java 8 method on Collection produces a sequential Stream?", C, "Hard", "stream()", "toStream()", "asStream()", "openStream()");
        a.add("Which Java 8 package introduced the modern date/time API (LocalDate, LocalTime)?", C, "Hard", "java.time", "java.date", "java.util.time", "java.chrono");
        a.add("Which Java 8 feature allows interfaces to provide concrete method implementations?", C, "Hard", "Default methods", "Abstract methods", "Static initializers", "Inner classes");
        a.add("What is the purpose of java.util.Optional<T>?", C, "Hard", "Represent an optional/possibly absent value", "Provide automatic null guards on every method", "Define mandatory parameters", "Synchronize concurrent access");
        a.add("What is the project name for the Java Platform Module System introduced in Java 9?", C, "Hard", "Project Jigsaw", "Project Panama", "Project Loom", "Project Amber");
        a.add("Which interactive REPL tool was introduced as part of Java 9?", C, "Hard", "JShell", "JREPL", "JRun", "JConsole");
        a.add("Which Java 10 keyword enables local-variable type inference?", C, "Hard", "var", "let", "auto", "dynamic");
        a.add("In Java 14+ switch expressions, which keyword returns a value from a case block?", C, "Hard", "yield", "return", "break", "give");
        a.add("Which Java 14 feature introduces a concise way to declare immutable data carrier classes?", C, "Hard", "Records", "Data classes", "Tuples", "POJOs");
        a.add("Which Java 17 feature lets a class restrict which classes may extend or implement it?", C, "Hard", "Sealed classes", "Final classes only", "Hidden classes", "Abstract classes");
        a.add("In the JVM class loader hierarchy, which loader sits at the very top?", C, "Hard", "Bootstrap ClassLoader", "Application ClassLoader", "System ClassLoader", "Extension ClassLoader");
        a.add("What does the 'G1' in G1 garbage collector stand for?", C, "Hard", "Garbage First", "Generational One", "Group One", "Global One");
        a.add("Which garbage collector became the default in Java 9 and later?", C, "Hard", "G1 GC", "Parallel GC", "Serial GC", "CMS");
        a.add("Which experimental garbage collector performs no actual reclamation (often used for testing)?", C, "Hard", "Epsilon GC", "Z GC", "Shenandoah GC", "Parallel GC");
        a.add("Which low-pause concurrent garbage collector was added to OpenJDK by Oracle?", C, "Hard", "ZGC", "Epsilon", "Serial", "CMS");
        a.add("In the JVM, which memory area stores class metadata since Java 8?", C, "Hard", "Metaspace", "PermGen", "Heap", "Code Cache");
        a.add("In the JVM, which memory area is the primary location of allocated Java objects?", C, "Hard", "Heap", "Stack", "Method area only", "Native memory");
        a.add("In the JVM, which memory area stores per-thread local variables and call frames?", C, "Hard", "Stack", "Heap", "Method area", "Direct memory");
        a.add("What does the JIT compiler stand for?", C, "Hard", "Just-In-Time", "Java Instant Translator", "Java Inline Trace", "Just Inlined Translator");
        a.add("In HotSpot's tiered compilation, how many compilation tiers (including interpreter) are usually configured?", C, "Hard", "5 (tiers 0-4)", "3", "2", "10");
        a.add("Which framework, introduced in Java 7, supports parallel divide-and-conquer tasks via work-stealing?", C, "Hard", "Fork/Join framework", "Executors framework only", "CompletableFuture", "Reactor");
        a.add("Which Java NIO Buffer method prepares the buffer for reading after writing into it?", C, "Hard", "flip()", "rewind()", "clear()", "compact()");
        a.add("What is the default initial capacity of an ArrayList in the standard JDK implementation?", C, "Hard", "10", "16", "20", "32");
        a.add("What is the default initial capacity of a HashMap in the standard JDK implementation?", C, "Hard", "16", "10", "32", "64");
        a.add("What is the default load factor of a HashMap?", C, "Hard", "0.75", "1.0", "0.5", "0.9");
        a.add("Since Java 8, when a HashMap bucket's chain length exceeds a threshold, the bucket is converted to which structure?", C, "Hard", "Red-black tree", "Linked list always", "Skip list", "Hash table inside hash table");
        a.add("In Java, the default Integer cache covers which numeric range?", C, "Hard", "-128 to 127", "0 to 255", "-256 to 255", "0 to 1023");
        a.add("Which characteristic best describes the java.lang.String class?", C, "Hard", "Immutable", "Mutable but not thread-safe", "Mutable and thread-safe", "Synchronized always");
        a.add("Why is the String class declared 'final' in Java?", C, "Hard", "To preserve immutability and string pool integrity", "Because of historical reasons only", "To improve garbage collection", "To support sealed classes");
        a.add("Which statement best describes how Java passes method arguments?", C, "Hard", "Always pass-by-value (object references are passed by value too)", "Always pass-by-reference for objects", "Pass-by-reference for primitives only", "Depends on the method modifier");
        a.add("In design patterns, the Singleton pattern guarantees what about its instance?", C, "Hard", "Only one instance exists per JVM (per class loader)", "Only one method may run at a time", "Only one thread may use it", "Only one subclass may exist");
        a.add("Which Java functional interface represents a boolean-valued test of one argument?", C, "Hard", "Predicate<T>", "Function<T,R>", "Supplier<T>", "Consumer<T>");
        a.add("Which Java functional interface represents a function that takes no input and returns a value?", C, "Hard", "Supplier<T>", "Function<Void,T>", "Producer<T>", "Provider<T>");
        a.add("Which Java functional interface represents an operation that takes a value and returns no result?", C, "Hard", "Consumer<T>", "Sink<T>", "Acceptor<T>", "Runnable<T>");
        a.add("Which Java functional interface takes a T and returns a T (a unary operator)?", C, "Hard", "UnaryOperator<T>", "Function<T,T>", "BiFunction<T,T,T>", "Identity<T>");
        a.add("Which class does System.out belong to?", C, "Hard", "PrintStream", "OutputStream", "Writer", "Console");
        a.add("What does JDK stand for in the Java ecosystem?", C, "Hard", "Java Development Kit", "Java Deployment Kit", "Java Distribution Kit", "Java Definition Kit");
        a.add("What does JRE stand for?", C, "Hard", "Java Runtime Environment", "Java Runnable Engine", "Java Reusable Environment", "Java Reflective Engine");
        a.add("What does JVM bytecode have a file extension of?", C, "Hard", ".class", ".java", ".bytecode", ".jvm");
        a.add("Which Java keyword in a class declaration signals the class cannot be instantiated directly and may have abstract methods?", C, "Hard", "abstract", "interface", "final", "sealed");
        a.add("Which Java method is invoked automatically by the JVM (when implemented) before an object is finalized for collection?", C, "Hard", "finalize()", "destroy()", "close()", "dispose()");
        a.add("Which Java construct lets you handle multiple exception types in a single catch block?", C, "Hard", "Multi-catch using | (pipe)", "Multi-catch using , (comma)", "try-with-resources", "rethrow");
        a.add("Which Java 7 feature automatically closes resources declared in a try statement?", C, "Hard", "try-with-resources", "auto-close blocks", "using statement", "close-on-exit");
        a.add("Which interface must a resource type implement to be used in try-with-resources?", C, "Hard", "AutoCloseable", "Closeable only", "Disposable", "Resourceful");
        a.add("In Java reflection, which class is the entry point for inspecting a class at runtime?", C, "Hard", "Class<?>", "Reflection", "Mirror", "MetaClass");
        a.add("Which JVM tool prints information about Java thread stacks of a running process?", C, "Hard", "jstack", "jmap", "jhat", "jstat");
    }
}
