package com.quiz.config.seeds;

public final class LiteratureSeeder {
    private static final String C = "Literature";
    private LiteratureSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Who wrote 'Oliver Twist'?", C, "Easy", "Charles Dickens", "Mark Twain", "Charlotte Bronte", "Thomas Hardy");
        a.add("Who wrote 'A Christmas Carol'?", C, "Easy", "Charles Dickens", "Lewis Carroll", "Wilkie Collins", "Anthony Trollope");
        a.add("Who wrote 'Great Expectations'?", C, "Easy", "Charles Dickens", "George Eliot", "William Thackeray", "Henry James");
        a.add("Who wrote 'The Adventures of Huckleberry Finn'?", C, "Easy", "Mark Twain", "Herman Melville", "Henry James", "Jack London");
        a.add("Who wrote 'The Adventures of Tom Sawyer'?", C, "Easy", "Mark Twain", "Nathaniel Hawthorne", "Washington Irving", "Bret Harte");
        a.add("Who wrote 'Moby-Dick'?", C, "Easy", "Herman Melville", "James Fenimore Cooper", "Henry Wadsworth Longfellow", "Walt Whitman");
        a.add("Who wrote 'The Catcher in the Rye'?", C, "Easy", "J.D. Salinger", "F. Scott Fitzgerald", "Ernest Hemingway", "John Updike");
        a.add("Who wrote 'To Kill a Mockingbird'?", C, "Easy", "Harper Lee", "Toni Morrison", "Carson McCullers", "Flannery O'Connor");
        a.add("Who wrote 'The Lord of the Rings'?", C, "Easy", "J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "Terry Pratchett");
        a.add("Who wrote 'The Hobbit'?", C, "Easy", "J.R.R. Tolkien", "C.S. Lewis", "Lewis Carroll", "Roald Dahl");
        a.add("Who wrote 'Charlie and the Chocolate Factory'?", C, "Easy", "Roald Dahl", "E.B. White", "Maurice Sendak", "Beatrix Potter");
        a.add("Who wrote 'Matilda'?", C, "Easy", "Roald Dahl", "Enid Blyton", "Beatrix Potter", "Eric Carle");
        a.add("Who wrote 'The Cat in the Hat'?", C, "Easy", "Dr. Seuss", "Maurice Sendak", "Eric Carle", "Shel Silverstein");
        a.add("Who wrote 'Green Eggs and Ham'?", C, "Easy", "Dr. Seuss", "P.D. Eastman", "Mo Willems", "Stan Berenstain");
        a.add("Who wrote and illustrated 'Where the Wild Things Are'?", C, "Easy", "Maurice Sendak", "Eric Carle", "Shel Silverstein", "Beatrix Potter");
        a.add("Who wrote 'Alice's Adventures in Wonderland'?", C, "Easy", "Lewis Carroll", "L. Frank Baum", "J.M. Barrie", "Kenneth Grahame");
        a.add("Who wrote 'The Wonderful Wizard of Oz'?", C, "Easy", "L. Frank Baum", "Lewis Carroll", "C.S. Lewis", "J.M. Barrie");
        a.add("Who wrote 'Peter Pan'?", C, "Easy", "J.M. Barrie", "Lewis Carroll", "L. Frank Baum", "Kenneth Grahame");
        a.add("Who wrote 'The Jungle Book'?", C, "Easy", "Rudyard Kipling", "Joseph Conrad", "H. Rider Haggard", "Robert Louis Stevenson");
        a.add("Who wrote 'Treasure Island'?", C, "Easy", "Robert Louis Stevenson", "Daniel Defoe", "Jack London", "Captain Marryat");
        a.add("Who wrote 'Frankenstein'?", C, "Easy", "Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "Robert Louis Stevenson");
        a.add("Who wrote 'Dracula'?", C, "Easy", "Bram Stoker", "Mary Shelley", "Edgar Allan Poe", "H.G. Wells");
        a.add("Who wrote 'The Picture of Dorian Gray'?", C, "Easy", "Oscar Wilde", "George Bernard Shaw", "Henry James", "W.B. Yeats");
        a.add("Who wrote 'The Old Man and the Sea'?", C, "Easy", "Ernest Hemingway", "John Steinbeck", "William Faulkner", "Sinclair Lewis");
        a.add("Who wrote 'Of Mice and Men'?", C, "Easy", "John Steinbeck", "Ernest Hemingway", "F. Scott Fitzgerald", "William Faulkner");
        a.add("Who wrote 'The Diary of a Young Girl'?", C, "Easy", "Anne Frank", "Elie Wiesel", "Primo Levi", "Imre Kertesz");
        a.add("Who wrote 'The Da Vinci Code'?", C, "Easy", "Dan Brown", "John Grisham", "James Patterson", "Lee Child");
        a.add("Who wrote 'The Shining'?", C, "Easy", "Stephen King", "Dean Koontz", "Clive Barker", "Anne Rice");
        a.add("Who wrote the horror novel 'It'?", C, "Easy", "Stephen King", "Dean Koontz", "Bentley Little", "Robert McCammon");
        a.add("Who wrote 'Carrie'?", C, "Easy", "Stephen King", "Shirley Jackson", "Richard Matheson", "Peter Straub");
        a.add("Who wrote 'Charlotte's Web'?", C, "Easy", "E.B. White", "Beatrix Potter", "Roald Dahl", "Kate DiCamillo");
        a.add("Who wrote 'The Little Prince'?", C, "Easy", "Antoine de Saint-Exupery", "Jules Verne", "Victor Hugo", "Marcel Pagnol");
        a.add("Who wrote 'The Hunger Games'?", C, "Easy", "Suzanne Collins", "Stephenie Meyer", "Veronica Roth", "Kiera Cass");
        a.add("Who wrote the 'Twilight' series?", C, "Easy", "Stephenie Meyer", "Suzanne Collins", "Veronica Roth", "Cassandra Clare");
        a.add("Who wrote 'The Fault in Our Stars'?", C, "Easy", "John Green", "Rainbow Rowell", "Jenny Han", "Nicola Yoon");
        a.add("Who created the 'Diary of a Wimpy Kid' book series?", C, "Easy", "Jeff Kinney", "R.L. Stine", "Rick Riordan", "James Patterson");
        a.add("Which famous detective was created by Sir Arthur Conan Doyle?", C, "Easy", "Sherlock Holmes", "Hercule Poirot", "Miss Marple", "Inspector Morse");
        a.add("Which famous spy character was created by Ian Fleming?", C, "Easy", "James Bond", "Jason Bourne", "George Smiley", "Jack Ryan");
        a.add("Who is the wizarding hero of the J.K. Rowling book series?", C, "Easy", "Harry Potter", "Ron Weasley", "Neville Longbottom", "Draco Malfoy");
        a.add("Which young hobbit carries the One Ring on its journey in 'The Lord of the Rings'?", C, "Easy", "Frodo Baggins", "Bilbo Baggins", "Samwise Gamgee", "Merry Brandybuck");
        a.add("Who is the obsessed captain of the Pequod in 'Moby-Dick'?", C, "Easy", "Captain Ahab", "Captain Nemo", "Captain Hook", "Captain Bligh");
        a.add("Who wrote 'The Three Musketeers'?", C, "Easy", "Alexandre Dumas", "Victor Hugo", "Jules Verne", "Honore de Balzac");
        a.add("Who wrote 'The Count of Monte Cristo'?", C, "Easy", "Alexandre Dumas", "Victor Hugo", "Stendhal", "Gustave Flaubert");
        a.add("Who wrote 'Robinson Crusoe'?", C, "Easy", "Daniel Defoe", "Jonathan Swift", "Henry Fielding", "Samuel Richardson");
        a.add("Who wrote 'Gulliver's Travels'?", C, "Easy", "Jonathan Swift", "Daniel Defoe", "Voltaire", "Alexander Pope");
        a.add("Who is traditionally credited with the collection known as 'Aesop's Fables'?", C, "Easy", "Aesop", "Homer", "Hesiod", "La Fontaine");
        a.add("What is the title of Lewis Carroll's sequel to 'Alice's Adventures in Wonderland'?", C, "Easy", "Through the Looking-Glass", "Alice in Mirrorland", "The Tea Party", "The Queen's Garden");
        a.add("Who wrote the children's classic 'Heidi'?", C, "Easy", "Johanna Spyri", "Astrid Lindgren", "Frances Hodgson Burnett", "Louisa May Alcott");
        a.add("How many books are in the main 'Harry Potter' novel series?", C, "Easy", "7", "5", "8", "10");
        a.add("Who wrote the novel 'The Color Purple'?", C, "Easy", "Alice Walker", "Toni Morrison", "Maya Angelou", "Zora Neale Hurston");

        // ===== Medium (50) =====
        a.add("Who wrote 'The Grapes of Wrath'?", C, "Medium", "John Steinbeck", "William Faulkner", "Ernest Hemingway", "Sinclair Lewis");
        a.add("Who wrote 'East of Eden'?", C, "Medium", "John Steinbeck", "F. Scott Fitzgerald", "Saul Bellow", "John Updike");
        a.add("Who wrote 'Little Women'?", C, "Medium", "Louisa May Alcott", "Harriet Beecher Stowe", "Edith Wharton", "Kate Chopin");
        a.add("Who wrote 'Wuthering Heights'?", C, "Medium", "Emily Bronte", "Charlotte Bronte", "Anne Bronte", "Elizabeth Gaskell");
        a.add("Who wrote 'Jane Eyre'?", C, "Medium", "Charlotte Bronte", "Emily Bronte", "Jane Austen", "George Eliot");
        a.add("Who wrote 'The Scarlet Letter'?", C, "Medium", "Nathaniel Hawthorne", "Herman Melville", "Edgar Allan Poe", "Washington Irving");
        a.add("Who wrote 'The Sound and the Fury'?", C, "Medium", "William Faulkner", "Flannery O'Connor", "John Steinbeck", "Richard Wright");
        a.add("Who wrote 'Heart of Darkness'?", C, "Medium", "Joseph Conrad", "Rudyard Kipling", "E.M. Forster", "Henry James");
        a.add("Who wrote 'Lord of the Flies'?", C, "Medium", "William Golding", "George Orwell", "Aldous Huxley", "Anthony Burgess");
        a.add("Who wrote 'A Tale of Two Cities'?", C, "Medium", "Charles Dickens", "Wilkie Collins", "Anthony Trollope", "George Gissing");
        a.add("Who wrote 'David Copperfield'?", C, "Medium", "Charles Dickens", "William Thackeray", "Thomas Hardy", "George Eliot");
        a.add("Who wrote 'Fahrenheit 451'?", C, "Medium", "Ray Bradbury", "Isaac Asimov", "Arthur C. Clarke", "Philip K. Dick");
        a.add("Who wrote 'The Martian Chronicles'?", C, "Medium", "Ray Bradbury", "Isaac Asimov", "Robert A. Heinlein", "Ursula K. Le Guin");
        a.add("Who wrote 'Catch-22'?", C, "Medium", "Joseph Heller", "Kurt Vonnegut", "Norman Mailer", "John Updike");
        a.add("Who wrote 'On the Road'?", C, "Medium", "Jack Kerouac", "William S. Burroughs", "Allen Ginsberg", "Neal Cassady");
        a.add("Who wrote 'Beloved'?", C, "Medium", "Toni Morrison", "Alice Walker", "Maya Angelou", "Zora Neale Hurston");
        a.add("Who wrote 'Things Fall Apart'?", C, "Medium", "Chinua Achebe", "Wole Soyinka", "Ngugi wa Thiong'o", "Ben Okri");
        a.add("Who wrote 'The Sun Also Rises'?", C, "Medium", "Ernest Hemingway", "F. Scott Fitzgerald", "Gertrude Stein", "John Dos Passos");
        a.add("Who wrote 'A Farewell to Arms'?", C, "Medium", "Ernest Hemingway", "Erich Maria Remarque", "Ford Madox Ford", "Robert Graves");
        a.add("Who wrote 'For Whom the Bell Tolls'?", C, "Medium", "Ernest Hemingway", "John Steinbeck", "George Orwell", "Andre Malraux");
        a.add("Who wrote 'The Bell Jar'?", C, "Medium", "Sylvia Plath", "Anne Sexton", "Joan Didion", "Adrienne Rich");
        a.add("Who wrote 'Slaughterhouse-Five'?", C, "Medium", "Kurt Vonnegut", "Joseph Heller", "Norman Mailer", "Don DeLillo");
        a.add("Who wrote 'The Hitchhiker's Guide to the Galaxy'?", C, "Medium", "Douglas Adams", "Terry Pratchett", "Neil Gaiman", "Iain Banks");
        a.add("Who wrote the 'Foundation' science-fiction series?", C, "Medium", "Isaac Asimov", "Arthur C. Clarke", "Ray Bradbury", "Robert A. Heinlein");
        a.add("Who wrote the science-fiction novel 'Dune'?", C, "Medium", "Frank Herbert", "Isaac Asimov", "Arthur C. Clarke", "Larry Niven");
        a.add("Who wrote 'Ender's Game'?", C, "Medium", "Orson Scott Card", "Robert A. Heinlein", "Larry Niven", "Joe Haldeman");
        a.add("Who wrote the novel 'American Gods'?", C, "Medium", "Neil Gaiman", "Stephen King", "Clive Barker", "Charles de Lint");
        a.add("Who wrote 'Coraline'?", C, "Medium", "Neil Gaiman", "Roald Dahl", "Philip Pullman", "Lemony Snicket");
        a.add("Who wrote 'Norwegian Wood'?", C, "Medium", "Haruki Murakami", "Yasunari Kawabata", "Yukio Mishima", "Banana Yoshimoto");
        a.add("Who wrote 'Kafka on the Shore'?", C, "Medium", "Haruki Murakami", "Kazuo Ishiguro", "Kobo Abe", "Ryunosuke Akutagawa");
        a.add("Who wrote the novella 'The Metamorphosis'?", C, "Medium", "Franz Kafka", "Thomas Mann", "Hermann Hesse", "Robert Musil");
        a.add("Who wrote the novel 'The Trial'?", C, "Medium", "Franz Kafka", "Albert Camus", "Jean-Paul Sartre", "Hermann Broch");
        a.add("Who wrote 'The Stranger' (L'Etranger)?", C, "Medium", "Albert Camus", "Jean-Paul Sartre", "Andre Gide", "Marcel Proust");
        a.add("Who wrote 'The Plague' (La Peste)?", C, "Medium", "Albert Camus", "Andre Malraux", "Antoine de Saint-Exupery", "Romain Rolland");
        a.add("Who wrote 'Madame Bovary'?", C, "Medium", "Gustave Flaubert", "Honore de Balzac", "Emile Zola", "Stendhal");
        a.add("Who wrote 'Anna Karenina'?", C, "Medium", "Leo Tolstoy", "Fyodor Dostoevsky", "Ivan Turgenev", "Anton Chekhov");
        a.add("Who wrote 'The Brothers Karamazov'?", C, "Medium", "Fyodor Dostoevsky", "Leo Tolstoy", "Mikhail Lermontov", "Nikolai Gogol");
        a.add("Who wrote 'Notes from Underground'?", C, "Medium", "Fyodor Dostoevsky", "Leo Tolstoy", "Maxim Gorky", "Anton Chekhov");
        a.add("Who wrote 'Sense and Sensibility'?", C, "Medium", "Jane Austen", "Charlotte Bronte", "Maria Edgeworth", "Frances Burney");
        a.add("Who wrote 'Emma'?", C, "Medium", "Jane Austen", "Elizabeth Gaskell", "George Eliot", "Mary Shelley");
        a.add("Who wrote 'Persuasion'?", C, "Medium", "Jane Austen", "Charlotte Bronte", "Anne Bronte", "Anthony Trollope");
        a.add("Who wrote 'Mansfield Park'?", C, "Medium", "Jane Austen", "George Eliot", "Charlotte Bronte", "Maria Edgeworth");
        a.add("Who wrote 'Northanger Abbey'?", C, "Medium", "Jane Austen", "Mary Shelley", "Frances Burney", "Maria Edgeworth");
        a.add("Who wrote 'Gone with the Wind'?", C, "Medium", "Margaret Mitchell", "Edna Ferber", "Pearl S. Buck", "Willa Cather");
        a.add("Who wrote the gothic novel 'Rebecca'?", C, "Medium", "Daphne du Maurier", "Agatha Christie", "Iris Murdoch", "Muriel Spark");
        a.add("Who wrote the play 'The Importance of Being Earnest'?", C, "Medium", "Oscar Wilde", "George Bernard Shaw", "Noel Coward", "J.M. Barrie");
        a.add("Who wrote the play 'An Ideal Husband'?", C, "Medium", "Oscar Wilde", "George Bernard Shaw", "Henrik Ibsen", "Anton Chekhov");
        a.add("Who wrote the tragedy 'Macbeth'?", C, "Medium", "William Shakespeare", "Christopher Marlowe", "Ben Jonson", "Thomas Kyd");
        a.add("Who wrote the tragedy 'King Lear'?", C, "Medium", "William Shakespeare", "John Webster", "Thomas Middleton", "Christopher Marlowe");
        a.add("Who wrote the tragedy 'Othello'?", C, "Medium", "William Shakespeare", "Ben Jonson", "Cyril Tourneur", "John Ford");

        // ===== Hard (50) =====
        a.add("Who wrote the modernist novel 'Ulysses'?", C, "Hard", "James Joyce", "Virginia Woolf", "T.S. Eliot", "Ezra Pound");
        a.add("Who wrote 'A Portrait of the Artist as a Young Man'?", C, "Hard", "James Joyce", "Henry James", "D.H. Lawrence", "Joseph Conrad");
        a.add("Who wrote the short-story collection 'Dubliners'?", C, "Hard", "James Joyce", "Sean O'Casey", "Samuel Beckett", "Frank O'Connor");
        a.add("Who wrote 'Finnegans Wake'?", C, "Hard", "James Joyce", "T.S. Eliot", "Wyndham Lewis", "Flann O'Brien");
        a.add("Who wrote 'To the Lighthouse'?", C, "Hard", "Virginia Woolf", "Katherine Mansfield", "E.M. Forster", "Vita Sackville-West");
        a.add("Who wrote 'Mrs Dalloway'?", C, "Hard", "Virginia Woolf", "Edith Wharton", "Elizabeth Bowen", "Iris Murdoch");
        a.add("Who wrote 'Orlando'?", C, "Hard", "Virginia Woolf", "Vita Sackville-West", "Rebecca West", "Rose Macaulay");
        a.add("Who wrote 'The Magic Mountain'?", C, "Hard", "Thomas Mann", "Hermann Hesse", "Robert Musil", "Stefan Zweig");
        a.add("Who wrote the novella 'Death in Venice'?", C, "Hard", "Thomas Mann", "Hermann Hesse", "Stefan Zweig", "Joseph Roth");
        a.add("Who wrote 'Buddenbrooks'?", C, "Hard", "Thomas Mann", "Theodor Fontane", "Heinrich Mann", "Gunter Grass");
        a.add("Who wrote the multivolume work 'In Search of Lost Time'?", C, "Hard", "Marcel Proust", "Andre Gide", "Romain Rolland", "Anatole France");
        a.add("'Swann's Way' is the first volume of which novel cycle?", C, "Hard", "In Search of Lost Time", "The Human Comedy", "Les Rougon-Macquart", "The Forsyte Saga");
        a.add("Who wrote 'The Master and Margarita'?", C, "Hard", "Mikhail Bulgakov", "Boris Pasternak", "Yevgeny Zamyatin", "Andrei Bely");
        a.add("Who wrote 'Doctor Zhivago'?", C, "Hard", "Boris Pasternak", "Mikhail Sholokhov", "Vladimir Nabokov", "Ivan Bunin");
        a.add("Who wrote 'And Quiet Flows the Don'?", C, "Hard", "Mikhail Sholokhov", "Vasily Grossman", "Ilya Ehrenburg", "Alexei Tolstoy");
        a.add("Who wrote the verse novel 'Eugene Onegin'?", C, "Hard", "Alexander Pushkin", "Mikhail Lermontov", "Nikolai Nekrasov", "Fyodor Tyutchev");
        a.add("Who wrote 'Dead Souls'?", C, "Hard", "Nikolai Gogol", "Ivan Turgenev", "Mikhail Saltykov-Shchedrin", "Ivan Goncharov");
        a.add("Who wrote 'Fathers and Sons'?", C, "Hard", "Ivan Turgenev", "Anton Chekhov", "Ivan Goncharov", "Maxim Gorky");
        a.add("Who wrote 'The Tin Drum'?", C, "Hard", "Gunter Grass", "Heinrich Boll", "Siegfried Lenz", "Bernhard Schlink");
        a.add("Who wrote the WWI novel 'All Quiet on the Western Front'?", C, "Hard", "Erich Maria Remarque", "Robert Graves", "Siegfried Sassoon", "Jaroslav Hasek");
        a.add("Who wrote 'The Sorrows of Young Werther'?", C, "Hard", "Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich von Kleist", "Novalis");
        a.add("Who wrote 'Love in the Time of Cholera'?", C, "Hard", "Gabriel Garcia Marquez", "Mario Vargas Llosa", "Carlos Fuentes", "Julio Cortazar");
        a.add("Who wrote 'The Feast of the Goat'?", C, "Hard", "Mario Vargas Llosa", "Gabriel Garcia Marquez", "Augusto Roa Bastos", "Carlos Fuentes");
        a.add("Who wrote 'The House of the Spirits'?", C, "Hard", "Isabel Allende", "Laura Esquivel", "Elena Poniatowska", "Marta Brunet");
        a.add("Who wrote the novel 'Pedro Paramo'?", C, "Hard", "Juan Rulfo", "Carlos Fuentes", "Octavio Paz", "Mariano Azuela");
        a.add("Who wrote the experimental novel 'Hopscotch' (Rayuela)?", C, "Hard", "Julio Cortazar", "Adolfo Bioy Casares", "Manuel Puig", "Roberto Arlt");
        a.add("Who wrote the short story collection 'The Aleph'?", C, "Hard", "Jorge Luis Borges", "Julio Cortazar", "Ernesto Sabato", "Adolfo Bioy Casares");
        a.add("Who wrote the short fiction collection 'Ficciones'?", C, "Hard", "Jorge Luis Borges", "Julio Cortazar", "Roberto Bolano", "Macedonio Fernandez");
        a.add("Who wrote the novel 'If on a Winter's Night a Traveler'?", C, "Hard", "Italo Calvino", "Umberto Eco", "Cesare Pavese", "Primo Levi");
        a.add("Who wrote the prose poem collection 'Invisible Cities'?", C, "Hard", "Italo Calvino", "Cesare Pavese", "Luigi Pirandello", "Eugenio Montale");
        a.add("Who wrote 'The Name of the Rose'?", C, "Hard", "Umberto Eco", "Italo Calvino", "Cesare Pavese", "Carlo Emilio Gadda");
        a.add("Who wrote 'Foucault's Pendulum'?", C, "Hard", "Umberto Eco", "Italo Calvino", "Andrea Camilleri", "Erri De Luca");
        a.add("Who wrote the Sicilian classic 'The Leopard'?", C, "Hard", "Giuseppe Tomasi di Lampedusa", "Alberto Moravia", "Leonardo Sciascia", "Ignazio Silone");
        a.add("Who wrote the political novel 'I, the Supreme'?", C, "Hard", "Augusto Roa Bastos", "Alejo Carpentier", "Miguel Angel Asturias", "Juan Carlos Onetti");
        a.add("Who wrote the novel 'Blindness' (Ensaio sobre a cegueira)?", C, "Hard", "Jose Saramago", "Antonio Lobo Antunes", "Eca de Queiros", "Fernando Pessoa");
        a.add("Who wrote 'Petals of Blood'?", C, "Hard", "Ngugi wa Thiong'o", "Wole Soyinka", "Chinua Achebe", "Ben Okri");
        a.add("Who wrote 'Half of a Yellow Sun'?", C, "Hard", "Chimamanda Ngozi Adichie", "NoViolet Bulawayo", "Tsitsi Dangarembga", "Buchi Emecheta");
        a.add("Who wrote the novel 'Disgrace'?", C, "Hard", "J.M. Coetzee", "Nadine Gordimer", "Andre Brink", "Damon Galgut");
        a.add("Who wrote the 'Cairo Trilogy'?", C, "Hard", "Naguib Mahfouz", "Tawfik al-Hakim", "Yusuf Idris", "Alaa Al Aswany");
        a.add("Who wrote the novel 'Snow' (Kar)?", C, "Hard", "Orhan Pamuk", "Yashar Kemal", "Elif Shafak", "Nazim Hikmet");
        a.add("Who wrote 'My Name Is Red'?", C, "Hard", "Orhan Pamuk", "Elif Shafak", "Yashar Kemal", "Sabahattin Ali");
        a.add("Who wrote 'Midnight's Children'?", C, "Hard", "Salman Rushdie", "V.S. Naipaul", "Anita Desai", "Vikram Seth");
        a.add("Who wrote the controversial novel 'The Satanic Verses'?", C, "Hard", "Salman Rushdie", "Hanif Kureishi", "Mohsin Hamid", "Kamila Shamsie");
        a.add("Who wrote 'The God of Small Things'?", C, "Hard", "Arundhati Roy", "Kiran Desai", "Jhumpa Lahiri", "Anita Desai");
        a.add("Who wrote the long novel 'A Suitable Boy'?", C, "Hard", "Vikram Seth", "Amitav Ghosh", "Rohinton Mistry", "R.K. Narayan");
        a.add("Who is traditionally credited as the author of 'The Tale of Genji'?", C, "Hard", "Murasaki Shikibu", "Sei Shonagon", "Yoshida Kenko", "Kamo no Chomei");
        a.add("Who wrote the classical Japanese 'Pillow Book'?", C, "Hard", "Sei Shonagon", "Murasaki Shikibu", "Izumi Shikibu", "Yoshida Kenko");
        a.add("In which language was the epic poem 'Beowulf' originally composed?", C, "Hard", "Old English", "Latin", "Old Norse", "Old French");
        a.add("Who wrote 'The Canterbury Tales'?", C, "Hard", "Geoffrey Chaucer", "John Gower", "William Langland", "Thomas Malory");
        a.add("Who wrote the epic poem 'Paradise Lost'?", C, "Hard", "John Milton", "Edmund Spenser", "John Dryden", "Andrew Marvell");
    }
}
