package com.quiz.config.seeds;

public final class ReactBasicsSeeder {
    private static final String C = "React Basics";
    private ReactBasicsSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which company originally created and open-sourced React?", C, "Easy", "Facebook (now Meta)", "Google", "Microsoft", "Twitter");
        a.add("React is best described as which kind of library?", C, "Easy", "A JavaScript library for building user interfaces", "A relational database", "A bundler for JavaScript apps", "A backend framework");
        a.add("In which year was React first publicly released as open source?", C, "Easy", "2013", "2010", "2016", "2008");
        a.add("By convention, React component names should be written in which case?", C, "Easy", "PascalCase", "camelCase", "snake_case", "kebab-case");
        a.add("Which tool most commonly transpiles JSX into plain JavaScript?", C, "Easy", "Babel", "Webpack", "ESLint", "TypeScript only");
        a.add("Which command installs React itself into a project using npm?", C, "Easy", "npm install react", "npm get react", "npm fetch react", "npm add react-core");
        a.add("Which import is most commonly seen at the top of a React file?", C, "Easy", "import React from 'react';", "import 'react' as React;", "import * as React;", "use React;");
        a.add("Which React hook is used to manage local component state?", C, "Easy", "useState", "useStateful", "useStore", "useLocal");
        a.add("Calling 'const [count, setCount] = useState(0)' returns which two things?", C, "Easy", "The current state and an updater function", "The previous and next state", "The state and an effect", "A reducer and a dispatcher");
        a.add("Which React hook memoizes a callback reference between renders?", C, "Easy", "useCallback", "useMemo", "useRef", "useFreeze");
        a.add("Which React hook is the reducer-style alternative to useState?", C, "Easy", "useReducer", "useStore", "useDispatch", "useState");
        a.add("Which React hook lets you read a layout-affecting effect synchronously after DOM mutations?", C, "Easy", "useLayoutEffect", "useEffect", "useDom", "useSyncEffect");
        a.add("Which React hook gives you a mutable ref object useful for DOM access?", C, "Easy", "useRef", "useDom", "useNode", "useElement");
        a.add("React event handler props are written using which casing convention?", C, "Easy", "camelCase (e.g., onClick)", "PascalCase (e.g., OnClick)", "kebab-case (e.g., on-click)", "snake_case (e.g., on_click)");
        a.add("Which prop attaches a click handler to a JSX element in React?", C, "Easy", "onClick", "onclick", "click", "onTap");
        a.add("Which prop attaches a change handler to an input element in React?", C, "Easy", "onChange", "onchange", "change", "onInput only");
        a.add("Which prop is used to handle form submission in React?", C, "Easy", "onSubmit", "onsubmit", "submit", "onFormSubmit");
        a.add("Which special prop helps React identify list items uniquely during rendering?", C, "Easy", "key", "id", "uid", "ref");
        a.add("Which JSX prop sets the CSS class of an element?", C, "Easy", "className", "class", "cssClass", "styleClass");
        a.add("Which JSX prop sets inline styles, taking a JavaScript object?", C, "Easy", "style", "css", "inlineStyle", "styles");
        a.add("Which React 18 function from 'react-dom/client' creates a root for rendering?", C, "Easy", "createRoot", "createApp", "mountRoot", "createMountPoint");
        a.add("Which React Router component, when wrapping a tree, enables routing in a SPA?", C, "Easy", "BrowserRouter", "RouterRoot", "RouteProvider", "RoutingContext");
        a.add("Which React Router component renders a route's element when its path matches?", C, "Easy", "Route", "Path", "Match", "Page");
        a.add("Which React Router component is used to render navigational links?", C, "Easy", "Link (or NavLink)", "Anchor", "Goto", "PageLink");
        a.add("Which legacy React DOM function rendered an app before React 18?", C, "Easy", "ReactDOM.render", "ReactDOM.mount", "ReactDOM.attach", "ReactDOM.boot");
        a.add("Which React prop holds the content placed between a component's opening and closing tags?", C, "Easy", "children", "content", "body", "inner");
        a.add("In a class component, which method returns the JSX to render?", C, "Easy", "render()", "draw()", "build()", "view()");
        a.add("Which command is used by default in Create React App to start the dev server?", C, "Easy", "npm start", "npm run dev", "npm serve", "npm boot");
        a.add("Which Create React App command produces a production build?", C, "Easy", "npm run build", "npm prod", "npm release", "npm bundle");
        a.add("In a default Create React App project, which file is the JS entry point?", C, "Easy", "src/index.js", "src/main.js", "src/app.js", "public/index.js");
        a.add("Which file extension is commonly used for React TypeScript components?", C, "Easy", ".tsx", ".jsx", ".ts", ".react");
        a.add("In React, JSX expressions must return how many root elements?", C, "Easy", "Exactly one (use a Fragment to group siblings)", "Any number, no wrapper needed", "At most three", "Always exactly two");
        a.add("Which short syntax denotes a React Fragment in JSX?", C, "Easy", "<>...</>", "<Fragment.Empty>...</Fragment.Empty>", "<>...<>", "<<...>>");
        a.add("Which characters embed a JavaScript expression inside JSX?", C, "Easy", "{ expression }", "${ expression }", "(( expression ))", "[[ expression ]]");
        a.add("Which two props together typically implement a controlled input field?", C, "Easy", "value and onChange", "name and onChange", "ref and value", "id and onClick");
        a.add("Which method on a form event prevents the browser's default page reload on submit?", C, "Easy", "e.preventDefault()", "e.stop()", "e.cancel()", "e.preventReload()");
        a.add("What is React's standard hook signature for component state?", C, "Easy", "const [state, setState] = useState(initial);", "let state = useState(initial);", "var state = useState(initial);", "useState(initial);");
        a.add("What is React's standard hook signature for side effects?", C, "Easy", "useEffect(() => { ... }, [deps]);", "useEffect((deps) => ... );", "useEffect(deps, () => ...);", "useEffect(deps);");
        a.add("Which JS feature does JSX rely on to compose elements?", C, "Easy", "Function calls (e.g., React.createElement)", "Decorators only", "Reflection only", "Web Components only");
        a.add("Which React feature allows passing data from parent to child component?", C, "Easy", "Props", "Context only", "Refs only", "Globals only");
        a.add("Which React feature allows storing internal mutable data within a component?", C, "Easy", "State", "Props", "Refs only", "Static fields only");
        a.add("Which built-in component lets you render content into a DOM node outside the parent tree?", C, "Easy", "ReactDOM.createPortal", "React.OutsideRender", "React.Detach", "React.Mount");
        a.add("Which JSX boolean shorthand is the same as 'disabled={true}'?", C, "Easy", "disabled", "disabled=\"\"", "disabled=true", "disabled=on");
        a.add("Which React import is needed to use Fragments by their full name?", C, "Easy", "React.Fragment", "React.GroupNode", "React.Wrap", "React.Empty");
        a.add("To pass extra HTML data attributes through JSX, you use the prop named...", C, "Easy", "data-... attributes", "html-... attributes", "raw-... attributes", "ext-... attributes");
        a.add("Which React utility wraps your app to surface potential problems during development?", C, "Easy", "React.StrictMode", "React.SafeMode", "React.DevMode", "React.LintMode");
        a.add("To bind a DOM node to a ref, which prop do you use on a JSX element?", C, "Easy", "ref", "domRef", "node", "elementRef");
        a.add("Which lifecycle stage of a class component runs immediately before unmounting?", C, "Easy", "componentWillUnmount", "componentDidUnmount", "componentWillDestroy", "componentDidDestroy");
        a.add("Which method on a class component lets you set state asynchronously?", C, "Easy", "this.setState(...)", "this.updateState(...)", "this.assignState(...)", "this.changeState(...)");
        a.add("In a controlled component, the source of truth for the input's value is...", C, "Easy", "React state", "The DOM element only", "A global variable", "The browser's localStorage");

        // ===== Medium (50) =====
        a.add("What is React's Virtual DOM?", C, "Medium", "An in-memory representation of the UI used to compute changes", "A second browser DOM behind the scenes", "A mobile-only DOM tree", "A DOM tree shared by Web Workers");
        a.add("Which name is given to the algorithm React uses to diff Virtual DOM trees?", C, "Medium", "Reconciliation", "Hydration", "Rehydration", "Coalescence");
        a.add("What are the three core class component lifecycle phases?", C, "Medium", "Mounting, updating, unmounting", "Build, render, hydrate", "Mount, hydrate, dispose", "Init, render, finalize");
        a.add("Which hook+pattern simulates the old componentDidMount behavior?", C, "Medium", "useEffect with an empty dependency array []", "useState run-once", "useReducer with INIT action", "useRef triggered on mount");
        a.add("Which hook+pattern simulates the old componentWillUnmount behavior?", C, "Medium", "Returning a cleanup function from useEffect", "Calling useEffect inside cleanup", "Using useUnmount", "Setting state to null");
        a.add("React 18 introduced which rendering model by default in createRoot?", C, "Medium", "Concurrent rendering", "Synchronous rendering only", "Worker-based rendering", "Two-phase batching only");
        a.add("Which React 18 API is used to create a root for rendering?", C, "Medium", "createRoot from 'react-dom/client'", "ReactDOM.createApp", "createReactRoot from 'react'", "ReactDOM.render is still preferred");
        a.add("Which higher-order React utility wraps a function component to skip re-render when props are shallow-equal?", C, "Medium", "React.memo", "React.purify", "React.compare", "React.eager");
        a.add("Which class component base provides shallow prop/state comparison automatically?", C, "Medium", "React.PureComponent", "React.Component (always pure)", "React.MemoComponent", "React.ShallowComponent");
        a.add("What is a Higher-Order Component (HOC) in React?", C, "Medium", "A function that takes a component and returns a new enhanced component", "A class with two render methods", "A component with multiple roots", "A native browser element wrapper");
        a.add("What does the render-props pattern in React refer to?", C, "Medium", "Passing a function as a prop and calling it inside the child to render UI", "Rendering all children twice", "Returning JSX from a constructor", "Using setState inside render()");
        a.add("Which API in React is intended to share data through the tree without prop-drilling?", C, "Medium", "The Context API", "The Refs API", "The Children API", "The Portals API");
        a.add("Which function creates a Context object in React?", C, "Medium", "React.createContext", "React.useContext", "React.makeContext", "React.context");
        a.add("Which hook reads the value provided by the nearest matching Context.Provider?", C, "Medium", "useContext", "useProvider", "useStore", "useGlobal");
        a.add("Which JSX element makes a Context value visible to descendants?", C, "Medium", "<MyContext.Provider value={...}>", "<MyContext value={...}>", "<MyContext.Inject value={...}>", "<MyContext.Source value={...}>");
        a.add("If a useEffect dependency array is empty, when does the effect run?", C, "Medium", "Only after the initial mount", "After every render", "Never", "Only on unmount");
        a.add("If a useEffect has no dependency array, when does the effect run?", C, "Medium", "After every render", "Only after mount", "Only after unmount", "Never");
        a.add("If a useEffect's dependency array includes [x], the effect re-runs when...", C, "Medium", "x changes between renders (using Object.is)", "Any state changes", "Any prop changes", "Component is unmounted");
        a.add("When does the cleanup function returned from useEffect run?", C, "Medium", "Before the next effect, and on unmount", "Only on unmount", "After every render only", "Once on the initial mount");
        a.add("Which is the recommended way to run async code inside useEffect?", C, "Medium", "Define an async function inside the effect and call it", "Make the effect callback itself async", "Use async/await directly in setState", "Use top-level await in the file");
        a.add("Which class component lifecycle method runs after every render except the first?", C, "Medium", "componentDidUpdate", "componentDidMount", "componentWillReceiveProps", "componentDidRender");
        a.add("Which built-in class component method allows skipping a re-render if props/state haven't changed?", C, "Medium", "shouldComponentUpdate", "componentWillUpdate", "skipUpdate", "componentWillSkip");
        a.add("On a class component, which method forces a re-render programmatically?", C, "Medium", "this.forceUpdate()", "this.refresh()", "this.rerender()", "this.update()");
        a.add("'Lifting state up' in React refers to what pattern?", C, "Medium", "Moving shared state to the closest common ancestor", "Promoting a local variable to global", "Replacing useState with useReducer", "Storing state in a Context only");
        a.add("Which React anti-pattern can cause subtle bugs when items reorder in a list?", C, "Medium", "Using array index as the React key", "Using stable IDs as the key", "Wrapping items in fragments", "Using onClick instead of onChange");
        a.add("How do you give a React Fragment a key prop in a list?", C, "Medium", "Use the long form <React.Fragment key={k}>...</React.Fragment>", "Use <key=k>...</>", "Use <>{key:k}...</>", "You cannot key fragments");
        a.add("Which library is the most widely used Redux state container?", C, "Medium", "Redux", "MobX", "Recoil", "Zustand");
        a.add("In Redux, the centralized state is stored in what?", C, "Medium", "A single store", "Multiple unrelated stores", "Each component's local state", "The browser's localStorage");
        a.add("In Redux, what describes a change that occurred (by convention as a plain object with a type field)?", C, "Medium", "An action", "A reducer", "An effect", "A snapshot");
        a.add("In Redux, what is a pure function that takes the previous state and an action and returns the next state?", C, "Medium", "A reducer", "An action creator", "A selector", "A middleware");
        a.add("Which Redux Toolkit utility is the recommended way to write reducers and action creators together?", C, "Medium", "createSlice", "combineReducers only", "createAction only", "configureStore");
        a.add("Side effects in Redux are most commonly handled by which kind of code?", C, "Medium", "Middleware (e.g., redux-thunk, redux-saga)", "Reducers", "Selectors", "Components");
        a.add("In modern react-redux, which two hooks have largely replaced the connect() HOC?", C, "Medium", "useSelector and useDispatch", "useStore and useReducer", "useState and useEffect", "useContext and useRef");
        a.add("React Testing Library encourages tests written from whose perspective?", C, "Medium", "The user's perspective", "The component implementation's perspective", "The bundler's perspective", "The CI server's perspective");
        a.add("Which React Testing Library export is commonly used to render a component in tests?", C, "Medium", "render()", "mount()", "draw()", "expose()");
        a.add("Which is the standard naming convention for a custom React hook?", C, "Medium", "Function name starts with 'use'", "Function name ends with 'Hook'", "Function name starts with 'react'", "Function name is all lowercase");
        a.add("A typical custom 'useFetch' hook commonly returns which shape?", C, "Medium", "{ data, loading, error }", "{ promise, status }", "{ value, isLoading }", "{ result }");
        a.add("Which two strategies prevent unnecessary re-renders of a child component?", C, "Medium", "React.memo (props) and useMemo/useCallback (referential stability)", "Direct DOM mutation and skipping render", "Using class components only", "Avoiding state altogether");
        a.add("Which hook returns a memoized function reference?", C, "Medium", "useCallback", "useMemo", "useRef", "useFunc");
        a.add("Which hook returns a memoized value computed from a function?", C, "Medium", "useMemo", "useCallback", "useRef", "useValue");
        a.add("In React Router v6, which hook reads the current URL parameters?", C, "Medium", "useParams", "useUrlParams", "useRouteParams", "useLocationParams");
        a.add("In React Router v6, which hook navigates programmatically?", C, "Medium", "useNavigate", "useHistory (deprecated)", "useRouter", "useGoTo");
        a.add("In React Router v6, which hook returns the current location object?", C, "Medium", "useLocation", "useUrl", "useHistory", "useRoute");
        a.add("React's 'concurrent features' allow rendering work to be...", C, "Medium", "Interrupted, paused, or restarted to keep the UI responsive", "Compiled into web workers", "Always synchronous and uninterruptible", "Run on the GPU instead of CPU");
        a.add("Which React feature allows splitting a large bundle by loading components on demand?", C, "Medium", "React.lazy with Suspense", "React.split", "React.dynamic", "React.import");
        a.add("Which boundary component renders a fallback while a lazy/Suspense child is loading?", C, "Medium", "<Suspense fallback={...}>", "<LazyBoundary fallback={...}>", "<Async fallback={...}>", "<Loading wrap={...}>");
        a.add("Which React 18 hook marks a state update as non-urgent (low priority)?", C, "Medium", "useTransition", "useDefer", "useNonUrgent", "useBackground");
        a.add("Which React 18 hook returns a deferred (slightly stale) value during transitions?", C, "Medium", "useDeferredValue", "useDelay", "useStale", "useLazyValue");
        a.add("Which 'rules of hooks' constraint must always be followed?", C, "Medium", "Hooks must be called at the top level (not inside conditionals/loops)", "Hooks must be called inside try/catch blocks", "Hooks may only be called inside class components", "Hooks may only be called once per app");
        a.add("Why must hooks be called in the same order every render?", C, "Medium", "React relies on call order to associate state with each hook", "It improves bundle size", "It enables hot reloading", "It prevents JSX parsing errors");

        // ===== Hard (50) =====
        a.add("What is the name of React's reimplemented reconciliation engine introduced in React 16?", C, "Hard", "Fiber", "Stack", "Refiner", "Sprout");
        a.add("Which React feature lets you declaratively show fallback UI for asynchronous resources?", C, "Hard", "Suspense", "Async", "Streaming", "Pending");
        a.add("Which React API enables code-splitting by lazily importing a component?", C, "Hard", "React.lazy", "React.dynamic", "React.split", "React.import");
        a.add("Which React 18 hook returns a stable, framework-managed unique ID for accessibility?", C, "Hard", "useId", "useUid", "useUniqueId", "useStableId");
        a.add("Which React 18 hook lets external stores integrate with React's concurrent rendering?", C, "Hard", "useSyncExternalStore", "useStoreSubscription", "useExternalState", "useStore");
        a.add("Which React hook is intended to inject debug labels visible in React DevTools for custom hooks?", C, "Hard", "useDebugValue", "useDebug", "useDevTools", "useTrace");
        a.add("Which React 18 hook fires synchronously before mutations are applied (intended for CSS-in-JS libraries)?", C, "Hard", "useInsertionEffect", "useLayoutEffect", "useStyleEffect", "useCssEffect");
        a.add("In React 18, all state updates inside any callback (including async) are now batched. What is this called?", C, "Hard", "Automatic batching", "Implicit batching", "Concurrent batching", "Forced batching");
        a.add("In development, React.StrictMode intentionally double-invokes which kinds of functions?", C, "Hard", "Render functions and certain lifecycle methods, to surface side effects", "All callbacks twice", "Only constructors", "Only useEffect cleanups");
        a.add("Which React API lets you opt out of automatic batching and apply a state update synchronously?", C, "Hard", "flushSync from 'react-dom'", "syncUpdate from 'react'", "forceFlush from 'react-dom/client'", "applyNow from 'react-dom'");
        a.add("Which React DOM Server API enables streaming server-side rendering with Suspense in React 18?", C, "Hard", "renderToPipeableStream", "renderToString (only)", "hydrateToStream", "ssrStream");
        a.add("Which React API is used to forward a ref from a parent component into a child component?", C, "Hard", "React.forwardRef", "React.useRef", "React.passRef", "React.refForward");
        a.add("Which React hook customizes the value exposed via a forwarded ref to a parent?", C, "Hard", "useImperativeHandle", "useRefHandle", "useExposedRef", "useExportRef");
        a.add("To avoid re-rendering a memoized child due to a fresh inline object literal each render, you should...", C, "Hard", "Wrap the object construction in useMemo to stabilize its reference", "Wrap it in useCallback", "Promote it to a top-level constant only if it never depends on state/props", "Both: useMemo for state-derived; constant for static");
        a.add("In React class components, which lifecycle methods are used to implement an Error Boundary?", C, "Hard", "static getDerivedStateFromError + componentDidCatch", "componentDidUpdate + componentWillUnmount", "componentDidMount + componentWillCatch", "render + componentDidError");
        a.add("Error Boundaries do NOT catch errors that occur in which contexts?", C, "Hard", "Event handlers, async code, and during SSR", "Synchronous render code", "Lifecycle method bodies", "Constructor of the boundary itself");
        a.add("Which React utility component allows you to measure render performance with a callback?", C, "Hard", "<Profiler>", "<Measure>", "<Timer>", "<RenderInfo>");
        a.add("Which transient phase of React's commit lifecycle applies the changes to the actual DOM?", C, "Hard", "Commit phase", "Render phase", "Hydration phase", "Reconciliation phase");
        a.add("Which phase of React's render cycle is purely computational and can be interrupted?", C, "Hard", "Render phase", "Commit phase", "Mount phase", "Effect phase");
        a.add("Hydration in React refers to which process?", C, "Hard", "Attaching event handlers and state to server-rendered HTML on the client", "Sending state from client to server", "Re-rendering after a transition", "Preloading images for faster first paint");
        a.add("React Server Components run where, and what can they NOT use?", C, "Hard", "On the server; they cannot use state or browser-only effects", "On the client; they cannot use props", "On a service worker; they cannot use JSX", "Inside web workers; they cannot use refs");
        a.add("Which React 19 feature lets components await promises and read context conditionally?", C, "Hard", "The 'use' hook (use() API)", "The 'await' hook", "The 'when' hook", "The 'resolve' hook");
        a.add("Which React feature, paired with Server Components, simplifies data mutations from forms?", C, "Hard", "Server Actions / Form Actions", "Server Routers", "Edge Mutations", "Form Reducers");
        a.add("To pass a ref to a deeply nested DOM element through a wrapper component, the wrapper must be created with...", C, "Hard", "React.forwardRef", "React.passRef", "React.exposeRef", "React.exportNode");
        a.add("Which React hook is reserved by convention for synchronizing with browser-only stores like Redux?", C, "Hard", "useSyncExternalStore", "useStoreState", "useReduxStore", "useExternalSync");
        a.add("Which static field on a class component lets you derive state from an error in the boundary?", C, "Hard", "static getDerivedStateFromError(error)", "static deriveError(error)", "static onErrorReceived(error)", "static catch(error)");
        a.add("Which is the conventional way to mark a state update as a non-urgent transition in React 18?", C, "Hard", "startTransition or useTransition's start function", "setState({_transient: true})", "scheduleUpdate(...)", "useDelay(...)");
        a.add("Which React 18 hook reports whether a transition is in progress?", C, "Hard", "useTransition (returns isPending)", "useStatus", "useIsLoading", "useTransientFlag");
        a.add("Which API renders a React tree to a string for traditional SSR (older approach)?", C, "Hard", "ReactDOMServer.renderToString", "ReactDOMServer.toHTML", "ReactDOMServer.flushString", "ReactDOMServer.serialize");
        a.add("If the server-rendered markup does not match what the client renders during hydration, React typically...", C, "Hard", "Logs a hydration mismatch warning and may fall back to client-side render", "Silently fixes the mismatch", "Throws a fatal runtime error always", "Re-renders the entire app on every load");
        a.add("Which third-party library is most commonly used with React for building forms with built-in validation, and is hooks-first?", C, "Hard", "react-hook-form", "Formik (older but popular)", "Final-Form", "RxForm");
        a.add("React Native is best described as which kind of framework?", C, "Hard", "A framework for building native mobile apps using React components", "A native browser fork written in React", "A React-only desktop framework", "A serverless React renderer");
        a.add("In which React version did the new JSX transform allow JSX without explicitly importing React?", C, "Hard", "React 17", "React 16", "React 18", "React 15");
        a.add("Which Babel preset/option enables the new automatic JSX runtime?", C, "Hard", "@babel/preset-react with runtime: 'automatic'", "@babel/preset-jsx with runtime: 'classic'", "babel-plugin-jsx-auto", "babel-runtime-jsx");
        a.add("React's batching means that multiple setState calls inside a single event handler usually cause...", C, "Hard", "One re-render that reflects all the batched updates", "One re-render per setState call", "No re-render until the next tick", "Two re-renders: one immediate, one deferred");
        a.add("Which React feature allows portals to render children into a DOM node outside the parent hierarchy?", C, "Hard", "ReactDOM.createPortal", "React.detach", "React.outerRender", "React.mountElsewhere");
        a.add("Why is calling a hook conditionally (inside an if) forbidden by the rules of hooks?", C, "Hard", "It would change the call order across renders, breaking React's hook bookkeeping", "It violates ECMAScript module semantics", "It causes JSX parsing errors", "It blocks browser garbage collection");
        a.add("Which React function is the conventional way to create a portal in React DOM?", C, "Hard", "ReactDOM.createPortal(children, container)", "React.createPortal(children, container)", "createPortalRoot(children, container)", "Portal.render(children, container)");
        a.add("Which React Profiler callback prop receives timing information for each render commit?", C, "Hard", "onRender", "onCommit", "onMeasure", "onProfile");
        a.add("Which React feature allows treating multiple sibling DOM nodes as if they shared one wrapper without adding markup?", C, "Hard", "Fragments", "Portals", "Suspense boundaries", "Slots");
        a.add("Suspense for data is most idiomatically combined with which API in React 19?", C, "Hard", "use() with a Promise resource", "useAsync()", "useSuspenseQuery()", "useFetchSuspense()");
        a.add("Which React API was deprecated in React 18 in favor of createRoot for client-side rendering?", C, "Hard", "ReactDOM.render", "ReactDOM.hydrate (replaced with hydrateRoot)", "ReactDOM.createPortal", "ReactDOM.unmountComponentAtNode");
        a.add("Which React 18 API hydrates server-rendered markup using the new root model?", C, "Hard", "hydrateRoot from 'react-dom/client'", "ReactDOM.hydrate", "ReactDOM.attachToServer", "createServerRoot");
        a.add("Which is the canonical pattern to share complex stateful logic across components without HOCs?", C, "Hard", "Custom hooks", "Render props", "Higher-order components", "Class mixins (deprecated)");
        a.add("Which React feature lets you opt out of automatic React batching for performance-critical legacy code?", C, "Hard", "flushSync", "manualBatch", "syncRender", "noBatch");
        a.add("Which React behavior helps React 18 keep the UI responsive while large updates are computing?", C, "Hard", "Time-slicing during the render phase", "Switching to a worker thread", "Skipping render entirely", "Disabling event handlers");
        a.add("React's 'fiber' nodes correspond conceptually to what in the React tree?", C, "Hard", "Units of work for components and their state", "DOM nodes one-to-one", "CSS computed styles", "Event listeners");
        a.add("Why does React recommend NOT mutating state directly?", C, "Hard", "React relies on referential equality for change detection and re-render scheduling", "It causes browsers to crash", "It bypasses TypeScript checks", "It is forbidden by ECMAScript");
        a.add("Which library, often paired with React, provides a small atomic state model with hooks?", C, "Hard", "Recoil (or Jotai)", "Vuex", "Pinia", "Ngrx");
        a.add("In a controlled form, which prop pair is the canonical pattern for an input element?", C, "Hard", "value and onChange", "defaultValue and onBlur", "value and onInput", "ref and onSubmit");
    }
}
