package com.quiz.config.seeds;

public final class RestApiSeeder {
    private static final String C = "REST API";
    private RestApiSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which HTTP method is used to retrieve a resource representation?", C, "Easy", "GET", "POST", "PUT", "DELETE");
        a.add("Which HTTP method is conventionally used to fully update (replace) a resource?", C, "Easy", "PUT", "PATCH", "POST", "GET");
        a.add("Which HTTP method is conventionally used to partially update a resource?", C, "Easy", "PATCH", "PUT", "POST", "DELETE");
        a.add("Which HTTP method is used to query the communication options for a resource (e.g., for CORS preflight)?", C, "Easy", "OPTIONS", "TRACE", "HEAD", "CONNECT");
        a.add("Which HTTP method requests only the response headers, with no body?", C, "Easy", "HEAD", "GET", "OPTIONS", "TRACE");
        a.add("Which HTTP status code indicates 'Not Found'?", C, "Easy", "404", "400", "401", "403");
        a.add("Which HTTP status code indicates a generic 'Server Error'?", C, "Easy", "500", "501", "404", "400");
        a.add("Which HTTP status code indicates 'Unauthorized' (authentication required)?", C, "Easy", "401", "403", "400", "404");
        a.add("Which HTTP status code indicates a malformed 'Bad Request'?", C, "Easy", "400", "404", "401", "405");
        a.add("Which HTTP status code commonly indicates 'No Content' on a successful operation?", C, "Easy", "204", "200", "202", "201");
        a.add("Which HTTP status code indicates 'Moved Permanently'?", C, "Easy", "301", "302", "307", "308");
        a.add("Which HTTP status code indicates 'Found' (often used as a temporary redirect)?", C, "Easy", "302", "301", "307", "303");
        a.add("Which HTTP status code indicates 'Service Unavailable'?", C, "Easy", "503", "500", "504", "502");
        a.add("Which HTTP status code indicates 'Gateway Timeout'?", C, "Easy", "504", "503", "502", "408");
        a.add("Which HTTP status code indicates a 'Conflict' (e.g., concurrent edit conflict)?", C, "Easy", "409", "410", "412", "417");
        a.add("Status codes in the range 4xx are reserved for what kind of errors?", C, "Easy", "Client errors", "Server errors", "Successful responses", "Redirects");
        a.add("Status codes in the range 5xx are reserved for what kind of errors?", C, "Easy", "Server errors", "Client errors", "Redirects", "Informational");
        a.add("Status codes in the range 2xx indicate which kind of outcome?", C, "Easy", "Success", "Client error", "Redirect", "Server error");
        a.add("Status codes in the range 3xx indicate which kind of outcome?", C, "Easy", "Redirection", "Success", "Client error", "Server error");
        a.add("Status codes in the range 1xx indicate which kind of outcome?", C, "Easy", "Informational", "Success", "Server error", "Redirection");
        a.add("In CRUD, which HTTP method most directly maps to 'Read'?", C, "Easy", "GET", "POST", "PUT", "DELETE");
        a.add("In CRUD, which HTTP methods most commonly map to 'Update'?", C, "Easy", "PUT or PATCH", "GET only", "POST only", "DELETE only");
        a.add("In CRUD, which HTTP method most directly maps to 'Delete'?", C, "Easy", "DELETE", "POST", "GET", "REMOVE");
        a.add("What does the 'R' in REST stand for?", C, "Easy", "Representational", "Remote", "Reactive", "Reusable");
        a.add("What does the 'T' in REST stand for?", C, "Easy", "Transfer", "Type", "Token", "Transaction");
        a.add("Which HTTP request header indicates the media type of the request body?", C, "Easy", "Content-Type", "Accept", "Content-Encoding", "Content-Length");
        a.add("Which HTTP request header lists media types the client is willing to accept in the response?", C, "Easy", "Accept", "Content-Type", "Accept-Encoding only", "Vary");
        a.add("Which HTTP header is conventionally used to send authentication credentials or tokens?", C, "Easy", "Authorization", "Authentication", "Auth-Token", "Credentials");
        a.add("Which Content-Type value represents JSON request/response bodies?", C, "Easy", "application/json", "text/json", "application/x-json", "json/text");
        a.add("Which Content-Type value represents XML request/response bodies?", C, "Easy", "application/xml", "text/xml only", "application/xhtml+xml only", "xml/document");
        a.add("Which Content-Type value represents URL-encoded form submissions?", C, "Easy", "application/x-www-form-urlencoded", "multipart/form-data", "application/form", "text/form");
        a.add("Which Content-Type value represents file uploads / multipart forms?", C, "Easy", "multipart/form-data", "application/x-www-form-urlencoded", "application/multipart", "form/multipart");
        a.add("Which character introduces the query string portion of a URL?", C, "Easy", "?", "#", "&", ":");
        a.add("Which character introduces the fragment portion of a URL?", C, "Easy", "#", "?", "&", "/");
        a.add("Which port is the default for HTTP?", C, "Easy", "80", "443", "8080", "8000");
        a.add("Which port is the default for HTTPS?", C, "Easy", "443", "80", "8443", "8000");
        a.add("Which is a popular command-line tool, besides Postman, for testing REST APIs?", C, "Easy", "cURL", "Wireshark only", "Telnet only", "FTP");
        a.add("In JSON, which characters delimit an object?", C, "Easy", "{ and }", "[ and ]", "( and )", "< and >");
        a.add("In JSON, which characters delimit an array?", C, "Easy", "[ and ]", "{ and }", "( and )", "< and >");
        a.add("In JSON, keys (property names) must be quoted using which characters?", C, "Easy", "Double quotes", "Single quotes only", "Backticks", "No quotes required");
        a.add("Which of these is NOT a JSON value type?", C, "Easy", "function", "string", "number", "array");
        a.add("Which character separates path segments in a URL?", C, "Easy", "/", "\\", "|", "-");
        a.add("RESTful API design favors which kind of words in URL paths?", C, "Easy", "Nouns (resources) over verbs (actions)", "Verbs over nouns", "Adjectives only", "Numeric IDs only");
        a.add("Which character set is the standard for JSON content?", C, "Easy", "UTF-8", "UTF-16", "ASCII only", "ISO-8859-1");
        a.add("REST endpoints conventionally return which data format by default in modern APIs?", C, "Easy", "JSON", "XML", "CSV", "YAML");
        a.add("Which HTTP version's status line introduced reason phrases by default?", C, "Easy", "HTTP/1.0 and later", "HTTP/0.9", "HTTP/2 only", "HTTP/3 only");
        a.add("Which HTTP method is generally considered 'safe' (no observable server side effects)?", C, "Easy", "GET (also HEAD, OPTIONS)", "POST", "DELETE", "PUT");
        a.add("Which HTTP status code commonly indicates 'OK' for a successful GET?", C, "Easy", "200", "201", "204", "202");
        a.add("Which HTTP status code commonly indicates a request 'Accepted' for processing later?", C, "Easy", "202", "200", "201", "203");
        a.add("Which HTTP method is widely used to create a new resource on the server?", C, "Easy", "POST", "GET", "PUT only", "OPTIONS");

        // ===== Medium (50) =====
        a.add("Which HTTP response header advises clients on caching policies?", C, "Medium", "Cache-Control", "Pragma only", "Expires only", "ETag");
        a.add("Which request header indicates the origin of a CORS request?", C, "Medium", "Origin", "Referer", "Host", "Sec-Fetch-Site");
        a.add("Which HTTP method is used by browsers for a CORS preflight request?", C, "Medium", "OPTIONS", "GET", "HEAD", "POST");
        a.add("Which CORS response header lists the allowed HTTP methods?", C, "Medium", "Access-Control-Allow-Methods", "Allow-Methods", "Access-Control-Methods", "Cors-Methods");
        a.add("Which CORS response header lists the allowed origin(s)?", C, "Medium", "Access-Control-Allow-Origin", "Allowed-Origins", "Cors-Origin", "X-Allow-Origin");
        a.add("Which CORS response header indicates whether credentials may be sent in cross-origin requests?", C, "Medium", "Access-Control-Allow-Credentials", "Cors-Credentials", "Allow-Credentials", "X-Allow-Credentials");
        a.add("How is a JWT typically sent in a request to authenticate a user?", C, "Medium", "Authorization: Bearer <token>", "Cookie: jwt=<token>", "X-JWT: <token>", "JWT: <token>");
        a.add("Basic HTTP Authentication encodes 'username:password' using which encoding?", C, "Medium", "Base64", "URL-encoding", "Hex", "Base32");
        a.add("Which HTTP/1.1 header keeps the TCP connection open for additional requests?", C, "Medium", "Connection: keep-alive", "Keep-Alive: yes", "Connection: open", "Persistent: true");
        a.add("Which header gives the size of the response body in bytes (for non-streaming responses)?", C, "Medium", "Content-Length", "Length", "Body-Length", "Content-Size");
        a.add("Which HTTP header signals that the body is sent in chunks of unknown total size?", C, "Medium", "Transfer-Encoding: chunked", "Content-Transfer: chunk", "Body-Encoding: stream", "Cache-Control: stream");
        a.add("What is the primary purpose of the ETag response header?", C, "Medium", "Cache validation via opaque resource version identifier", "Compression algorithm selection", "Authentication token storage", "Content language hint");
        a.add("Which conditional request header is paired with ETag for cache validation?", C, "Medium", "If-None-Match", "If-Match-None", "If-Modified-Since", "If-Range");
        a.add("Which conditional request header is paired with Last-Modified for cache validation?", C, "Medium", "If-Modified-Since", "If-Last-Match", "If-None-Match", "If-Updated-Since");
        a.add("Which HTTP status code commonly indicates 'Not Modified' for a cached response?", C, "Medium", "304", "200", "204", "412");
        a.add("Which HTTP 1xx status code is used for 'Continue'?", C, "Medium", "100", "101", "102", "103");
        a.add("Which HTTP status code commonly indicates an unprocessable entity (e.g., validation failure)?", C, "Medium", "422", "400", "409", "412");
        a.add("Which HTTP status code is returned when a client has sent too many requests in a given time?", C, "Medium", "429", "418", "402", "499");
        a.add("Which HTTP status code indicates the HTTP method is not allowed on the resource?", C, "Medium", "405", "404", "415", "406");
        a.add("Which HTTP status code indicates the request body's media type is not supported?", C, "Medium", "415", "406", "405", "400");
        a.add("Which HTTP status code indicates the server cannot produce a response matching the Accept headers?", C, "Medium", "406", "415", "400", "424");
        a.add("Which HTTP response header asks the client to wait before retrying after rate limiting?", C, "Medium", "Retry-After", "X-Retry", "Wait-For", "Throttle-Reset");
        a.add("Which header does the server use to set cookies on the client?", C, "Medium", "Set-Cookie", "Cookie", "Set-Header", "Server-Cookie");
        a.add("Which header does the client use to send cookies back to the server?", C, "Medium", "Cookie", "Set-Cookie", "Client-Cookies", "Cookies");
        a.add("Which standard HTTP methods are considered idempotent?", C, "Medium", "GET, HEAD, PUT, DELETE (and OPTIONS, TRACE)", "GET and POST only", "PUT and POST only", "All methods");
        a.add("In RESTful design, which naming style is recommended for collection endpoints?", C, "Medium", "Plural nouns (e.g., /users)", "Singular nouns (e.g., /user)", "Action verbs (e.g., /getUsers)", "PascalCase tokens");
        a.add("How is API versioning most commonly indicated in URL-based REST APIs?", C, "Medium", "A version segment in the path (e.g., /v1/...)", "A version cookie", "A version body field", "A version of HTTP");
        a.add("In REST, pagination is most often implemented via which mechanism?", C, "Medium", "Query parameters (e.g., page=, size= or offset=, limit=)", "URL fragments", "Body parameters", "Cookies");
        a.add("In REST, filtering of collections is most often implemented via which mechanism?", C, "Medium", "Query parameters", "Path segments only", "Custom verbs only", "Cookies");
        a.add("In REST, the conventional query parameter name for sorting is which?", C, "Medium", "sort", "orderBy only", "filter", "select");
        a.add("Which architectural concept did Roy Fielding define in his 2000 dissertation?", C, "Medium", "REST", "SOAP", "GraphQL", "RPC");
        a.add("Compared to REST, SOAP relies primarily on which message format?", C, "Medium", "XML envelopes (with strict schemas)", "Plain JSON only", "Protocol Buffers", "YAML");
        a.add("Which RPC framework, originally from Google, uses HTTP/2 and Protocol Buffers?", C, "Medium", "gRPC", "JSON-RPC only", "XML-RPC", "Avro RPC");
        a.add("Compared to REST, GraphQL typically exposes how many endpoints per service?", C, "Medium", "A single endpoint that accepts flexible queries", "One per resource type", "One per HTTP method", "One per role");
        a.add("Which is the conventional REST endpoint to fetch a list of users?", C, "Medium", "GET /users", "GET /getUsers", "POST /users/list", "GET /user");
        a.add("Which is the conventional REST endpoint to fetch a single user by id?", C, "Medium", "GET /users/{id}", "GET /user?id={id} only", "POST /users/getById", "GET /user-id/{id}");
        a.add("Which is the conventional REST endpoint to create a user?", C, "Medium", "POST /users", "POST /createUser", "PUT /users/new", "GET /users/create");
        a.add("Which is the conventional REST endpoint to fully update a user?", C, "Medium", "PUT /users/{id}", "POST /users/{id}/update", "PATCH /users/{id} (full)", "POST /users/update?id={id}");
        a.add("Which is the conventional REST endpoint to delete a user?", C, "Medium", "DELETE /users/{id}", "POST /users/{id}/delete", "GET /users/delete?id={id}", "REMOVE /users/{id}");
        a.add("In a URL like /orders/{id}, '{id}' is referred to as which kind of parameter?", C, "Medium", "Path parameter", "Query parameter", "Form parameter", "Header parameter");
        a.add("In a URL like /orders?status=open, 'status=open' is referred to as which kind of parameter?", C, "Medium", "Query parameter", "Path parameter", "Form parameter", "Header parameter");
        a.add("What does the abbreviation DTO commonly stand for in REST API design?", C, "Medium", "Data Transfer Object", "Data Type Object", "Direct Transport Object", "Database Transfer Object");
        a.add("Why is using a DTO usually preferred over exposing JPA entities directly in REST APIs?", C, "Medium", "It decouples the persistence model from the API contract", "DTOs are mandatory in HTTP", "JPA entities cannot be serialized to JSON", "It improves database performance");
        a.add("Which is a common REST anti-pattern?", C, "Medium", "Embedding verbs in URL paths (e.g., /getUser, /createOrder)", "Using HTTP methods (GET/POST/PUT/DELETE) for actions", "Returning JSON responses", "Using HTTPS");
        a.add("The 'X-' prefix on custom HTTP headers was historically used but has been deprecated by which RFC?", C, "Medium", "RFC 6648", "RFC 2616", "RFC 7231", "RFC 9110");
        a.add("Which header carries the user's preferred response language(s)?", C, "Medium", "Accept-Language", "Content-Language", "Lang", "Locale");
        a.add("Which HTTP header is used to enforce HTTPS upgrades for a domain in modern browsers?", C, "Medium", "Strict-Transport-Security (HSTS)", "Upgrade-Insecure-Requests only", "X-HTTPS-Required", "Force-HTTPS");
        a.add("Which header is set by a server to mitigate cross-origin script injection (CSP)?", C, "Medium", "Content-Security-Policy", "X-XSS-Policy", "X-Frame-Options", "Cross-Site-Policy");
        a.add("Which HTTP request header carries the URL of the page that linked to the request?", C, "Medium", "Referer", "Origin", "Source", "Caller");
        a.add("Which response header conveys server-side performance timing back to the client?", C, "Medium", "Server-Timing", "X-Performance", "Timing-Stats", "Server-Stats");

        // ===== Hard (50) =====
        a.add("Roy Fielding's RESTful maturity is often described by the Richardson Maturity Model, which has how many levels?", C, "Hard", "4 levels (0 through 3)", "3 levels", "5 levels", "2 levels");
        a.add("In the Richardson Maturity Model, what is Level 0 commonly called?", C, "Hard", "The Swamp of POX (one URI, one HTTP method)", "Resource-oriented", "HTTP verbs used properly", "Hypermedia controls");
        a.add("In the Richardson Maturity Model, Level 1 introduces what?", C, "Hard", "Multiple resource URIs (still using one HTTP method)", "HATEOAS", "Hypermedia controls", "Single endpoint with all verbs");
        a.add("In the Richardson Maturity Model, Level 2 properly uses what?", C, "Hard", "HTTP verbs and status codes", "Only POST for everything", "Hypermedia links", "Versioning headers");
        a.add("In the Richardson Maturity Model, Level 3 is characterized by what?", C, "Hard", "Hypermedia controls (HATEOAS)", "Pagination support", "Caching support", "Consistent JSON shape");
        a.add("The HTTP CONNECT method is primarily used for what?", C, "Hard", "Tunneling (e.g., setting up TLS through a proxy)", "Service health checks", "Cache validation", "Server-side push");
        a.add("The HTTP TRACE method is used for what (and is often disabled for security)?", C, "Hard", "Loopback request tracing for diagnostics", "Compression negotiation", "Long-polling streaming", "Encrypted tunneling");
        a.add("HTTP/2 introduced which significant performance feature compared to HTTP/1.1?", C, "Hard", "Stream multiplexing over a single TCP connection", "Mandatory TLS 1.3", "Plain text headers always", "End-to-end encryption mandatory");
        a.add("HTTP/3 transports HTTP semantics over which underlying protocol?", C, "Hard", "QUIC (over UDP)", "TCP only", "SCTP", "WebSocket");
        a.add("Which HTTP header enforces HTTPS for future visits to a host?", C, "Hard", "Strict-Transport-Security (HSTS)", "Upgrade-Insecure-Requests", "Force-HTTPS", "X-HTTPS-Only");
        a.add("Which header lets a site declare allowed sources for scripts, styles, etc.?", C, "Hard", "Content-Security-Policy (CSP)", "X-Content-Source", "Allowed-Sources", "Script-Policy");
        a.add("Which header mitigates clickjacking by controlling whether a page can be framed?", C, "Hard", "X-Frame-Options", "Frame-Policy", "X-Frame-Allow", "Allow-Frame");
        a.add("Which header value forbids browsers from MIME-sniffing the response body?", C, "Hard", "X-Content-Type-Options: nosniff", "Content-Sniff: false", "X-MIME-Sniff: off", "MIME-Strict: true");
        a.add("Which (real) HTTP status code is reserved for 'Unavailable For Legal Reasons'?", C, "Hard", "451", "418", "423", "499");
        a.add("Which whimsical HTTP status code is defined by RFC 2324 as 'I'm a Teapot'?", C, "Hard", "418", "417", "421", "419");
        a.add("Which HTTP status code indicates the client must upgrade to a different protocol?", C, "Hard", "426", "428", "421", "405");
        a.add("Which HTTP status code requires the request to include certain preconditions?", C, "Hard", "428", "412", "417", "424");
        a.add("Which HTTP redirect status preserves the original method (vs. 301)?", C, "Hard", "308 Permanent Redirect", "303 See Other", "302 Found", "301 Moved Permanently");
        a.add("Which HTTP redirect status preserves the original method (vs. 302)?", C, "Hard", "307 Temporary Redirect", "303 See Other", "301 Moved Permanently", "308 Permanent Redirect");
        a.add("Which media type is used for an HTTP PATCH that follows JSON Patch (RFC 6902)?", C, "Hard", "application/json-patch+json", "application/merge-patch+json", "application/patch+json", "application/json");
        a.add("Which media type is used for an HTTP PATCH that follows JSON Merge Patch (RFC 7396)?", C, "Hard", "application/merge-patch+json", "application/json-patch+json", "application/merge+json", "application/diff+json");
        a.add("Which RFC defines JSON Patch (a sequence of operations to apply)?", C, "Hard", "RFC 6902", "RFC 7396", "RFC 8259", "RFC 7230");
        a.add("Which RFC defines JSON Merge Patch (a single document representing the desired changes)?", C, "Hard", "RFC 7396", "RFC 6902", "RFC 7320", "RFC 9110");
        a.add("Which OAuth 2.0 grant type is intended for confidential server-to-server clients (no end user)?", C, "Hard", "Client Credentials", "Authorization Code", "Implicit", "Resource Owner Password");
        a.add("Which OAuth 2.0 grant type, with PKCE, is recommended for browser-based and native apps?", C, "Hard", "Authorization Code with PKCE", "Implicit", "Client Credentials", "Resource Owner Password");
        a.add("Which OAuth 2.0 grant has been largely deprecated for native and SPA apps in favor of Authorization Code with PKCE?", C, "Hard", "Implicit Grant", "Client Credentials", "Authorization Code", "Refresh Token");
        a.add("What does the acronym PKCE stand for in OAuth 2.0?", C, "Hard", "Proof Key for Code Exchange", "Public Key Cryptographic Exchange", "Persistent Key Credentialed Exchange", "Public Key Code Encryption");
        a.add("What was the OpenAPI Specification originally called before being donated and renamed?", C, "Hard", "Swagger", "RAML", "API Blueprint", "JSON Schema");
        a.add("Which tool is most commonly associated with 'interactive API documentation' for OpenAPI?", C, "Hard", "Swagger UI", "Postman only", "Insomnia only", "ReDoc only");
        a.add("Which response header conveys an attachment filename for file downloads?", C, "Hard", "Content-Disposition", "Filename", "Attachment", "Download-Name");
        a.add("Which response header instructs caches which request headers should also be considered when keying responses?", C, "Hard", "Vary", "Cache-Vary", "ETag-By", "Vary-On");
        a.add("Which request header (set by browsers) describes the request mode such as 'cors' or 'same-origin'?", C, "Hard", "Sec-Fetch-Mode", "Origin-Mode", "Sec-Mode", "Fetch-Mode");
        a.add("WebDAV extends HTTP with which additional methods for collection/property management?", C, "Hard", "PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK", "GET-COLL, PUT-COLL, MERGE", "READ, WRITE, LIST, MOVE", "CREATE, DROP, ALTER, MOVE");
        a.add("What was the original (pre-1.0) version of the HTTP protocol?", C, "Hard", "HTTP/0.9 (1991)", "HTTP/1.0", "HTTP/0.5", "HTTP/0.1");
        a.add("Which HTTP version first introduced the request-line / response-line / headers structure?", C, "Hard", "HTTP/1.0", "HTTP/0.9", "HTTP/1.1", "HTTP/2");
        a.add("Which HTTP version introduced persistent connections, the Host header, and chunked encoding by default?", C, "Hard", "HTTP/1.1", "HTTP/1.0", "HTTP/2", "HTTP/3");
        a.add("In which year was HTTP/2 first standardized as RFC 7540?", C, "Hard", "2015", "2010", "2018", "2020");
        a.add("Which RFC standardized HTTP/3 in 2022?", C, "Hard", "RFC 9114", "RFC 7540", "RFC 7230", "RFC 9000");
        a.add("Which HTTP status code indicates 'Network Authentication Required'?", C, "Hard", "511", "401", "403", "510");
        a.add("Which Content-Encoding value indicates gzip-compressed bodies?", C, "Hard", "gzip", "deflate", "br", "compress");
        a.add("Which Content-Encoding value indicates Brotli-compressed bodies?", C, "Hard", "br", "brotli", "gzip", "compress");
        a.add("Which transport protocol underlies QUIC, the basis for HTTP/3?", C, "Hard", "UDP", "TCP", "SCTP", "DCCP");
        a.add("Which version of TLS is recommended for the lowest-latency handshake (one round trip in many cases)?", C, "Hard", "TLS 1.3", "TLS 1.2", "TLS 1.1", "SSL 3.0");
        a.add("OAuth 2.1 consolidates OAuth 2.0 best practices and removes which grant type entirely?", C, "Hard", "Implicit Grant (and Resource Owner Password Credentials)", "Client Credentials", "Authorization Code", "Refresh Token");
        a.add("What does the acronym SCIM stand for in identity management?", C, "Hard", "System for Cross-domain Identity Management", "Standard Credential Identity Module", "Single Customer Identity Manager", "Secure Cross Identity Mediator");
        a.add("Which standard provides JSON validation rules for documents (e.g., types, constraints)?", C, "Hard", "JSON Schema", "JSON Patch", "OpenAPI", "AsyncAPI");
        a.add("Which standard supersedes Swagger 2.0 with new features like JSON Schema 2020-12 alignment (long term)?", C, "Hard", "OpenAPI 3.x", "Swagger 1", "Postman Collections", "RAML 2");
        a.add("Which response header advertises which content types are acceptable for a PATCH request to the resource?", C, "Hard", "Accept-Patch", "Patch-Types", "Accept-Methods", "Accept-Format");
        a.add("Which HTTP status code is commonly used by Nginx (non-standard) when the client closes the connection before the server responds?", C, "Hard", "499", "504", "408", "419");
        a.add("Which header signals the desired protocol upgrade (e.g., from HTTP/1.1 to WebSocket)?", C, "Hard", "Upgrade", "Switch-Protocol", "Protocol-Upgrade", "Sec-Upgrade");
    }
}
