package com.quiz.config.seeds;

public final class ScienceSeeder {
    private static final String C = "Science";
    private ScienceSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("What is the chemical symbol for Silver?", C, "Easy", "Ag", "Si", "Sv", "Au");
        a.add("What is the chemical symbol for Iron?", C, "Easy", "Fe", "Ir", "In", "Fr");
        a.add("What is the chemical symbol for Sodium?", C, "Easy", "Na", "So", "Sd", "Si");
        a.add("What is the chemical symbol for Potassium?", C, "Easy", "K", "Po", "Pt", "P");
        a.add("What is the chemical symbol for Carbon?", C, "Easy", "C", "Ca", "Co", "Cn");
        a.add("What is the chemical symbol for Oxygen?", C, "Easy", "O", "Ox", "On", "Og");
        a.add("What is the chemical symbol for Nitrogen?", C, "Easy", "N", "Ni", "Nt", "No");
        a.add("What is the chemical symbol for Hydrogen?", C, "Easy", "H", "Hy", "He", "Hd");
        a.add("What is the chemical symbol for Helium?", C, "Easy", "He", "H", "Hl", "Hm");
        a.add("What is the chemical symbol for Calcium?", C, "Easy", "Ca", "Cl", "C", "Cm");
        a.add("How many planets are in our solar system (excluding dwarf planets)?", C, "Easy", "8", "9", "7", "10");
        a.add("Which fundamental force pulls objects toward the Earth?", C, "Easy", "Gravity", "Magnetism", "Friction", "Electricity");
        a.add("To which class of animals do humans belong?", C, "Easy", "Mammals", "Reptiles", "Birds", "Amphibians");
        a.add("What is the central part of an atom called?", C, "Easy", "Nucleus", "Electron", "Proton", "Neutron");
        a.add("What is considered the smallest functional unit of life?", C, "Easy", "Cell", "Atom", "Tissue", "Organ");
        a.add("Which process do plants use to make food using sunlight?", C, "Easy", "Photosynthesis", "Respiration", "Digestion", "Transpiration");
        a.add("Which pigment gives most plants their green color?", C, "Easy", "Chlorophyll", "Hemoglobin", "Melanin", "Carotene");
        a.add("Approximately how many bones are in the adult human body?", C, "Easy", "206", "186", "226", "246");
        a.add("Which star is at the center of our solar system?", C, "Easy", "Sun", "Polaris", "Sirius", "Alpha Centauri");
        a.add("Which organ pumps blood through the human body?", C, "Easy", "Heart", "Liver", "Kidney", "Brain");
        a.add("Which organs do humans use to breathe air?", C, "Easy", "Lungs", "Liver", "Stomach", "Kidneys");
        a.add("What is the solid form of water called?", C, "Easy", "Ice", "Steam", "Vapor", "Snow only");
        a.add("What is the natural satellite of the Earth called?", C, "Easy", "Moon", "Mars", "Sun", "Venus");
        a.add("What is the name of the galaxy that contains our solar system?", C, "Easy", "Milky Way", "Andromeda", "Triangulum", "Whirlpool");
        a.add("Which gas is the most abundant in Earth's atmosphere by volume?", C, "Easy", "Nitrogen", "Oxygen", "Carbon Dioxide", "Argon");
        a.add("What is the largest organ of the human body?", C, "Easy", "Skin", "Liver", "Brain", "Heart");
        a.add("Which temperature scale is most commonly used worldwide for everyday weather?", C, "Easy", "Celsius", "Fahrenheit", "Kelvin", "Rankine");
        a.add("What is the energy received from the Sun called?", C, "Easy", "Solar energy", "Wind energy", "Geothermal energy", "Tidal energy");
        a.add("Which force opposes motion between two contacting surfaces?", C, "Easy", "Friction", "Gravity", "Magnetism", "Tension");
        a.add("Which large bird lays the largest egg?", C, "Easy", "Ostrich", "Eagle", "Swan", "Albatross");
        a.add("Which branch of science studies living things?", C, "Easy", "Biology", "Chemistry", "Physics", "Geology");
        a.add("Which branch of science studies matter and its changes?", C, "Easy", "Chemistry", "Biology", "Physics", "Astronomy");
        a.add("Which branch of science studies motion, energy, and forces?", C, "Easy", "Physics", "Chemistry", "Biology", "Geology");
        a.add("How many magnetic poles does an ordinary bar magnet have?", C, "Easy", "2", "1", "3", "4");
        a.add("Which form of carbon is commonly used in pencil 'lead'?", C, "Easy", "Graphite", "Diamond", "Coal", "Charcoal");
        a.add("Which process turns a liquid into a gas?", C, "Easy", "Evaporation", "Condensation", "Sublimation", "Freezing");
        a.add("Which process turns a gas into a liquid?", C, "Easy", "Condensation", "Evaporation", "Melting", "Freezing");
        a.add("Which process turns a solid into a liquid?", C, "Easy", "Melting", "Freezing", "Boiling", "Condensation");
        a.add("Which process turns a liquid into a solid?", C, "Easy", "Freezing", "Melting", "Evaporation", "Condensation");
        a.add("Which is the most abundant chemical element in the universe?", C, "Easy", "Hydrogen", "Helium", "Oxygen", "Carbon");
        a.add("Which optical instrument is used to see very small objects?", C, "Easy", "Microscope", "Telescope", "Periscope", "Stethoscope");
        a.add("Which optical instrument is used to see very distant objects?", C, "Easy", "Telescope", "Microscope", "Periscope", "Binoculars only");
        a.add("Which simple machine is a flat surface with a slope?", C, "Easy", "Inclined plane", "Lever", "Pulley", "Wheel");
        a.add("Which simple machine has two circular ends connected by a rod?", C, "Easy", "Wheel and axle", "Lever", "Pulley", "Wedge");
        a.add("What is the brightest object in Earth's daytime sky?", C, "Easy", "Sun", "Moon", "Venus", "Sirius");
        a.add("Which gas do humans exhale in large amounts?", C, "Easy", "Carbon Dioxide", "Oxygen", "Hydrogen", "Helium");
        a.add("Which gas do humans need to breathe in to survive?", C, "Easy", "Oxygen", "Nitrogen", "Carbon Dioxide", "Helium");
        a.add("Which sense organ is responsible for hearing in humans?", C, "Easy", "Ears", "Nose", "Eyes", "Tongue");
        a.add("Which sense organ is responsible for taste in humans?", C, "Easy", "Tongue", "Nose", "Ears", "Skin");
        a.add("Which sense organ is responsible for smell in humans?", C, "Easy", "Nose", "Tongue", "Ears", "Eyes");

        // ===== Medium (50) =====
        a.add("What is the atomic number of Carbon?", C, "Medium", "6", "12", "8", "14");
        a.add("What is the atomic number of Oxygen?", C, "Medium", "8", "6", "16", "10");
        a.add("What is the atomic number of Iron?", C, "Medium", "26", "16", "36", "56");
        a.add("How many permanent teeth does a typical adult human have?", C, "Medium", "32", "28", "30", "34");
        a.add("How many chambers does the human heart have?", C, "Medium", "4", "2", "3", "5");
        a.add("Which is the longest bone in the human body?", C, "Medium", "Femur", "Tibia", "Humerus", "Fibula");
        a.add("Which animal has the longest known gestation period among mammals?", C, "Medium", "Elephant", "Whale", "Giraffe", "Rhinoceros");
        a.add("Which blood type is considered the universal red cell donor?", C, "Medium", "O negative", "O positive", "AB positive", "A positive");
        a.add("Which blood type is considered the universal red cell recipient?", C, "Medium", "AB positive", "O negative", "AB negative", "O positive");
        a.add("Which is the lightest known chemical element?", C, "Medium", "Hydrogen", "Helium", "Lithium", "Carbon");
        a.add("Which vitamin is produced by the skin when exposed to sunlight?", C, "Medium", "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K");
        a.add("Approximately what is the pH of human stomach acid?", C, "Medium", "2", "7", "9", "5");
        a.add("Approximately what is the acceleration due to gravity on Earth's surface?", C, "Medium", "9.8 m/s^2", "98 m/s^2", "0.98 m/s^2", "1.0 m/s^2");
        a.add("Which instrument is used to measure temperature?", C, "Medium", "Thermometer", "Barometer", "Hygrometer", "Anemometer");
        a.add("Which instrument is used to measure atmospheric pressure?", C, "Medium", "Barometer", "Thermometer", "Voltmeter", "Spectrometer");
        a.add("Which instrument is used to detect and record earthquakes?", C, "Medium", "Seismograph", "Hygrometer", "Tachometer", "Periscope");
        a.add("Which subatomic particle orbits the nucleus of an atom?", C, "Medium", "Electron", "Proton", "Neutron", "Photon");
        a.add("Which subatomic particle inside the nucleus carries a positive charge?", C, "Medium", "Proton", "Electron", "Neutron", "Positron");
        a.add("Which biological process releases water vapor from plant leaves?", C, "Medium", "Transpiration", "Photosynthesis", "Respiration", "Germination");
        a.add("Which molecule is often called the 'energy currency' of the cell?", C, "Medium", "ATP", "DNA", "RNA", "Glucose");
        a.add("Which is the basic hereditary unit passed from parent to offspring?", C, "Medium", "Gene", "Cell", "Protein", "Enzyme");
        a.add("Which branch of biology studies fungi?", C, "Medium", "Mycology", "Botany", "Zoology", "Ecology");
        a.add("Which type of cell division produces two genetically identical daughter cells?", C, "Medium", "Mitosis", "Meiosis", "Binary fission", "Conjugation");
        a.add("Which type of cell division produces gametes (sperm and egg)?", C, "Medium", "Meiosis", "Mitosis", "Cytokinesis", "Replication");
        a.add("Which type of lens converges parallel light rays to a focal point?", C, "Medium", "Convex lens", "Concave lens", "Cylindrical lens", "Plano lens");
        a.add("Which type of lens spreads parallel light rays apart?", C, "Medium", "Concave lens", "Convex lens", "Spherical lens", "Toric lens");
        a.add("Which type of chemical bond involves the sharing of electron pairs?", C, "Medium", "Covalent bond", "Ionic bond", "Metallic bond", "Hydrogen bond");
        a.add("Which type of chemical bond involves the transfer of electrons between atoms?", C, "Medium", "Ionic bond", "Covalent bond", "Metallic bond", "Van der Waals bond");
        a.add("What is the SI unit of electric current?", C, "Medium", "Ampere", "Volt", "Watt", "Coulomb");
        a.add("What is the SI unit of voltage?", C, "Medium", "Volt", "Ampere", "Ohm", "Watt");
        a.add("What is the SI unit of power?", C, "Medium", "Watt", "Joule", "Newton", "Pascal");
        a.add("What is the SI unit of energy?", C, "Medium", "Joule", "Watt", "Newton", "Pascal");
        a.add("What is the SI unit of frequency?", C, "Medium", "Hertz", "Watt", "Joule", "Decibel");
        a.add("Which group of animals breathes through gills throughout life?", C, "Medium", "Fish", "Reptiles", "Birds", "Mammals");
        a.add("What is a recognizable group of stars forming a pattern in the sky called?", C, "Medium", "Constellation", "Galaxy", "Nebula", "Cluster");
        a.add("What is the smallest unit of an element that retains its chemical properties?", C, "Medium", "Atom", "Molecule", "Ion", "Proton");
        a.add("Which layer of Earth's atmosphere is closest to the surface and contains weather?", C, "Medium", "Troposphere", "Stratosphere", "Mesosphere", "Thermosphere");
        a.add("Which layer of Earth's atmosphere contains most of the ozone layer?", C, "Medium", "Stratosphere", "Troposphere", "Mesosphere", "Exosphere");
        a.add("Which alkali metal is widely used in rechargeable batteries?", C, "Medium", "Lithium", "Sodium", "Potassium", "Calcium");
        a.add("Which element has the chemical symbol Pb?", C, "Medium", "Lead", "Phosphorus", "Platinum", "Palladium");
        a.add("What is the chemical formula for ozone?", C, "Medium", "O3", "O2", "OZ", "H2O2");
        a.add("Which planet is the smallest in our solar system?", C, "Medium", "Mercury", "Mars", "Pluto", "Venus");
        a.add("Which planet has prominent visible rings made primarily of ice and rock?", C, "Medium", "Saturn", "Jupiter", "Neptune", "Uranus");
        a.add("Which scientific term refers to an animal that eats only plants?", C, "Medium", "Herbivore", "Carnivore", "Omnivore", "Detritivore");
        a.add("Which scientific term refers to an animal that eats only meat?", C, "Medium", "Carnivore", "Herbivore", "Omnivore", "Insectivore");
        a.add("Which scientific term refers to an animal that eats both plants and meat?", C, "Medium", "Omnivore", "Herbivore", "Carnivore", "Detritivore");
        a.add("What is the name of the boundary around a black hole beyond which light cannot escape?", C, "Medium", "Event Horizon", "Photon Sphere", "Singularity", "Accretion Disk");
        a.add("What term describes a substance that speeds up a chemical reaction without being consumed?", C, "Medium", "Catalyst", "Inhibitor", "Reagent", "Solvent");
        a.add("Which gas is required for combustion to occur?", C, "Medium", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen");
        a.add("What does DNA stand for?", C, "Medium", "Deoxyribonucleic Acid", "Dinitric Acid", "Dinucleic Allele", "Deoxyribose Nitric Acid");

        // ===== Hard (50) =====
        a.add("Who formulated the three classical laws of motion?", C, "Hard", "Isaac Newton", "Galileo Galilei", "Albert Einstein", "Johannes Kepler");
        a.add("Who formulated the famous mass-energy equivalence equation E=mc^2?", C, "Hard", "Albert Einstein", "Isaac Newton", "Niels Bohr", "Max Planck");
        a.add("Which two scientists shared credit for proposing the double-helix structure of DNA?", C, "Hard", "Watson and Crick", "Pasteur and Koch", "Mendel and Morgan", "Curie and Becquerel");
        a.add("What is the approximate half-life of carbon-14, used in radiocarbon dating?", C, "Hard", "5,730 years", "1,000 years", "100,000 years", "50 years");
        a.add("Which is the most abundant element by mass in Earth's crust?", C, "Hard", "Oxygen", "Silicon", "Iron", "Aluminum");
        a.add("Which fundamental particle is the carrier (mediator) of the electromagnetic force?", C, "Hard", "Photon", "Gluon", "W boson", "Higgs boson");
        a.add("Which theory describes gravity as the curvature of spacetime by mass and energy?", C, "Hard", "General Relativity", "Special Relativity", "Quantum Mechanics", "String Theory");
        a.add("Who proposed the theory of evolution by natural selection in 'On the Origin of Species'?", C, "Hard", "Charles Darwin", "Alfred Wallace", "Gregor Mendel", "Jean-Baptiste Lamarck");
        a.add("What is the SI unit of magnetic flux?", C, "Hard", "Weber", "Tesla", "Henry", "Gauss");
        a.add("What is the SI unit of inductance?", C, "Hard", "Henry", "Farad", "Tesla", "Ohm");
        a.add("What is the SI unit of pressure?", C, "Hard", "Pascal", "Bar", "Torr", "Atmosphere");
        a.add("Which physicist is famously associated with the Uncertainty Principle?", C, "Hard", "Werner Heisenberg", "Erwin Schrodinger", "Niels Bohr", "Paul Dirac");
        a.add("Which Russian chemist is credited with formulating the original periodic table?", C, "Hard", "Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Henry Moseley");
        a.add("Which fundamental particle mediates the strong nuclear force inside the nucleus?", C, "Hard", "Gluon", "Photon", "Graviton", "Neutrino");
        a.add("Which type of bosons mediate the weak nuclear force?", C, "Hard", "W and Z bosons", "Higgs boson", "Gluons", "Photons");
        a.add("Which French physicist is credited with discovering radioactivity in 1896?", C, "Hard", "Henri Becquerel", "Marie Curie", "Pierre Curie", "Ernest Rutherford");
        a.add("Which metal has the highest melting point of all pure metals?", C, "Hard", "Tungsten", "Iron", "Platinum", "Titanium");
        a.add("Which is widely considered the first fully synthetic plastic?", C, "Hard", "Bakelite", "Polyethylene", "Nylon", "PVC");
        a.add("Who first described the wavelength shift now known as the Doppler effect?", C, "Hard", "Christian Doppler", "Heinrich Hertz", "Hendrik Lorentz", "Edward Morley");
        a.add("Which type of electromagnetic radiation has the highest frequency?", C, "Hard", "Gamma rays", "X-rays", "Ultraviolet", "Microwaves");
        a.add("What is the chemical formula for table salt?", C, "Hard", "NaCl", "KCl", "NaBr", "CaCl2");
        a.add("What is the chemical formula for sulfuric acid?", C, "Hard", "H2SO4", "HNO3", "HCl", "H2CO3");
        a.add("What is the chemical formula for nitric acid?", C, "Hard", "HNO3", "H2SO4", "HClO4", "HCN");
        a.add("What is the chemical formula for ammonia?", C, "Hard", "NH3", "NH4", "N2H4", "NaOH");
        a.add("What is the chemical formula for methane?", C, "Hard", "CH4", "C2H6", "CH2", "C2H4");
        a.add("What is the chemical formula for ethanol?", C, "Hard", "C2H5OH", "CH3OH", "C3H7OH", "CH3COOH");
        a.add("What is the chemical formula for glucose?", C, "Hard", "C6H12O6", "C12H22O11", "C5H10O5", "C2H4O2");
        a.add("Which Danish astronomer first measured the speed of light using observations of Jupiter's moons?", C, "Hard", "Ole Romer", "Tycho Brahe", "Johannes Kepler", "Christiaan Huygens");
        a.add("Which element has atomic number 92?", C, "Hard", "Uranium", "Plutonium", "Thorium", "Radium");
        a.add("Which element has atomic number 79?", C, "Hard", "Gold", "Silver", "Platinum", "Mercury");
        a.add("Which element has atomic number 47?", C, "Hard", "Silver", "Gold", "Copper", "Cobalt");
        a.add("Which celestial body was reclassified from a planet to a dwarf planet in 2006?", C, "Hard", "Pluto", "Ceres", "Eris", "Haumea");
        a.add("Which moon of Jupiter is the largest moon in the entire solar system?", C, "Hard", "Ganymede", "Europa", "Io", "Callisto");
        a.add("Which is the largest moon of Saturn?", C, "Hard", "Titan", "Rhea", "Iapetus", "Enceladus");
        a.add("Which gas dominates the atmosphere of Venus?", C, "Hard", "Carbon Dioxide", "Nitrogen", "Methane", "Oxygen");
        a.add("Which planet has the highest average surface temperature in our solar system?", C, "Hard", "Venus", "Mercury", "Mars", "Jupiter");
        a.add("Which American medical researcher developed the first effective polio vaccine?", C, "Hard", "Jonas Salk", "Albert Sabin", "Edward Jenner", "Louis Pasteur");
        a.add("The Krebs cycle in cellular respiration is also known by which name?", C, "Hard", "Citric Acid Cycle", "Calvin Cycle", "Glycolysis", "Electron Transport Chain");
        a.add("Dolly, born in 1996, was famously the first cloned mammal of which species?", C, "Hard", "Sheep", "Cow", "Goat", "Mouse");
        a.add("Which two photoreceptor cell types are found in the human retina?", C, "Hard", "Rods and cones", "Axons and dendrites", "Alpha and beta cells", "Glia and neurons");
        a.add("Which French chemist is often called the 'father of modern chemistry'?", C, "Hard", "Antoine Lavoisier", "Joseph Priestley", "Robert Boyle", "John Dalton");
        a.add("Which isotope is the standard reference for atomic mass units?", C, "Hard", "Carbon-12", "Hydrogen-1", "Oxygen-16", "Uranium-235");
        a.add("Which optical phenomenon causes light to bend when entering a different medium?", C, "Hard", "Refraction", "Reflection", "Diffraction", "Polarization");
        a.add("Which physicist is regarded as the father of quantum theory?", C, "Hard", "Max Planck", "Albert Einstein", "Niels Bohr", "Werner Heisenberg");
        a.add("Which Austrian physicist proposed the famous 'cat' thought experiment in quantum mechanics?", C, "Hard", "Erwin Schrodinger", "Wolfgang Pauli", "Max Born", "Eugene Wigner");
        a.add("What is the name of the single-celled organisms that lack a nucleus?", C, "Hard", "Prokaryotes", "Eukaryotes", "Protists", "Fungi");
        a.add("Which constant approximately equals 6.022 x 10^23 and counts entities per mole?", C, "Hard", "Avogadro's number", "Planck's constant", "Boltzmann's constant", "Faraday constant");
        a.add("Which physicist proposed that electrons in atoms occupy quantized energy levels?", C, "Hard", "Niels Bohr", "Ernest Rutherford", "J.J. Thomson", "James Maxwell");
        a.add("Which biologist is considered the father of modern genetics?", C, "Hard", "Gregor Mendel", "Charles Darwin", "Thomas Morgan", "Francis Crick");
        a.add("What is the name for the boundary at which a fluid changes from laminar to turbulent flow, characterized by the Reynolds number?", C, "Hard", "Critical Reynolds number", "Mach number", "Froude number", "Strouhal number");
    }
}
