package com.quiz.config.seeds;

public final class SportsSeeder {
    private static final String C = "Sports";
    private SportsSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which sport is played at the Wimbledon championships?", C, "Easy", "Tennis", "Cricket", "Rugby", "Squash");
        a.add("Which sport is played at The Masters tournament held annually in Augusta?", C, "Easy", "Golf", "Tennis", "Polo", "Croquet");
        a.add("Which sport is associated with the Tour de France?", C, "Easy", "Cycling", "Marathon running", "Motor racing", "Sailing");
        a.add("Which sport awards the Stanley Cup as its championship trophy?", C, "Easy", "Ice Hockey", "Lacrosse", "Field Hockey", "Curling");
        a.add("Which sport awards the Super Bowl as its championship game?", C, "Easy", "American Football", "Baseball", "Basketball", "Hockey");
        a.add("Which sport awards the World Series as its championship?", C, "Easy", "Baseball", "American Football", "Basketball", "Hockey");
        a.add("Which sport awards the Rugby World Cup?", C, "Easy", "Rugby Union", "Cricket", "American Football", "Soccer");
        a.add("Which sport uses a shuttlecock?", C, "Easy", "Badminton", "Tennis", "Squash", "Pickleball");
        a.add("Which sport uses a hard rubber puck?", C, "Easy", "Ice Hockey", "Field Hockey", "Lacrosse", "Curling");
        a.add("Which sport uses weapons called foil, epee and sabre?", C, "Easy", "Fencing", "Archery", "Kendo", "Boxing");
        a.add("Which Olympic sport involves lifting weights overhead?", C, "Easy", "Weightlifting", "Wrestling", "Judo", "Boxing");
        a.add("How many holes are on a standard regulation golf course?", C, "Easy", "18", "9", "12", "20");
        a.add("How many players are on a baseball team's defensive lineup on the field?", C, "Easy", "9", "10", "11", "8");
        a.add("How many players make up a standard cricket team?", C, "Easy", "11", "9", "10", "12");
        a.add("How many skaters play for one team on the ice in standard ice hockey?", C, "Easy", "6", "5", "7", "8");
        a.add("How many innings are in a standard MLB baseball game?", C, "Easy", "9", "7", "10", "11");
        a.add("How long is the regulation playing time of a standard soccer (football) match?", C, "Easy", "90 minutes", "80 minutes", "100 minutes", "60 minutes");
        a.add("How long is each quarter in an NBA game?", C, "Easy", "12 minutes", "10 minutes", "15 minutes", "20 minutes");
        a.add("Which is widely considered the most popular sport in the world by audience?", C, "Easy", "Soccer (Association Football)", "Cricket", "Basketball", "Baseball");
        a.add("How often are the Summer Olympic Games held?", C, "Easy", "Every 4 years", "Every 2 years", "Every 5 years", "Every year");
        a.add("Which sport features 'strikes' and 'spares' as scoring terms?", C, "Easy", "Bowling", "Baseball", "Cricket", "Pool");
        a.add("Which sport is credited as being invented by James Naismith in 1891?", C, "Easy", "Basketball", "Volleyball", "Lacrosse", "Hockey");
        a.add("Which sport originated in Scotland and is most associated with St Andrews?", C, "Easy", "Golf", "Curling", "Rugby", "Polo");
        a.add("In which country did the sport of Sumo wrestling originate?", C, "Easy", "Japan", "China", "South Korea", "Mongolia");
        a.add("In which country did the martial art Taekwondo originate?", C, "Easy", "South Korea", "Japan", "China", "Vietnam");
        a.add("In which country did the martial art Karate originate?", C, "Easy", "Japan", "China", "Korea", "Thailand");
        a.add("In which sport do you 'spike' the ball over a net?", C, "Easy", "Volleyball", "Tennis", "Badminton", "Basketball");
        a.add("In which sport do you 'tee off' to start play on each hole?", C, "Easy", "Golf", "Cricket", "Hockey", "Polo");
        a.add("In which sport do you 'ace' your opponent with an unreturnable serve?", C, "Easy", "Tennis", "Cricket", "Bowling", "Golf");
        a.add("In which sport do you 'score a try' for points?", C, "Easy", "Rugby", "Soccer", "Hockey", "Lacrosse");
        a.add("In which sport do you 'hit a six'?", C, "Easy", "Cricket", "Baseball", "Softball", "Tennis");
        a.add("In which sport do you 'hit a home run'?", C, "Easy", "Baseball", "Cricket", "Softball only", "Rugby");
        a.add("In which sport do you 'shoot a basket' for points?", C, "Easy", "Basketball", "Netball", "Handball", "Polo");
        a.add("Cricket as a sport originated in which country?", C, "Easy", "England", "Australia", "India", "South Africa");
        a.add("Modern baseball is most associated with which country's professional leagues?", C, "Easy", "United States", "Cuba", "Japan", "Dominican Republic");
        a.add("The sport of rugby originated in which country?", C, "Easy", "England", "France", "Wales", "Scotland");
        a.add("American football evolved primarily in which country?", C, "Easy", "United States", "Canada", "United Kingdom", "Australia");
        a.add("The sport of table tennis originated in which country?", C, "Easy", "England", "China", "Japan", "Germany");
        a.add("Modern lawn tennis was first codified in which country?", C, "Easy", "England", "France", "United States", "Australia");
        a.add("Which three medals are awarded for first, second and third place at the Olympics?", C, "Easy", "Gold, Silver, Bronze", "Gold, Silver, Copper", "Platinum, Gold, Silver", "Gold, Bronze, Iron");
        a.add("In which sport is a fight held inside a 'ring'?", C, "Easy", "Boxing", "Wrestling", "MMA only", "Fencing");
        a.add("Which winter Olympic sport combines cross-country skiing with rifle shooting?", C, "Easy", "Biathlon", "Triathlon", "Ski Cross", "Skeleton");
        a.add("In soccer, which colored card indicates a player has been sent off?", C, "Easy", "Red", "Yellow", "Blue", "Black");
        a.add("In soccer, which colored card is shown as a formal warning to a player?", C, "Easy", "Yellow", "Red", "Green", "Black");
        a.add("How many bases are there on a baseball diamond, including home plate?", C, "Easy", "4", "3", "5", "2");
        a.add("Which sport is played on a 'pitch' between two teams of 11, with bowlers and batters?", C, "Easy", "Cricket", "Baseball", "Rounders", "Softball");
        a.add("Which sport features the 'Tour de France' as its premier road event?", C, "Easy", "Cycling", "Marathon", "Triathlon", "Auto racing");
        a.add("Which sport awards the Vince Lombardi Trophy?", C, "Easy", "American Football (NFL)", "Basketball (NBA)", "Baseball (MLB)", "Hockey (NHL)");
        a.add("Which sport awards the Larry O'Brien Trophy as its championship?", C, "Easy", "NBA Basketball", "NFL Football", "MLB Baseball", "NHL Hockey");
        a.add("In which sport are the terms 'birdie' and 'eagle' used?", C, "Easy", "Golf", "Cricket", "Bowling", "Archery");

        // ===== Medium (50) =====
        a.add("How many Grand Slam tournaments are held in tennis each year?", C, "Medium", "4", "3", "5", "6");
        a.add("Which tennis Grand Slam is played on grass courts?", C, "Medium", "Wimbledon", "French Open", "US Open", "Australian Open");
        a.add("Which tennis Grand Slam is played on clay courts?", C, "Medium", "French Open", "Wimbledon", "US Open", "Australian Open");
        a.add("Which tennis Grand Slam is held first in the calendar year?", C, "Medium", "Australian Open", "French Open", "Wimbledon", "US Open");
        a.add("Which tennis Grand Slam is held in New York?", C, "Medium", "US Open", "French Open", "Wimbledon", "Australian Open");
        a.add("Which country has won the most FIFA World Cup tournaments in men's football?", C, "Medium", "Brazil", "Germany", "Italy", "Argentina");
        a.add("How many FIFA World Cups have Brazil won?", C, "Medium", "5", "4", "3", "6");
        a.add("How many FIFA World Cups have Germany won?", C, "Medium", "4", "3", "5", "2");
        a.add("Which country hosted the 2010 FIFA World Cup?", C, "Medium", "South Africa", "Germany", "Brazil", "Russia");
        a.add("Which country hosted the 2014 FIFA World Cup?", C, "Medium", "Brazil", "South Africa", "Germany", "Russia");
        a.add("Which country hosted the 2022 FIFA World Cup?", C, "Medium", "Qatar", "Russia", "Brazil", "South Africa");
        a.add("Which three countries are co-hosts of the 2026 FIFA World Cup?", C, "Medium", "USA, Canada, Mexico", "USA, UK, Mexico", "Brazil, USA, Argentina", "Mexico, Spain, USA");
        a.add("How long is each quarter of an NFL American football game?", C, "Medium", "15 minutes", "12 minutes", "20 minutes", "10 minutes");
        a.add("How many players are on each team on the field in American football?", C, "Medium", "11", "12", "10", "9");
        a.add("How many players are on each team in a Rugby Union match?", C, "Medium", "15", "13", "11", "7");
        a.add("How many players are on each team in netball?", C, "Medium", "7", "5", "6", "11");
        a.add("Which auto race is held annually as the 'Indianapolis 500'?", C, "Medium", "IndyCar Series race", "NASCAR Cup race", "Formula 1 race", "Le Mans-style race");
        a.add("Which sport is featured in the 'Daytona 500'?", C, "Medium", "NASCAR Auto Racing", "IndyCar Auto Racing", "Formula 1", "Sportscar Endurance");
        a.add("The cricket Test series called 'The Ashes' is contested between which two countries?", C, "Medium", "England and Australia", "India and Pakistan", "South Africa and Zimbabwe", "Australia and India");
        a.add("Tiger Woods is a famous professional in which sport?", C, "Medium", "Golf", "Tennis", "Baseball", "Squash");
        a.add("Roger Federer is a famous professional in which sport?", C, "Medium", "Tennis", "Squash", "Badminton", "Table Tennis");
        a.add("LeBron James is a famous professional in which sport?", C, "Medium", "Basketball", "Football", "Baseball", "Hockey");
        a.add("Lionel Messi is a famous professional in which sport?", C, "Medium", "Soccer (Football)", "Basketball", "Tennis", "Polo");
        a.add("Tom Brady was a famous professional in which sport?", C, "Medium", "American Football", "Baseball", "Basketball", "Soccer");
        a.add("Wayne Gretzky is a famous professional in which sport?", C, "Medium", "Ice Hockey", "Lacrosse", "Curling", "Figure Skating");
        a.add("Babe Ruth was a famous professional in which sport?", C, "Medium", "Baseball", "Basketball", "American Football", "Boxing");
        a.add("In golf, what is the term for completing a hole one stroke under par?", C, "Medium", "Birdie", "Eagle", "Bogey", "Albatross");
        a.add("In golf, what is the term for completing a hole two strokes under par?", C, "Medium", "Eagle", "Birdie", "Albatross", "Hole-in-one");
        a.add("In golf, what is the term for completing a hole three strokes under par?", C, "Medium", "Albatross", "Eagle", "Condor", "Birdie");
        a.add("In golf, what is the term for completing a hole one stroke over par?", C, "Medium", "Bogey", "Double Bogey", "Birdie", "Eagle");
        a.add("In bowling, what term is used for knocking down all 10 pins on the first ball?", C, "Medium", "Strike", "Spare", "Turkey", "Open frame");
        a.add("In bowling, what is it called when you knock down all 10 pins using two balls in one frame?", C, "Medium", "Spare", "Strike", "Split", "Turkey");
        a.add("In bowling, what slang term is used for three consecutive strikes?", C, "Medium", "Turkey", "Spare", "Hat trick", "Streak");
        a.add("In which year was the very first FIFA World Cup held?", C, "Medium", "1930", "1928", "1934", "1924");
        a.add("Which country hosted (and won) the first FIFA World Cup?", C, "Medium", "Uruguay", "Italy", "Brazil", "Argentina");
        a.add("Which traditional Latin Olympic motto translates as 'Faster, Higher, Stronger'?", C, "Medium", "Citius, Altius, Fortius", "Veni, Vidi, Vici", "Carpe Diem", "Semper Fidelis");
        a.add("Pele, widely considered one of football's greatest, played for which country?", C, "Medium", "Brazil", "Argentina", "Portugal", "Uruguay");
        a.add("Diego Maradona, the football legend, played for which national team?", C, "Medium", "Argentina", "Brazil", "Italy", "Uruguay");
        a.add("In MLB, which team is named the 'Yankees'?", C, "Medium", "New York Yankees", "Chicago Yankees", "Boston Yankees", "Los Angeles Yankees");
        a.add("Which country has Cristiano Ronaldo represented in international football?", C, "Medium", "Portugal", "Spain", "Brazil", "Argentina");
        a.add("Which sport is played at the Cheltenham Festival in the UK?", C, "Medium", "Horse Racing", "Greyhound Racing", "Polo", "Cricket");
        a.add("In Formula 1, which trophy is awarded to the season's top driver?", C, "Medium", "Drivers' Championship", "Manufacturers' Cup", "FIA Trophy", "Monaco Cup");
        a.add("Which event is the most prestigious endurance sportscar race held in France?", C, "Medium", "24 Hours of Le Mans", "12 Hours of Sebring", "Daytona 24", "Spa 24 Hours");
        a.add("Which annual cycling stage race is the most prestigious in Italy?", C, "Medium", "Giro d'Italia", "Tour de France", "Vuelta a Espana", "Milan-San Remo");
        a.add("Which annual cycling stage race is the most prestigious in Spain?", C, "Medium", "Vuelta a Espana", "Giro d'Italia", "Tour de France", "Volta a Catalunya");
        a.add("In tennis, what is the score called when a game is tied at 40-40?", C, "Medium", "Deuce", "Advantage", "Tiebreak", "Match point");
        a.add("In which sport is the term 'butterfly stroke' used?", C, "Medium", "Swimming", "Boxing", "Karate", "Gymnastics");
        a.add("Which Premier League football club plays its home games at Old Trafford?", C, "Medium", "Manchester United", "Manchester City", "Liverpool", "Arsenal");
        a.add("Which English football club plays its home games at Anfield?", C, "Medium", "Liverpool", "Everton", "Newcastle", "Aston Villa");
        a.add("Real Madrid plays its home games at which stadium?", C, "Medium", "Santiago Bernabeu", "Camp Nou", "Mestalla", "Wanda Metropolitano");

        // ===== Hard (50) =====
        a.add("In which year was the very first Wimbledon Championship held?", C, "Hard", "1877", "1881", "1891", "1905");
        a.add("In which year was the first US Open tennis tournament held?", C, "Hard", "1881", "1877", "1891", "1900");
        a.add("In which year was the first French Open (Roland Garros) tennis tournament held?", C, "Hard", "1891", "1877", "1905", "1925");
        a.add("In which year was the first Australian Open tennis tournament held?", C, "Hard", "1905", "1881", "1891", "1925");
        a.add("Australian Margaret Court holds a record for how many singles Grand Slam titles?", C, "Hard", "24", "22", "20", "18");
        a.add("Which Australian player achieved the calendar Grand Slam in 1969?", C, "Hard", "Rod Laver", "Ken Rosewall", "John Newcombe", "Lew Hoad");
        a.add("Which European football club has won the most UEFA Champions League / European Cup titles?", C, "Hard", "Real Madrid", "AC Milan", "Bayern Munich", "Liverpool");
        a.add("Which player has won the most Ballon d'Or trophies in football history?", C, "Hard", "Lionel Messi", "Cristiano Ronaldo", "Michel Platini", "Johan Cruyff");
        a.add("Who is the all-time leading goal scorer in NHL history?", C, "Hard", "Wayne Gretzky", "Gordie Howe", "Alex Ovechkin", "Jaromir Jagr");
        a.add("Who is the NBA's all-time leading regular-season scorer (recent)?", C, "Hard", "LeBron James", "Kareem Abdul-Jabbar", "Michael Jordan", "Karl Malone");
        a.add("Which NFL team famously lost four consecutive Super Bowls in the early 1990s?", C, "Hard", "Buffalo Bills", "Minnesota Vikings", "Denver Broncos", "Atlanta Falcons");
        a.add("Which city hosted the 1936 Summer Olympic Games?", C, "Hard", "Berlin", "Helsinki", "Antwerp", "Amsterdam");
        a.add("Which city hosted the 1980 Summer Olympic Games?", C, "Hard", "Moscow", "Montreal", "Munich", "Mexico City");
        a.add("Which city hosted the 1984 Summer Olympic Games?", C, "Hard", "Los Angeles", "Seoul", "Mexico City", "Moscow");
        a.add("Which city hosted the 2012 Summer Olympic Games?", C, "Hard", "London", "Beijing", "Rio de Janeiro", "Athens");
        a.add("Which city hosted the 2016 Summer Olympic Games?", C, "Hard", "Rio de Janeiro", "London", "Tokyo", "Sydney");
        a.add("Which city hosted the (delayed) 2020 Summer Olympic Games?", C, "Hard", "Tokyo", "Beijing", "Paris", "Seoul");
        a.add("Which city hosted the 2024 Summer Olympic Games?", C, "Hard", "Paris", "Los Angeles", "Brisbane", "Tokyo");
        a.add("Which city is scheduled to host the 2028 Summer Olympic Games?", C, "Hard", "Los Angeles", "Brisbane", "Paris", "Madrid");
        a.add("Which city is scheduled to host the 2032 Summer Olympic Games?", C, "Hard", "Brisbane", "Madrid", "Doha", "Toronto");
        a.add("Which country leads the all-time Summer Olympics gold medal table?", C, "Hard", "United States", "Soviet Union (historical)", "China", "Great Britain");
        a.add("In which year was the Indian Premier League (IPL) cricket tournament first held?", C, "Hard", "2008", "2005", "2010", "2003");
        a.add("Which team won the first season of the Indian Premier League in 2008?", C, "Hard", "Rajasthan Royals", "Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore");
        a.add("Which player holds the record for most goals scored in a single FIFA World Cup tournament?", C, "Hard", "Just Fontaine", "Pele", "Gerd Muller", "Miroslav Klose");
        a.add("Who scored the highest individual innings in Test cricket history?", C, "Hard", "Brian Lara", "Don Bradman", "Sachin Tendulkar", "Mahela Jayawardene");
        a.add("Who is the leading wicket-taker of all time in Test cricket?", C, "Hard", "Muttiah Muralitharan", "Shane Warne", "Anil Kumble", "Glenn McGrath");
        a.add("Who has scored the most centuries in Test cricket history?", C, "Hard", "Sachin Tendulkar", "Ricky Ponting", "Jacques Kallis", "Kumar Sangakkara");
        a.add("Who is the all-time leading run scorer across all international cricket?", C, "Hard", "Sachin Tendulkar", "Ricky Ponting", "Kumar Sangakkara", "Mahela Jayawardene");
        a.add("In which month is the Boston Marathon traditionally held?", C, "Hard", "April", "March", "May", "October");
        a.add("In which month is the London Marathon traditionally held?", C, "Hard", "April", "May", "September", "October");
        a.add("In which year was the very first Super Bowl played?", C, "Hard", "1967", "1961", "1972", "1955");
        a.add("Which boxer did Muhammad Ali defeat in the 'Rumble in the Jungle' in 1974?", C, "Hard", "George Foreman", "Joe Frazier", "Larry Holmes", "Sonny Liston");
        a.add("In which year did the U.S. men's hockey team's 'Miracle on Ice' upset the Soviet Union?", C, "Hard", "1980", "1976", "1984", "1972");
        a.add("Which country has won the most men's Cricket World Cup titles?", C, "Hard", "Australia", "India", "West Indies", "England");
        a.add("In which year was the very first men's Cricket World Cup held?", C, "Hard", "1975", "1979", "1983", "1971");
        a.add("Which team won the very first men's Cricket World Cup in 1975?", C, "Hard", "West Indies", "Australia", "England", "India");
        a.add("How many national teams will compete in the FIFA World Cup 2026 finals?", C, "Hard", "48", "32", "40", "36");
        a.add("How many national teams competed in the very first FIFA World Cup in 1930?", C, "Hard", "13", "16", "10", "20");
        a.add("Which boxer did Muhammad Ali fight in the 1975 'Thrilla in Manila'?", C, "Hard", "Joe Frazier", "George Foreman", "Ken Norton", "Larry Holmes");
        a.add("Who was the first man to officially run the mile in under 4 minutes?", C, "Hard", "Roger Bannister", "John Landy", "Sebastian Coe", "Steve Cram");
        a.add("Who set the men's 100m world record of 9.58 seconds in 2009?", C, "Hard", "Usain Bolt", "Tyson Gay", "Asafa Powell", "Yohan Blake");
        a.add("Who won 4 individual gold medals at the 1948 London Olympics, the first woman to do so?", C, "Hard", "Fanny Blankers-Koen", "Wilma Rudolph", "Babe Didrikson", "Florence Griffith Joyner");
        a.add("As of 2023, which country had won the most men's Rugby World Cup titles?", C, "Hard", "South Africa", "New Zealand", "Australia", "England");
        a.add("Which Formula One driver holds the record for most career race wins (recent)?", C, "Hard", "Lewis Hamilton", "Michael Schumacher", "Ayrton Senna", "Sebastian Vettel");
        a.add("Which Formula One constructor has won the most Constructors' Championships (historical)?", C, "Hard", "Ferrari", "McLaren", "Williams", "Mercedes");
        a.add("FC Barcelona plays its home games at which stadium (officially named since 2022)?", C, "Hard", "Spotify Camp Nou", "Estadi Olimpic", "Mestalla", "Vicente Calderon");
        a.add("In which sport is the Borg-Warner Trophy awarded?", C, "Hard", "IndyCar (Indianapolis 500)", "NASCAR", "Formula 1", "Le Mans");
        a.add("Who is widely considered cricket's greatest Test batsman, with an average of 99.94?", C, "Hard", "Don Bradman", "Sachin Tendulkar", "Sir Garfield Sobers", "Brian Lara");
        a.add("Which boxer was the youngest world heavyweight champion ever, becoming so in 1986?", C, "Hard", "Mike Tyson", "Muhammad Ali", "Floyd Patterson", "Joe Louis");
        a.add("Who is widely regarded as the inventor (or codifier) of modern volleyball in 1895?", C, "Hard", "William G. Morgan", "James Naismith", "Walter Camp", "Charles Miller");
    }
}
