package com.quiz.config.seeds;

public final class SpringBootSeeder {
    private static final String C = "Spring Boot";
    private SpringBootSeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("Which annotation marks a Java class as a generic Spring-managed component?", C, "Easy", "@Component", "@Bean", "@Module", "@SpringClass");
        a.add("Which annotation maps HTTP PUT requests in Spring MVC?", C, "Easy", "@PutMapping", "@PostMapping", "@PatchMapping", "@UpdateMapping");
        a.add("Which annotation maps HTTP DELETE requests in Spring MVC?", C, "Easy", "@DeleteMapping", "@RemoveMapping", "@DropMapping", "@PutMapping");
        a.add("Which annotation maps HTTP PATCH requests in Spring MVC?", C, "Easy", "@PatchMapping", "@PutMapping", "@PostMapping", "@UpdateMapping");
        a.add("What is the default port used by the embedded server in Spring Boot?", C, "Easy", "8080", "80", "8000", "443");
        a.add("Which Spring Boot starter provides core web/REST support including embedded Tomcat?", C, "Easy", "spring-boot-starter-web", "spring-boot-starter-core", "spring-boot-starter-rest", "spring-boot-starter-mvc");
        a.add("Which Spring Boot starter brings in Spring Data JPA?", C, "Easy", "spring-boot-starter-data-jpa", "spring-boot-starter-jdbc", "spring-boot-starter-orm", "spring-boot-starter-hibernate");
        a.add("Which Spring Boot starter brings in Spring Security?", C, "Easy", "spring-boot-starter-security", "spring-boot-starter-auth", "spring-boot-starter-oauth", "spring-boot-starter-protect");
        a.add("Which Spring Boot starter brings in test dependencies (JUnit, Mockito, etc.)?", C, "Easy", "spring-boot-starter-test", "spring-boot-starter-tests", "spring-boot-starter-junit", "spring-boot-starter-spec");
        a.add("Which Spring Boot starter enables Bean Validation (Hibernate Validator)?", C, "Easy", "spring-boot-starter-validation", "spring-boot-starter-bean-validator", "spring-boot-starter-jsr303", "spring-boot-starter-validate");
        a.add("Which Spring Boot starter enables the Actuator monitoring endpoints?", C, "Easy", "spring-boot-starter-actuator", "spring-boot-starter-monitor", "spring-boot-starter-metrics", "spring-boot-starter-admin");
        a.add("What is the build plugin name commonly used by Spring Boot projects in Maven?", C, "Easy", "spring-boot-maven-plugin", "maven-spring-plugin", "spring-build-plugin", "boot-maven-plugin");
        a.add("Which annotation combines @Configuration, @EnableAutoConfiguration, and @ComponentScan?", C, "Easy", "@SpringBootApplication", "@SpringApplication", "@EnableSpringBoot", "@SpringContext");
        a.add("To run a packaged Spring Boot JAR from the command line, you typically use which command?", C, "Easy", "java -jar app.jar", "mvn java app", "spring run app", "java -classpath app.jar");
        a.add("Which Maven goal runs a Spring Boot application during development?", C, "Easy", "spring-boot:run", "boot:run", "spring:start", "package:run");
        a.add("What is the typical default value of the 'spring.profiles.active' setting?", C, "Easy", "default", "dev", "prod", "test");
        a.add("Which annotation injects an externalized configuration property value into a field?", C, "Easy", "@Value", "@Property", "@Config", "@Inject");
        a.add("Which placeholder syntax is used inside @Value to refer to a property?", C, "Easy", "${property.name}", "#{property.name}", "@{property.name}", "%{property.name}");
        a.add("Which annotation binds a URI template variable to a method parameter?", C, "Easy", "@PathVariable", "@RequestParam", "@RequestBody", "@RequestHeader");
        a.add("Which annotation binds a single query parameter to a method parameter?", C, "Easy", "@RequestParam", "@PathVariable", "@RequestBody", "@RequestPart");
        a.add("Which annotation binds the HTTP request body to a method parameter (commonly JSON)?", C, "Easy", "@RequestBody", "@RequestParam", "@PathVariable", "@ResponseBody");
        a.add("Which website is the official Spring Initializr scaffold for Spring Boot projects?", C, "Easy", "start.spring.io", "spring.io/start", "init.spring.io", "boot.spring.io");
        a.add("By default, where do Spring Boot project resources (like application.properties) live in Maven layout?", C, "Easy", "src/main/resources", "src/main/java", "src/properties", "config/");
        a.add("Which file name is used for the YAML form of the Spring Boot configuration file?", C, "Easy", "application.yml", "config.yml", "spring.yaml", "boot.yaml");
        a.add("Which Spring Boot starter brings in the Thymeleaf templating engine?", C, "Easy", "spring-boot-starter-thymeleaf", "spring-boot-starter-templates", "spring-boot-starter-mustache", "spring-boot-starter-html");
        a.add("Which Spring Boot starter brings in basic JDBC support?", C, "Easy", "spring-boot-starter-jdbc", "spring-boot-starter-data-jdbc", "spring-boot-starter-sql", "spring-boot-starter-database");
        a.add("Which Spring Boot starter brings in Spring Data Redis?", C, "Easy", "spring-boot-starter-data-redis", "spring-boot-starter-redis", "spring-boot-starter-cache-redis", "spring-boot-starter-jedis");
        a.add("Which Spring Boot starter brings in Spring Data MongoDB?", C, "Easy", "spring-boot-starter-data-mongodb", "spring-boot-starter-mongodb", "spring-boot-starter-mongo", "spring-boot-starter-data-mongo");
        a.add("Which Spring Boot starter brings in AMQP/RabbitMQ messaging?", C, "Easy", "spring-boot-starter-amqp", "spring-boot-starter-rabbitmq", "spring-boot-starter-mq", "spring-boot-starter-messaging");
        a.add("Which annotation marks a method as a scheduled task?", C, "Easy", "@Scheduled", "@Timer", "@CronJob", "@Schedule");
        a.add("Which annotation must be on a configuration class to enable scheduling support?", C, "Easy", "@EnableScheduling", "@EnableTimers", "@EnableTasks", "@EnableScheduler");
        a.add("Which annotation enables Spring's asynchronous method execution support?", C, "Easy", "@EnableAsync", "@EnableConcurrent", "@EnableThreads", "@EnableExecutor");
        a.add("Which annotation marks a method to run asynchronously when invoked?", C, "Easy", "@Async", "@Background", "@Task", "@Future");
        a.add("Which annotation enables Spring's caching abstraction in a configuration class?", C, "Easy", "@EnableCaching", "@EnableCache", "@CacheConfig", "@UseCache");
        a.add("Which annotation marks a method's return value as cacheable?", C, "Easy", "@Cacheable", "@Cache", "@MemoCache", "@StoreCache");
        a.add("Which annotation evicts entries from a Spring cache when invoked?", C, "Easy", "@CacheEvict", "@CacheClear", "@RemoveCache", "@DeleteCache");
        a.add("Which annotation updates a Spring cache without skipping method execution?", C, "Easy", "@CachePut", "@Cacheable(update=true)", "@CacheUpdate", "@CacheReplace");
        a.add("Which annotation binds a single HTTP request header to a method parameter?", C, "Easy", "@RequestHeader", "@HeaderParam", "@Header", "@RequestParam");
        a.add("Which annotation reads a cookie value into a controller method parameter?", C, "Easy", "@CookieValue", "@Cookie", "@RequestCookie", "@ReadCookie");
        a.add("Which annotation must appear on a configuration class to enable JPA repository scanning?", C, "Easy", "@EnableJpaRepositories", "@EnableJpa", "@EnableRepositories", "@EnableData");
        a.add("Which Spring Data interface is the most commonly extended starting point for JPA repositories?", C, "Easy", "JpaRepository", "CrudRepository only", "PagingRepository only", "JpaCrud");
        a.add("Which annotation lets you set the HTTP status code returned by a controller method?", C, "Easy", "@ResponseStatus", "@HttpStatus", "@StatusCode", "@ResponseCode");
        a.add("Which annotation indicates that the return value of a controller method should be written directly into the HTTP response body?", C, "Easy", "@ResponseBody", "@ResponseEntity", "@Body", "@Json");
        a.add("Which annotation marks a class as a traditional MVC controller (typically returning view names)?", C, "Easy", "@Controller", "@RestController", "@MvcController", "@WebController");
        a.add("Which Spring tool helps generate a standalone runnable Spring Boot JAR (fat JAR)?", C, "Easy", "spring-boot-maven-plugin (or Gradle plugin)", "Maven assembly only", "Maven shade only", "Java packager");
        a.add("In Spring, what does the abbreviation IoC stand for?", C, "Easy", "Inversion of Control", "Injection of Components", "Instance of Class", "Internet of Containers");
        a.add("In Spring, what does DI stand for?", C, "Easy", "Dependency Injection", "Data Integration", "Dynamic Inheritance", "Dependency Inheritance");
        a.add("Which Spring Boot file customizes the startup banner text?", C, "Easy", "banner.txt in src/main/resources", "startup.txt", "boot-banner.html", "logo.png only");
        a.add("Which property toggles whether the Spring Boot startup banner is printed?", C, "Easy", "spring.main.banner-mode", "spring.banner.print", "spring.boot.banner", "spring.startup.banner");
        a.add("Which Spring Boot Maven goal builds an executable fat JAR?", C, "Easy", "spring-boot:repackage (often via package goal)", "boot:assemble", "spring:fatjar", "package:executable");

        // ===== Medium (50) =====
        a.add("What is the standard name for Spring's IoC container interface?", C, "Medium", "ApplicationContext", "BeanContext", "ServiceLocator", "InjectionContainer");
        a.add("Which dependency injection style is generally recommended in modern Spring code?", C, "Medium", "Constructor injection", "Field injection", "Setter injection", "Static injection");
        a.add("What is the default scope for Spring beans?", C, "Medium", "singleton", "prototype", "request", "session");
        a.add("Which annotation overrides the default scope on a Spring bean?", C, "Medium", "@Scope", "@Singleton", "@BeanScope", "@Lifecycle");
        a.add("Which annotation marks a method that handles exceptions thrown by handler methods in the same controller?", C, "Medium", "@ExceptionHandler", "@HandleException", "@ErrorHandler", "@Throws");
        a.add("What is the default URL path of the Spring Boot H2 console (when enabled)?", C, "Medium", "/h2-console", "/console", "/db", "/h2");
        a.add("Which Spring property enables the H2 web console?", C, "Medium", "spring.h2.console.enabled", "spring.h2.web.enabled", "spring.h2.ui", "spring.h2.console");
        a.add("Which Spring property sets the embedded server's HTTP port?", C, "Medium", "server.port", "spring.port", "server.http.port", "spring.server.port");
        a.add("Which Spring property sets the JDBC URL of the primary datasource?", C, "Medium", "spring.datasource.url", "spring.db.url", "datasource.url", "spring.jdbc.url");
        a.add("Which Spring property sets the username for the primary datasource?", C, "Medium", "spring.datasource.username", "spring.db.user", "datasource.user", "spring.jdbc.username");
        a.add("Which Spring property sets the password for the primary datasource?", C, "Medium", "spring.datasource.password", "spring.db.password", "datasource.password", "spring.jdbc.password");
        a.add("Which property selects the active Spring profile(s) at runtime?", C, "Medium", "spring.profiles.active", "spring.active.profile", "spring.profile.use", "active.profile");
        a.add("Which property sets a logical application name?", C, "Medium", "spring.application.name", "app.name", "spring.app.name", "application.id");
        a.add("Which logging framework is the default logging provider in Spring Boot?", C, "Medium", "Logback (via SLF4J)", "Log4j 1", "java.util.logging only", "Tinylog");
        a.add("Which property pattern overrides the log level for a specific package?", C, "Medium", "logging.level.<package>", "log.level.<package>", "logger.level.<package>", "spring.log.level.<package>");
        a.add("Which class is most commonly used to build typed HTTP responses in a Spring controller?", C, "Medium", "ResponseEntity", "HttpResponse", "ResponseObject", "ServletResponse");
        a.add("Which Spring class provides synchronous, blocking HTTP client functionality (older API)?", C, "Medium", "RestTemplate", "WebClient", "OkHttpClient only", "HttpURLConnection");
        a.add("Which Spring class is the modern, reactive, non-blocking HTTP client?", C, "Medium", "WebClient", "RestTemplate", "AsyncRestTemplate only", "ReactClient");
        a.add("Which annotation triggers method-level validation of method parameters by Spring?", C, "Medium", "@Validated", "@Verified", "@Validate", "@Check");
        a.add("Which annotation triggers Bean Validation on a request body or model object?", C, "Medium", "@Valid", "@Validated", "@Verified", "@CheckBody");
        a.add("Which annotation marks a method as a listener for application events?", C, "Medium", "@EventListener", "@Listener", "@OnEvent", "@Subscribe");
        a.add("Which annotation marks a class as additional test configuration?", C, "Medium", "@TestConfiguration", "@TestConfig", "@TestBeans", "@SpringTestConfiguration");
        a.add("Which annotation bootstraps a full Spring application context for an integration test?", C, "Medium", "@SpringBootTest", "@SpringTest", "@IntegrationTest", "@BootTest");
        a.add("Which annotation slices a test to focus only on the Spring MVC web layer?", C, "Medium", "@WebMvcTest", "@RestTest", "@WebTest", "@MvcTest");
        a.add("Which annotation slices a test to focus only on the JPA persistence layer?", C, "Medium", "@DataJpaTest", "@JpaTest", "@DataTest", "@PersistenceTest");
        a.add("Which annotation creates a Mockito mock and registers it in the Spring application context?", C, "Medium", "@MockBean", "@Mock", "@MockitoBean", "@AutoMock");
        a.add("Which annotation enables CORS settings on a Spring controller or method?", C, "Medium", "@CrossOrigin", "@AllowOrigin", "@CorsConfig", "@WebOrigin");
        a.add("Which annotation binds property values to a strongly-typed configuration class?", C, "Medium", "@ConfigurationProperties", "@PropertySource", "@PropertiesBinding", "@BindProperties");
        a.add("Which Spring Data abstraction allows you to declare paged queries that return Page<T>?", C, "Medium", "Pageable / Page<T>", "Sort only", "Stream<T>", "PageQuery");
        a.add("Which database migration tool is widely used with Spring Boot via auto-configuration?", C, "Medium", "Flyway (or Liquibase)", "Hibernate Validator", "MyBatis Generator", "Spring Migrate");
        a.add("Which JSON library does Spring Boot use by default to (de)serialize JSON?", C, "Medium", "Jackson", "Gson", "JSON-B", "org.json");
        a.add("Which Jackson annotation excludes a field from JSON serialization?", C, "Medium", "@JsonIgnore", "@JsonHide", "@JsonExclude", "@SkipJson");
        a.add("Which Jackson annotation customizes the JSON name of a Java field?", C, "Medium", "@JsonProperty(\"name\")", "@JsonName(\"name\")", "@JsonRename(\"name\")", "@JsonAlias only");
        a.add("Which Spring Boot Actuator endpoint reports application health by default?", C, "Medium", "/actuator/health", "/health/check", "/status", "/system/health");
        a.add("Which Spring Boot Actuator endpoint exposes static info contributors by default?", C, "Medium", "/actuator/info", "/about", "/version", "/build-info");
        a.add("Which Spring Boot property exposes all Actuator endpoints over HTTP?", C, "Medium", "management.endpoints.web.exposure.include=*", "management.actuator.expose-all=true", "spring.actuator.expose-all=true", "management.endpoints.expose=*");
        a.add("Which Spring annotation binds a path variable using a different name than the parameter?", C, "Medium", "@PathVariable(\"customName\")", "@PathParam(name=\"customName\")", "@URIVariable(\"customName\")", "@PathRename(\"customName\")");
        a.add("Which file format does Spring Boot recognize natively in addition to .properties for configuration?", C, "Medium", "YAML (.yml / .yaml)", "TOML", "JSON5", "INI");
        a.add("Which annotation marks a class as a controller AND combines @ResponseBody for all handler methods?", C, "Medium", "@RestController", "@WebController", "@JsonController", "@ApiController");
        a.add("Which Spring annotation binds a request part (e.g., a multipart upload) to a parameter?", C, "Medium", "@RequestPart", "@RequestParam(part=true)", "@MultipartRequest", "@FilePart");
        a.add("Which annotation indicates that a controller method consumes/produces given media types?", C, "Medium", "@RequestMapping(consumes=..., produces=...)", "@MediaType(...)", "@ContentType(...)", "@Accept(...)");
        a.add("Which annotation tells Spring to treat all controller methods as @ResponseBody by default?", C, "Medium", "@RestController", "@ResponseEntity", "@JsonResponse", "@AutoBody");
        a.add("Which Spring class wraps an HTTP request entity (headers + body) for outbound calls?", C, "Medium", "RequestEntity", "HttpEntity only", "RestEntity", "OutgoingRequest");
        a.add("Which annotation marks a parameter as receiving the entire HTTP session attribute set?", C, "Medium", "@SessionAttributes (with @ModelAttribute)", "@SessionParam", "@HttpSession", "@SessionScope");
        a.add("Which Spring Boot feature reloads the running app when classpath files change in development?", C, "Medium", "Spring Boot DevTools", "Spring Reload", "Boot Watch", "DevReload");
        a.add("Which testing utility built into Spring lets you simulate HTTP requests against MVC controllers?", C, "Medium", "MockMvc", "WebClientTester", "HttpSimulator", "TestRestTemplate only");
        a.add("Which Spring class provides a synchronous test-time HTTP client that runs against the embedded server?", C, "Medium", "TestRestTemplate", "RestTemplate only", "WebClient.Builder.testClient", "HttpTester");
        a.add("Which annotation marks a Spring test to run with a fresh ApplicationContext per test method?", C, "Medium", "@DirtiesContext", "@FreshContext", "@PerMethodContext", "@CleanContext");
        a.add("Which Spring Test annotation runs the test method inside a transaction that is rolled back at the end?", C, "Medium", "@Transactional (in tests)", "@Rollback only", "@TransactionalTest", "@TestTransactional");
        a.add("Which Spring tool helps generate OpenAPI/Swagger documentation from controllers (community)?", C, "Medium", "springdoc-openapi", "spring-restdocs only", "spring-openapi-core", "spring-swagger-gen");

        // ===== Hard (50) =====
        a.add("Which annotation runs a method just after Spring has populated all dependencies of a bean?", C, "Hard", "@PostConstruct", "@PreInitialize", "@AfterInjection", "@Initialize");
        a.add("Which annotation runs a method just before a bean is destroyed by the container?", C, "Hard", "@PreDestroy", "@AfterShutdown", "@OnDestroy", "@TerminateBean");
        a.add("Which interface is the legacy alternative to @PostConstruct for bean initialization?", C, "Hard", "InitializingBean (afterPropertiesSet)", "DisposableBean", "BeanPostProcessor", "Lifecycle only");
        a.add("Which interface is the legacy alternative to @PreDestroy for bean cleanup?", C, "Hard", "DisposableBean (destroy)", "InitializingBean", "Lifecycle", "Closeable");
        a.add("Which @SpringBootApplication attribute lets you exclude specific auto-configurations?", C, "Hard", "exclude = {SomeAutoConfiguration.class}", "ignore = {...}", "skip = {...}", "disable = {...}");
        a.add("Which annotation forces Spring to instantiate a bean only when first accessed?", C, "Hard", "@Lazy", "@OnDemand", "@Defer", "@Optional");
        a.add("Which Spring AOP advice type wraps a method invocation and can short-circuit it?", C, "Hard", "@Around", "@Before", "@After", "@AfterReturning");
        a.add("Which annotation declares a reusable AspectJ pointcut expression?", C, "Hard", "@Pointcut", "@Cut", "@Joinpoint", "@PointcutExpression");
        a.add("Spring Boot 3 requires which minimum Java version?", C, "Hard", "Java 17", "Java 11", "Java 8", "Java 21");
        a.add("Spring Boot 3 migrated the Servlet API namespace from javax.* to which new namespace?", C, "Hard", "jakarta.*", "java.servlet.*", "spring.servlet.*", "openapi.servlet.*");
        a.add("Which Spring Boot Actuator endpoint returns a thread dump?", C, "Hard", "/actuator/threaddump", "/actuator/threads", "/actuator/dumps", "/actuator/stack");
        a.add("Which Spring Boot Actuator endpoint exposes environment properties (filtered)?", C, "Hard", "/actuator/env", "/actuator/properties", "/actuator/config", "/actuator/system");
        a.add("Which Spring Boot Actuator endpoint exposes named metrics by id?", C, "Hard", "/actuator/metrics/{name}", "/actuator/measure/{name}", "/actuator/stats/{name}", "/actuator/data/{name}");
        a.add("Which embedded servlet containers does Spring Boot officially support out of the box?", C, "Hard", "Tomcat, Jetty, and Undertow", "Tomcat and JBoss", "Tomcat and Netty", "Jetty and Wildfly only");
        a.add("To switch from Tomcat to Jetty in Spring Boot, what must you usually do?", C, "Hard", "Exclude spring-boot-starter-tomcat and add spring-boot-starter-jetty", "Set server.engine=jetty", "Add @EnableJetty", "Replace spring-boot-starter-web with spring-boot-starter-jetty");
        a.add("Which Spring framework provides a reactive, non-blocking web stack as an alternative to MVC?", C, "Hard", "Spring WebFlux", "Spring Reactive MVC", "Spring Async", "Spring Stream");
        a.add("Which two reactive types are central to Project Reactor and Spring WebFlux?", C, "Hard", "Mono and Flux", "Single and Observable", "Promise and Stream", "Future and Channel");
        a.add("Which Spring Cloud project is a popular service registry/discovery server?", C, "Hard", "Spring Cloud Netflix Eureka", "Spring Cloud Consul UI", "Spring Cloud Discovery", "Spring Cloud Registrar");
        a.add("Which Spring Cloud project provides an API gateway based on the reactive stack?", C, "Hard", "Spring Cloud Gateway", "Spring Cloud Zuul (legacy)", "Spring Cloud Routes", "Spring Cloud Edge");
        a.add("Which library has largely replaced the deprecated Hystrix as Spring Cloud's circuit breaker?", C, "Hard", "Resilience4j", "Sentinel only", "Hystrix-X", "Failsafe only");
        a.add("Which Spring Cloud project centralizes configuration for distributed apps?", C, "Hard", "Spring Cloud Config", "Spring Boot Config", "Spring Distributed Settings", "Spring Cloud Settings");
        a.add("Which community project provides a UI for managing Spring Boot Actuator endpoints across services?", C, "Hard", "Spring Boot Admin (codecentric)", "Spring Boot Console", "Spring Boot Inspector", "Spring Boot Manage");
        a.add("In Spring Security, which bean type defines the security filter chain (preferred since 5.7)?", C, "Hard", "SecurityFilterChain", "WebSecurityConfigurerAdapter (deprecated)", "AuthenticationManager only", "FilterRegistrationBean only");
        a.add("Which annotation enables Spring Security in a Spring Boot configuration?", C, "Hard", "@EnableWebSecurity", "@EnableSecurity", "@EnableSpringSecurity", "@SecureWeb");
        a.add("Which annotation enables Spring Security's pre/post authorization annotations?", C, "Hard", "@EnableMethodSecurity", "@EnablePreAuthorize", "@EnableSecurityAnnotations", "@EnableSecuredAnnotations");
        a.add("Which annotation guards a method with a SpEL expression evaluated before invocation?", C, "Hard", "@PreAuthorize", "@Secured", "@RolesAllowed", "@PostAuthorize");
        a.add("Which annotation guards a method by evaluating a SpEL expression on the return value?", C, "Hard", "@PostAuthorize", "@PreAuthorize", "@Secured", "@AfterAuthorize");
        a.add("Which Spring Security default behavior often surprises new users with stateful HTTP forms?", C, "Hard", "CSRF protection enabled by default", "CORS enabled by default", "Basic auth disabled by default", "All endpoints public by default");
        a.add("Which interface bean defines password hashing strategy in Spring Security?", C, "Hard", "PasswordEncoder", "PasswordHasher", "CryptoEncoder", "BCryptOnly");
        a.add("Which annotation injects the currently authenticated principal into a controller parameter?", C, "Hard", "@AuthenticationPrincipal", "@CurrentUser", "@Principal", "@Authenticated");
        a.add("Which @EnableJpaRepositories attribute customizes which packages are scanned for repositories?", C, "Hard", "basePackages", "scan", "packages", "rootPackages");
        a.add("Which annotation declares a method as transactional in Spring?", C, "Hard", "@Transactional", "@WithTransaction", "@Tx", "@DBTransaction");
        a.add("What is the default propagation behavior of @Transactional?", C, "Hard", "Propagation.REQUIRED", "Propagation.REQUIRES_NEW", "Propagation.SUPPORTS", "Propagation.MANDATORY");
        a.add("By default, on which kind of exception does Spring's @Transactional roll back?", C, "Hard", "Unchecked exceptions (RuntimeException) and Errors", "All exceptions including checked", "Only IOException", "Only SQLException");
        a.add("Which @Transactional attribute lets you specify additional checked exception types that should trigger rollback?", C, "Hard", "rollbackFor", "rollbackOnException", "exceptionTypes", "rollbackTypes");
        a.add("What is the default isolation level used by @Transactional?", C, "Hard", "Isolation.DEFAULT (database-specific default)", "Isolation.READ_COMMITTED", "Isolation.SERIALIZABLE", "Isolation.REPEATABLE_READ");
        a.add("Which Spring annotation lets you observe a non-Spring component's bean lifecycle by post-processing it?", C, "Hard", "BeanPostProcessor implementations", "@PostBean", "@LifeCycle", "@PostInit");
        a.add("Which Spring component intercepts BeanFactory configuration to modify bean definitions before instantiation?", C, "Hard", "BeanFactoryPostProcessor", "BeanPostProcessor only", "BeanModifier", "BeanDefinitionAdvisor");
        a.add("Which annotation marks a Spring controller's method as serving a Server-Sent Events stream?", C, "Hard", "Producing 'text/event-stream' content type", "@SseEndpoint", "@StreamMapping", "@ServerSentEvent");
        a.add("Which Spring property marks the embedded server's session timeout (Servlet)?", C, "Hard", "server.servlet.session.timeout", "spring.session.timeout", "server.session.timeout-mins", "spring.servlet.timeout");
        a.add("Which Spring annotation, used on tests, autoconfigures a real but in-memory web environment?", C, "Hard", "@SpringBootTest(webEnvironment=RANDOM_PORT)", "@WebTest", "@MvcServerTest", "@WebContextTest");
        a.add("Which Spring testing utility allows verifying outbound HTTP calls made by RestTemplate?", C, "Hard", "MockRestServiceServer", "MockMvc", "WebTestClient.fakeServer", "RestTester");
        a.add("Which Spring abstraction simplifies issuing HTTP messages with retry/back-off (since Spring 6/Boot 3)?", C, "Hard", "RestClient (Spring 6 sync HTTP client)", "RestTemplate2", "HttpExchangeClient", "RestService");
        a.add("Which Spring annotation aggregates multiple @Configuration classes into a single application context import?", C, "Hard", "@Import", "@Include", "@ConfigImport", "@MergeConfig");
        a.add("Which Spring class provides programmatic access to externalized configuration via Property Sources?", C, "Hard", "Environment", "ConfigEnvironment", "Properties", "PropertyManager");
        a.add("Which Spring Boot config feature lets you define hierarchical, type-safe properties classes via Java records (since 2.6)?", C, "Hard", "@ConfigurationProperties on records", "@RecordProperties", "@ImmutableProperties", "@RecordConfig");
        a.add("Which Spring annotation lets you wire a collection of beans of the same type as a List or Map?", C, "Hard", "@Autowired on a List/Map parameter", "@Inject(all=true)", "@Resources", "@Multibean");
        a.add("Which annotation explicitly declares the order in which Spring instantiates dependent beans?", C, "Hard", "@DependsOn", "@Order only", "@After", "@Sequence");
        a.add("Which Spring class is the central place to register HTTP message converters, formatters, and CORS at MVC level?", C, "Hard", "WebMvcConfigurer", "MvcInitializer", "MvcRegistrar", "MvcOptions");
        a.add("Which annotation lets you customize how Spring serializes Java 8 LocalDateTime fields to JSON?", C, "Hard", "@JsonFormat (with pattern)", "@DateFormat", "@Format(json)", "@JsonDate");
    }
}
