package com.quiz.config.seeds;

public final class TechnologySeeder {
    private static final String C = "Technology";
    private TechnologySeeder() {}

    public static void seed(QuestionAdder a) {
        // ===== Easy (50) =====
        a.add("What does USB stand for?", C, "Easy", "Universal Serial Bus", "Universal System Bus", "Unified Serial Buffer", "United Software Block");
        a.add("What does WWW stand for?", C, "Easy", "World Wide Web", "World Web Wide", "Wide World Web", "Worldwide Web Wires");
        a.add("What does PDF stand for?", C, "Easy", "Portable Document Format", "Personal Data File", "Print Document File", "Portable Data Form");
        a.add("What does GIF stand for?", C, "Easy", "Graphics Interchange Format", "General Image File", "Graphics Image Frame", "Global Internet File");
        a.add("What does JPEG stand for?", C, "Easy", "Joint Photographic Experts Group", "Java Picture Encoding Group", "Joint Pixel Encoding Graphic", "Java Photo Editor Group");
        a.add("What does VPN stand for in networking?", C, "Easy", "Virtual Private Network", "Verified Public Node", "Virtual Public Network", "Variable Private Net");
        a.add("What does SSD stand for in computer storage?", C, "Easy", "Solid State Drive", "Secure Storage Device", "Static Storage Disk", "Smart Stream Drive");
        a.add("What does HDD stand for in computer storage?", C, "Easy", "Hard Disk Drive", "High Density Drive", "High Definition Disk", "Heavy Data Disk");
        a.add("What does GPU stand for?", C, "Easy", "Graphics Processing Unit", "General Processing Unit", "Game Processing Unit", "Graphic Performance Unit");
        a.add("What does RAM stand for in computers?", C, "Easy", "Random Access Memory", "Read Access Memory", "Rapid Access Memory", "Real Active Memory");
        a.add("What does ROM stand for in computers?", C, "Easy", "Read Only Memory", "Random Only Memory", "Real Operation Memory", "Reserved Object Memory");
        a.add("What does LAN stand for?", C, "Easy", "Local Area Network", "Linked Active Node", "Long Area Network", "Local Address Node");
        a.add("What does WAN stand for?", C, "Easy", "Wide Area Network", "Wireless Active Node", "Wide Address Node", "Web Area Network");
        a.add("Who co-founded Apple along with Steve Wozniak?", C, "Easy", "Steve Jobs", "Tim Cook", "Bill Gates", "Larry Page");
        a.add("Who is the co-founder and original CEO of Facebook (now Meta)?", C, "Easy", "Mark Zuckerberg", "Sheryl Sandberg", "Jack Dorsey", "Eduardo Saverin");
        a.add("Who founded the e-commerce company Amazon?", C, "Easy", "Jeff Bezos", "Larry Ellison", "Mark Zuckerberg", "Pierre Omidyar");
        a.add("Who is the long-serving CEO most associated with Tesla, Inc.?", C, "Easy", "Elon Musk", "Steve Jobs", "Bill Gates", "Larry Page");
        a.add("Who co-founded Google with Sergey Brin?", C, "Easy", "Larry Page", "Mark Zuckerberg", "Steve Ballmer", "Elon Musk");
        a.add("Which company makes the iPhone?", C, "Easy", "Apple", "Samsung", "Google", "Microsoft");
        a.add("Which company makes the Pixel line of smartphones?", C, "Easy", "Google", "Apple", "Samsung", "Huawei");
        a.add("Which company makes the Galaxy line of smartphones?", C, "Easy", "Samsung", "Apple", "Sony", "LG");
        a.add("Which company develops the Windows operating system?", C, "Easy", "Microsoft", "Apple", "Google", "Oracle");
        a.add("Which company develops the macOS operating system?", C, "Easy", "Apple", "Microsoft", "Google", "IBM");
        a.add("Which company develops the Android mobile operating system?", C, "Easy", "Google", "Apple", "Samsung", "Nokia");
        a.add("Who is the original creator of the Linux kernel?", C, "Easy", "Linus Torvalds", "Richard Stallman", "Bjarne Stroustrup", "Ken Thompson");
        a.add("Which web browser is developed by Google?", C, "Easy", "Chrome", "Firefox", "Safari", "Edge");
        a.add("Which web browser is developed by Mozilla?", C, "Easy", "Firefox", "Chrome", "Safari", "Opera");
        a.add("Which web browser is developed by Apple?", C, "Easy", "Safari", "Chrome", "Edge", "Firefox");
        a.add("Which web browser is the current default in Windows by Microsoft?", C, "Easy", "Edge", "Internet Explorer", "Chrome", "Opera");
        a.add("Which company runs the world's most-used general search engine?", C, "Easy", "Google", "Microsoft", "Yahoo", "DuckDuckGo");
        a.add("Which email service is provided by Google?", C, "Easy", "Gmail", "Outlook", "Yahoo Mail", "Proton Mail");
        a.add("Which large video-sharing platform is owned by Google?", C, "Easy", "YouTube", "Vimeo", "TikTok", "Dailymotion");
        a.add("Which photo and video sharing app is owned by Meta?", C, "Easy", "Instagram", "Snapchat", "Pinterest", "Tumblr");
        a.add("What is the current name of the platform formerly called Twitter?", C, "Easy", "X", "Threads", "Bluesky", "Mastodon");
        a.add("Which major site is focused on professional networking and resumes?", C, "Easy", "LinkedIn", "Facebook", "Reddit", "Discord");
        a.add("Which streaming service is famous for original shows like 'Stranger Things'?", C, "Easy", "Netflix", "Hulu", "Disney+", "Peacock");
        a.add("Which music streaming service uses a green logo with sound waves?", C, "Easy", "Spotify", "Apple Music", "Tidal", "YouTube Music");
        a.add("What is Amazon's flagship cloud computing platform called?", C, "Easy", "AWS", "Azure", "GCP", "OCI");
        a.add("What is Microsoft's flagship cloud computing platform called?", C, "Easy", "Azure", "AWS", "GCP", "Bluemix");
        a.add("What is Google's flagship cloud computing platform called?", C, "Easy", "Google Cloud", "AWS", "Azure", "OpenStack");
        a.add("Which large website is the most popular host of open-source code repositories?", C, "Easy", "GitHub", "Bitbucket", "GitLab", "SourceForge");
        a.add("What is the operating system used on iPhones called?", C, "Easy", "iOS", "macOS", "Android", "watchOS");
        a.add("Who is the current CEO of Microsoft?", C, "Easy", "Satya Nadella", "Bill Gates", "Steve Ballmer", "Paul Allen");
        a.add("Who is the current CEO of Apple?", C, "Easy", "Tim Cook", "Steve Jobs", "Jony Ive", "Phil Schiller");
        a.add("In HTML, what does the 'L' in HTML stand for?", C, "Easy", "Language", "Link", "List", "Layer");
        a.add("In HTTP, what does the 'T' in HTTP stand for?", C, "Easy", "Transfer", "Text", "Type", "Token");
        a.add("Which social platform is famous for short videos and is owned by ByteDance?", C, "Easy", "TikTok", "Snapchat", "Triller", "Vine");
        a.add("Which company makes the PlayStation console?", C, "Easy", "Sony", "Nintendo", "Microsoft", "Sega");
        a.add("Which company makes the Xbox console?", C, "Easy", "Microsoft", "Sony", "Nintendo", "Atari");
        a.add("Which company makes the Switch handheld console?", C, "Easy", "Nintendo", "Sony", "Microsoft", "Sega");

        // ===== Medium (50) =====
        a.add("In which year was the original iPhone released?", C, "Medium", "2007", "2005", "2008", "2010");
        a.add("In which year was the original iPad released?", C, "Medium", "2010", "2007", "2012", "2008");
        a.add("In which year was Facebook publicly launched?", C, "Medium", "2004", "2006", "2002", "2007");
        a.add("In which year was Google founded?", C, "Medium", "1998", "1996", "2000", "2002");
        a.add("In which year was Microsoft founded?", C, "Medium", "1975", "1980", "1971", "1985");
        a.add("In which year was Apple founded?", C, "Medium", "1976", "1971", "1980", "1984");
        a.add("In which year was Amazon founded?", C, "Medium", "1994", "1996", "1998", "2000");
        a.add("In which year was Tesla, Inc. founded?", C, "Medium", "2003", "2007", "2000", "2010");
        a.add("In which year was Twitter publicly launched?", C, "Medium", "2006", "2004", "2008", "2010");
        a.add("In which year was YouTube founded?", C, "Medium", "2005", "2003", "2007", "2008");
        a.add("In which year was the first commercial Android phone released?", C, "Medium", "2008", "2006", "2009", "2010");
        a.add("In which year was Wikipedia launched?", C, "Medium", "2001", "1998", "2003", "2005");
        a.add("In which year did Linus Torvalds first release the Linux kernel?", C, "Medium", "1991", "1985", "1995", "1989");
        a.add("In which year was the first version of Microsoft Windows released?", C, "Medium", "1985", "1981", "1990", "1992");
        a.add("Which IBM personal computer launched in 1981 and helped popularize PCs?", C, "Medium", "IBM PC (model 5150)", "IBM ThinkPad", "IBM Mainframe 360", "IBM AS/400");
        a.add("In which language was the original Linux kernel primarily written?", C, "Medium", "C", "Assembly", "C++", "Pascal");
        a.add("Who, with Dennis Ritchie, developed the original Unix operating system at Bell Labs?", C, "Medium", "Ken Thompson", "Brian Kernighan", "Douglas McIlroy", "Joe Ossanna");
        a.add("Who designed the original C programming language at Bell Labs?", C, "Medium", "Dennis Ritchie", "Bjarne Stroustrup", "Brian Kernighan", "Ken Thompson");
        a.add("Who designed the C++ programming language?", C, "Medium", "Bjarne Stroustrup", "Dennis Ritchie", "Bertrand Meyer", "Anders Hejlsberg");
        a.add("Who designed the Python programming language?", C, "Medium", "Guido van Rossum", "Larry Wall", "Yukihiro Matsumoto", "Rasmus Lerdorf");
        a.add("Who designed the Ruby programming language?", C, "Medium", "Yukihiro Matsumoto", "Larry Wall", "Guido van Rossum", "Anders Hejlsberg");
        a.add("Who designed the JavaScript programming language at Netscape in 1995?", C, "Medium", "Brendan Eich", "Tim Berners-Lee", "Anders Hejlsberg", "Douglas Crockford");
        a.add("Who originally created the PHP programming language?", C, "Medium", "Rasmus Lerdorf", "Brendan Eich", "Larry Wall", "Linus Torvalds");
        a.add("Who is widely credited (with Bob Kahn) for designing the TCP/IP protocols?", C, "Medium", "Vint Cerf", "Tim Berners-Lee", "Jon Postel", "Paul Mockapetris");
        a.add("Who is generally credited with sending the first email between two networked computers?", C, "Medium", "Ray Tomlinson", "Vint Cerf", "Bob Metcalfe", "Bob Kahn");
        a.add("Which company released the first commercially successful graphical web browser, Netscape Navigator?", C, "Medium", "Netscape Communications", "Microsoft", "NCSA", "Sun Microsystems");
        a.add("In which year was the Apple Macintosh first released?", C, "Medium", "1984", "1977", "1991", "1980");
        a.add("Which open-source relational database is widely used in LAMP web stacks?", C, "Medium", "MySQL", "MongoDB", "Cassandra", "Redis");
        a.add("What is the standard default TCP port for HTTP?", C, "Medium", "80", "8080", "443", "21");
        a.add("What is the standard default TCP port for HTTPS?", C, "Medium", "443", "80", "8443", "8080");
        a.add("What is the standard default TCP port for SSH?", C, "Medium", "22", "23", "21", "25");
        a.add("What is the standard default TCP port for FTP control connections?", C, "Medium", "21", "22", "23", "20");
        a.add("What is the standard default TCP port for SMTP?", C, "Medium", "25", "110", "143", "443");
        a.add("What is the standard default port for DNS queries (UDP)?", C, "Medium", "53", "80", "123", "143");
        a.add("What is the default TCP port for MySQL?", C, "Medium", "3306", "5432", "1433", "1521");
        a.add("What is the default TCP port for PostgreSQL?", C, "Medium", "5432", "3306", "27017", "1521");
        a.add("What is the default TCP port for MongoDB?", C, "Medium", "27017", "5984", "3306", "9200");
        a.add("How many bits are there in a single byte?", C, "Medium", "8", "16", "4", "32");
        a.add("Which CSS hex color code represents pure white?", C, "Medium", "#FFFFFF", "#000000", "#FF0000", "#FFFFF0");
        a.add("Which CSS hex color code represents pure black?", C, "Medium", "#000000", "#FFFFFF", "#0000FF", "#100000");
        a.add("In binary, what is the value 1010 equal to in decimal?", C, "Medium", "10", "8", "12", "16");
        a.add("In binary, what is the value 1000 equal to in decimal?", C, "Medium", "8", "10", "16", "4");
        a.add("Which numeral system has base 16?", C, "Medium", "Hexadecimal", "Binary", "Octal", "Decimal");
        a.add("Which numeral system has base 2?", C, "Medium", "Binary", "Octal", "Hexadecimal", "Quaternary");
        a.add("Which numeral system has base 8?", C, "Medium", "Octal", "Hexadecimal", "Binary", "Senary");
        a.add("Under what pseudonym was Bitcoin first proposed in a 2008 white paper?", C, "Medium", "Satoshi Nakamoto", "Hal Finney", "Vitalik Buterin", "Nick Szabo");
        a.add("Which open-source revision control system was created by Linus Torvalds in 2005?", C, "Medium", "Git", "Mercurial", "Subversion", "Perforce");
        a.add("Which language is the basis of Microsoft's .NET TypeScript and was designed by Anders Hejlsberg?", C, "Medium", "TypeScript", "C#", "F#", "VB.NET");
        a.add("Which framework popularized the Model-View-Controller pattern in PHP web apps?", C, "Medium", "Laravel", "Symfony", "CodeIgniter", "Yii");
        a.add("Which company developed the Kotlin programming language?", C, "Medium", "JetBrains", "Google", "Oracle", "Microsoft");

        // ===== Hard (50) =====
        a.add("Which computing pioneer popularized the term 'computer bug' after finding a moth in a relay?", C, "Hard", "Grace Hopper", "John von Neumann", "Howard Aiken", "Ada Lovelace");
        a.add("Who led the team that developed the FORTRAN programming language at IBM?", C, "Hard", "John Backus", "John McCarthy", "Grace Hopper", "Edsger Dijkstra");
        a.add("Which programming language was largely shaped by Grace Hopper's work in the late 1950s?", C, "Hard", "COBOL", "FORTRAN", "ALGOL", "LISP");
        a.add("Who designed the Pascal programming language?", C, "Hard", "Niklaus Wirth", "John McCarthy", "Bjarne Stroustrup", "Edsger Dijkstra");
        a.add("Who created the LISP programming language in 1958?", C, "Hard", "John McCarthy", "Marvin Minsky", "Alan Kay", "Donald Knuth");
        a.add("Who is the principal designer of the Smalltalk programming language?", C, "Hard", "Alan Kay", "Adele Goldberg", "Dan Ingalls", "Brad Cox");
        a.add("Who is widely credited with proposing what is known today as the Turing Test?", C, "Hard", "Alan Turing", "John von Neumann", "Marvin Minsky", "Norbert Wiener");
        a.add("Who is widely considered the world's first computer programmer?", C, "Hard", "Ada Lovelace", "Grace Hopper", "Hedy Lamarr", "Adele Goldberg");
        a.add("During World War II, the Enigma machine was used to encrypt messages by which country?", C, "Hard", "Germany", "United Kingdom", "United States", "Soviet Union");
        a.add("Who coined the phrase 'Artificial Intelligence' at the 1956 Dartmouth Conference?", C, "Hard", "John McCarthy", "Marvin Minsky", "Allen Newell", "Herbert Simon");
        a.add("Who is often called the 'father of the computer' for his designs of mechanical computing engines?", C, "Hard", "Charles Babbage", "Alan Turing", "John von Neumann", "Vannevar Bush");
        a.add("What was the name of the proposed mechanical general-purpose computer designed by Charles Babbage?", C, "Hard", "Analytical Engine", "Difference Engine 2", "Babbage Machine", "Mechanical Mark I");
        a.add("Which 1979 release is widely regarded as the first 'killer app' spreadsheet for personal computers?", C, "Hard", "VisiCalc", "Lotus 1-2-3", "Excel", "SuperCalc");
        a.add("What was the name of the first Apple computer kit, designed by Steve Wozniak?", C, "Hard", "Apple I", "Apple II", "Apple III", "Lisa");
        a.add("In which famous 1984 Super Bowl ad was the original Macintosh introduced?", C, "Hard", "1984", "Hello Macintosh", "Mac is Born", "Future Now");
        a.add("ARPANET, an early packet-switched network, is most famously a precursor to which technology?", C, "Hard", "The Internet", "Telephone networks", "Cable TV", "Cellular networks");
        a.add("In which year did ARPANET send its first message between two computers?", C, "Hard", "1969", "1962", "1972", "1959");
        a.add("Which IEEE standard family is most associated with Wi-Fi wireless networking?", C, "Hard", "802.11", "802.3", "802.15", "802.16");
        a.add("In storage, what does the acronym SCSI stand for?", C, "Hard", "Small Computer System Interface", "Secure Computing System Interface", "Standard Computing Storage Interconnect", "System Coupled Storage Interface");
        a.add("In email, what does the acronym SMTP stand for?", C, "Hard", "Simple Mail Transfer Protocol", "Standard Mail Transport Procedure", "Synchronous Message Transfer Protocol", "Server Mail Transmission Protocol");
        a.add("In file transfer, what does the acronym FTP stand for?", C, "Hard", "File Transfer Protocol", "Fast Transit Protocol", "Fixed Transmission Protocol", "Forwarded Transport Procedure");
        a.add("In web protocols, what does the acronym HTTP stand for?", C, "Hard", "Hypertext Transfer Protocol", "Hypertext Transport Procedure", "Hyperlink Transfer Protocol", "Hosted Text Transmission Protocol");
        a.add("What does the acronym ASCII stand for in computing?", C, "Hard", "American Standard Code for Information Interchange", "American Standard Coded Information Index", "American System Code for Internet Interchange", "Automated Standard Coding for Information Interchange");
        a.add("In storage, what does RAID stand for?", C, "Hard", "Redundant Array of Independent Disks", "Random Array of Independent Disks", "Redundant Allocation of Internal Drives", "Reliable Array of Inexpensive Drives");
        a.add("In cryptography, what does SSL stand for?", C, "Hard", "Secure Sockets Layer", "Secure Server Layer", "Secure Socket Link", "Standard Secure Layer");
        a.add("In cryptography, what does TLS stand for?", C, "Hard", "Transport Layer Security", "Transmission Layer Security", "Trusted Link Security", "Tunneling Layer Security");
        a.add("In web services, what does SOAP stand for?", C, "Hard", "Simple Object Access Protocol", "Service Oriented Application Protocol", "Standard Object Access Protocol", "Streaming Object Access Procedure");
        a.add("In web architecture, what does REST stand for?", C, "Hard", "Representational State Transfer", "Reliable Stateful Transfer", "Remote Endpoint Service Transfer", "Representational Service Transfer");
        a.add("In email standards, what does MIME stand for?", C, "Hard", "Multipurpose Internet Mail Extensions", "Multipurpose Internet Message Encoding", "Modular Internet Mail Encoding", "Managed Internet Mail Extensions");
        a.add("What is the standard default TCP port for IMAP?", C, "Hard", "143", "110", "993", "995");
        a.add("What is the standard default TCP port for POP3?", C, "Hard", "110", "143", "995", "993");
        a.add("What is the standard default TCP port for Telnet?", C, "Hard", "23", "22", "25", "21");
        a.add("What is the standard default TCP port for Microsoft Remote Desktop (RDP)?", C, "Hard", "3389", "5900", "1433", "5432");
        a.add("What is the standard default TCP port for VNC remote desktop displays?", C, "Hard", "5900", "5800", "3389", "5901");
        a.add("Approximately how many addresses are in the IPv4 address space?", C, "Hard", "About 4.3 billion", "About 1 billion", "About 65 thousand", "About 16 million");
        a.add("How many bits are in an IPv6 address?", C, "Hard", "128", "64", "32", "256");
        a.add("Which IPv4 address is the standard local loopback address?", C, "Hard", "127.0.0.1", "192.168.0.1", "10.0.0.1", "0.0.0.0");
        a.add("Which subnet mask corresponds to a /24 IPv4 network?", C, "Hard", "255.255.255.0", "255.255.0.0", "255.0.0.0", "255.255.255.255");
        a.add("In which year was the first official version of the Java programming language released?", C, "Hard", "1995", "1991", "1998", "2000");
        a.add("In which year was the first official version of Python released?", C, "Hard", "1991", "1989", "1995", "2000");
        a.add("In which year was the first official version of Ruby released?", C, "Hard", "1995", "1991", "1999", "2002");
        a.add("In which year was JavaScript first released as part of Netscape Navigator 2.0?", C, "Hard", "1995", "1993", "1997", "1999");
        a.add("In which year was the first official version of PHP released?", C, "Hard", "1995", "1993", "1997", "2000");
        a.add("In which year was Mac OS X 10.0 (Cheetah) released?", C, "Hard", "2001", "1999", "2003", "2005");
        a.add("Which Oak Ridge supercomputer was the first to achieve sustained exascale performance in 2022?", C, "Hard", "Frontier", "Summit", "Sierra", "Aurora");
        a.add("Which 1990s cryptographic hash function, designed by NSA, is now considered cryptographically broken?", C, "Hard", "SHA-1", "SHA-256", "MD2", "BLAKE2");
        a.add("Which company developed the original Ethernet local area networking technology?", C, "Hard", "Xerox PARC", "IBM", "Bell Labs", "Intel");
        a.add("Which programming language was originally named 'Oak' before being renamed?", C, "Hard", "Java", "JavaScript", "Kotlin", "Scala");
        a.add("Which 1968 demo by Doug Engelbart introduced the mouse, hypertext, and video conferencing?", C, "Hard", "The Mother of All Demos", "The Dynabook Demo", "The Xerox Star Demo", "The Hypercard Reveal");
        a.add("Which programming concept did Alan Kay's Smalltalk help popularize?", C, "Hard", "Object-Oriented Programming", "Functional Programming", "Logic Programming", "Aspect-Oriented Programming");
    }
}
